pentaho/big-data-plugin

- build.properties
- ivy.xml
> Added MapR401 shim dependency

- src/org/pentaho/di/ui/job/entries/hadoopjobexecutor/JobEntryHadoopJobExecutorController.java
Allow edits to cluster infomation via Named Cluster Edit dialog
Also allow saving job entry without any existing named clusters (using only built-in properties)
http://jira.pentaho.com/browse/PDI-13380
> [PDI-13380] Allow configuring Hadoop Job Executor clusters without names

- src/org/pentaho/di/ui/job/entries/hadoopjobexecutor/JobEntryHadoopJobExecutorController.java
> [PDI-13403] Clicking Browse button on Hadoop Job Executor dialog does

- src/org/pentaho/di/core/hadoop/HadoopSpoonPlugin.java
- src/org/pentaho/di/core/hadoop/SpoonExtensionPoint.java
Revert of HadoopSpoonPlugin.
Moved spoon extension code into new class.
> [BACKLOG-2100] Remove Hadoop Clusters from Kettle

- build.properties
- ivy.xml
Picked changes from master and updated revision in build.properties.
> [SP-1712] - Backport of BAD-140 - Compile HDP 2.2 shim (5.3 Suite)

- build.properties
- ivy.xml
Merge of master into future-develop
> Auto-Merge refreshing development branch

- src/org/pentaho/di/core/namedcluster/NamedClusterManager.java
- src/org/pentaho/di/job/entries/hadoopcopyfiles/JobEntryHadoopCopyFiles.java
- src/org/pentaho/di/trans/steps/hadoopfileinput/HadoopFileInputMeta.java
- src/org/pentaho/di/trans/steps/hadoopfileoutput/HadoopFileOutputMeta.java
- src/org/pentaho/di/ui/job/entries/hadoopcopyfiles/JobEntryHadoopCopyFilesDialog.java
- src/org/pentaho/di/ui/trans/steps/hadoopfileinput/HadoopFileInputDialog.java
- src/org/pentaho/di/ui/trans/steps/hadoopfileoutput/HadoopFileOutputDialog.java
@e-cuellar these are the changes you tested today, please review
> [BACKLOG-3183] PMR job fails if embedded trans contains Hadoop File Input

- src/org/pentaho/di/ui/job/entries/hadoopcopyfiles/JobEntryHadoopCopyFilesDialog.java
> [BACKLOG-1929] As a Hadoop File Input (VFS Browser) user I need to

- src/org/pentaho/di/job/entries/hadoopcopyfiles/JobEntryHadoopCopyFiles.java
- src/org/pentaho/di/trans/steps/hadoopfileinput/HadoopFileInputMeta.java
- src/org/pentaho/di/trans/steps/hadoopfileinput/messages/messages_en_US.properties
- src/org/pentaho/di/ui/job/entries/hadoopcopyfiles/JobEntryHadoopCopyFilesDialog.java
- src/org/pentaho/di/ui/trans/steps/hadoopfileinput/HadoopFileInputDialog.java
> [BACKLOG-1929] Dev - UI updates

- src/org/pentaho/di/ui/vfs/VfsFileChooserHelper.java
- test-src/org/pentaho/di/ui/vfs/VfsFileChooserHelperTest.java
The fix is to create array of length 1, not 0: https://github.com/pentaho/big-data-plugin/blob/master/src/org/pentaho/di/ui/vfs/VfsFileChooserHelper.java#L151
@kcruzada @dkincade
> [BACKLOG-3475] S3 File Output: Unable to browse S3 storage

- src/org/pentaho/di/ui/trans/steps/hadoopfileinput/HadoopFileInputDialog.java
Fix typo - most probably the consequence of inaccurate copy-paste
@kcruzada @dkincade @mdamour1976 could you please review/approve/merge?
> [BACKLOG-3473] - Hadoop File Input: Error appears on trying to set S3 folder

- src/org/pentaho/amazon/s3/S3FileOutputMeta.java
- test-res/s3OutputMetaTest.ktr
- test-src/org/pentaho/amazon/s3/S3FileOutputMetaTest.java
> [PDI-13700] - S3 File Output Fails when writing to large buckets

- src/org/pentaho/di/core/namedcluster/NamedClusterManager.java
- src/org/pentaho/di/trans/steps/hadoopfileinput/HadoopFileInputMeta.java
- src/org/pentaho/di/ui/trans/steps/hadoopfileoutput/HadoopFileOutputDialog.java
> [BAD-290] Error appears if variables is used in both named cluster and

- build.properties
- ivy.xml
> [BAD-245] - Compile MapR 4.1 Shim

- assemblies/legacy-plugin/pom.xml
- pom.xml
Should be merged instead of https://github.com/pentaho/big-data-plugin/pull/412
> [BAD-281] - Build CDH54 shim

- assemblies/legacy-plugin/pom.xml
- legacy/pom.xml
Related to  https://github.com/pentaho/big-data-plugin/pull/423. 
Also need to be merged.
>  [BAD-281] - Build CDH54 shim

- impl/shim/hdfs/src/main/java/com/pentaho/big/data/bundles/impl/shim/hdfs/HadoopFileSystemFactoryLoader.java
- impl/shim/pig/src/main/java/org/pentaho/big/data/impl/shim/pig/PigServiceFactoryLoader.java
- legacy/src/main/java/org/pentaho/di/core/hadoop/HadoopConfigurationBootstrap.java
- legacy/src/main/java/org/pentaho/di/core/hadoop/HadoopConfigurationListener.java
> [BAD-316] MapR410 secure: Unable to connect to HBase

- legacy/src/main/java/org/pentaho/di/core/database/HiveDatabaseMeta.java
- legacy/src/test/java/org/pentaho/di/core/database/HiveDatabaseMetaTest.java
Merge with https://github.com/pentaho/pentaho-hadoop-shims/pull/240 Moving fix to HiveDriver. Remove fix for PDI-11049.
> [BAD-157] Impala: Unable to connect to other than "default" schema using Impala connection template

- assemblies/pmr-libraries/pom.xml
- pom.xml
with those maintained by the build team.
@lucboudreau @lgrill-pentaho
> [CLEANUP] making version properties consistent

- legacy/src/main/java/org/pentaho/di/job/entries/sqoop/SqoopUtils.java
- legacy/src/test/java/org/pentaho/di/job/entries/sqoop/SqoopUtilsTest.java
* Fixed NPE during switch to command-line if there are rows with empty values
* Added parsing of custom argument when there is no space between -D and argument name
* Quote custom option value if it contains "=".
* Check style fixes.
> [BAD-276] - Additional changes

- impl/shim/hdfs/src/main/java/com/pentaho/big/data/bundles/impl/shim/hdfs/HadoopFileSystemFactoryImpl.java
- legacy/src/main/java/org/pentaho/di/core/database/Hive2DatabaseMeta.java
- legacy/src/main/java/org/pentaho/di/core/database/Hive2SimbaDatabaseMeta.java
- legacy/src/main/java/org/pentaho/di/core/database/ImpalaDatabaseMeta.java
- legacy/src/main/java/org/pentaho/di/core/database/ImpalaSimbaDatabaseMeta.java
* Maprfs mistype
* Added Impala and Hive Simba metadada classes
> [BAD-215] Add Support for the Simba Driver

- build.properties
> [CLEANUP]  removing unused property

- api/cluster/src/main/java/org/pentaho/big/data/api/cluster/NamedCluster.java
- impl/cluster/src/main/java/org/pentaho/big/data/impl/cluster/NamedClusterImpl.java
- kettle-plugins/common/namedClusterBridge/src/main/java/org/pentaho/big/data/plugins/common/ui/named/cluster/bridge/NamedClusterBridgeImpl.java
- kettle-plugins/common/namedClusterBridge/src/test/java/org/pentaho/big/data/plugins/common/ui/named/cluster/bridge/NamedClusterBridgeImplTest.java
- kettle-plugins/common/ui/src/main/java/org/pentaho/big/data/plugins/common/ui/ClusterTestDialog.java
- kettle-plugins/common/ui/src/main/java/org/pentaho/big/data/plugins/common/ui/NamedClusterDialogImpl.java
- kettle-plugins/common/ui/src/main/resources/org/pentaho/big/data/plugins/common/ui/messages/messages_en_US.properties
- legacy/src/main/java/org/pentaho/di/core/namedcluster/model/NamedCluster.java
- legacy/src/test/java/org/pentaho/di/core/namedcluster/NamedClusterTest.java
Also added toString() implementations to other NamedCluster classes/tests
> [BACKLOG-4505] Added initial cluster test dialog

- impl/shim/shimTests/src/main/resources/org/pentaho/big/data/impl/shim/tests/messages/messages_en_US.properties
> BACKLOG-4863 - Fix apostrophe quoting

- legacy/src/main/java/org/pentaho/di/core/database/Hive2SimbaDatabaseMeta.java
- legacy/src/main/java/org/pentaho/di/core/database/ImpalaSimbaDatabaseMeta.java
* Hide HiveSimba 
* Cloudera Impala from Impala Simba
> [BAD-332] - Hide HiveSimba rename Cloudera Impala

- legacy/src/main/java/org/pentaho/di/job/entries/sqoop/SqoopUtils.java
- legacy/src/test/java/org/pentaho/di/job/entries/sqoop/SqoopUtilsTest.java
Added backslash escaping during grid -> command line switch.
Unit tests.
Checkstyle fixes.
> Backlog 4928

- impl/vfs/hdfs/src/main/java/org/pentaho/big/data/impl/vfs/hdfs/HDFSFileProvider.java
- impl/vfs/hdfs/src/main/java/org/pentaho/big/data/impl/vfs/hdfs/MapRFileNameParser.java
- impl/vfs/hdfs/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- impl/vfs/hdfs/src/test/java/org/pentaho/big/data/impl/vfs/hdfs/MapRFileNameParserTest.java
* Added MapRFilenameParser - to correctly work with urls like "maprfs:///"
> [BACKLOG-5127] - Regression: VFS Browser fails to connect to MapR FS

- kettle-plugins/common/ui/src/main/java/org/pentaho/big/data/plugins/common/ui/ClusterTestResultsDialog.java
- kettle-plugins/common/ui/src/main/resources/ui/images/error_red.svg
- kettle-plugins/common/ui/src/main/resources/ui/images/success_green.svg
- kettle-plugins/common/ui/src/main/resources/ui/images/warning_yellow.svg
Refactored from GridLayout to FormLayout in order to support label wrap, separators, etc.  Added new icons
> [BACKLOG-4505] Latest UX improvements for Cluster Test Results dialog

- legacy/src/main/java/org/pentaho/di/trans/steps/hbaseinput/HBaseInputDialog.java
- legacy/src/main/java/org/pentaho/di/trans/steps/hbaseoutput/HBaseOutputDialog.java
- legacy/src/main/java/org/pentaho/di/trans/steps/hbaserowdecoder/HBaseRowDecoderDialog.java
- legacy/src/main/java/org/pentaho/hbase/mapping/MappingEditor.java
* Separated situations in which key is need in mapping and not
> [BACKLOG-5321][Regression] Re-editing Hbase Input/Output steps, with mappings stored in the step, leads to problems with mapping

- legacy/src/main/java/org/pentaho/di/job/entries/hadooptransjobexecutor/JobEntryHadoopTransJobExecutor.java
- legacy/src/test/java/org/pentaho/di/job/entries/hadooptransjobexecutor/JobEntryHadoopTransJobExecutorTest.java
* Checked exporting. Previous problem with paths was fixed indirectly.
> [PDI-11537] Export Linked Resources: PMR Mapper and Reducer transformations not exported

- src/org/pentaho/di/ui/job/entries/oozie/OozieJobExecutorJobEntryController.java
(cherry picked from commit c981296)
@mattyb149, @brosander, @mdamour1976, review it please. This is a backport of https://github.com/pentaho/big-data-plugin/pull/405
> [SP-1941] - Backport of PDI-13905 - Browse button not working on Oozie Job Executor (5.4 Suite)

- assemblies/legacy-plugin/pom.xml
- pom.xml
this is complementary PR to the:  https://github.com/pentaho/pentaho-hadoop-shims/pull/291 
@mattyb149 @brosander
> [BAD-381] - pack HDP23 shim into big-data-plugin CE

- assemblies/legacy-plugin/pom.xml
- pom.xml
> [BAD-376] - Update all supporting build configs for EMR 4.1 SHIM

- legacy/src/main/java/org/pentaho/di/core/hadoop/HadoopConfigurationBootstrap.java
- legacy/src/main/java/org/pentaho/di/job/entries/oozie/OozieJobExecutorConfig.java
- legacy/src/main/java/org/pentaho/di/ui/job/entries/hadoopjobexecutor/JobEntryHadoopJobExecutorDialog.java
- legacy/src/main/java/org/pentaho/di/ui/job/entries/hadooptransjobexecutor/JobEntryHadoopTransJobExecutorDialog.java
- legacy/src/main/java/org/pentaho/di/ui/job/entries/sqoop/SqoopExportJobEntryController.java
This is just a fix for several checkstyle violations.
> [CHECKSTYLE]: Fixes for checkstyle voilations in legacy.

- legacy/src/main/java/org/pentaho/di/ui/vfs/VfsFileChooserHelper.java
- legacy/src/test/java/org/pentaho/di/ui/vfs/VfsFileChooserHelperTest.java
Unit tests to increase tests coverage.
> [TEST][big-data-plugin\legacy]: Increased test coverage for VfsFileChooserHelper

- api/hdfs/src/main/java/org/pentaho/bigdata/api/hdfs/HadoopFileSystem.java
- impl/shim/hdfs/src/main/java/com/pentaho/big/data/bundles/impl/shim/hdfs/HadoopFileSystemImpl.java
- impl/shim/hdfs/src/test/java/com/pentaho/big/data/bundles/impl/shim/hdfs/HadoopFileSystemImplTest.java
- impl/vfs/hdfs/src/main/java/org/pentaho/big/data/impl/vfs/hdfs/HDFSFileProvider.java
- impl/vfs/hdfs/src/main/java/org/pentaho/big/data/impl/vfs/hdfs/HDFSFileSystem.java
- impl/vfs/hdfs/src/test/java/org/pentaho/big/data/impl/vfs/hdfs/HDFSFileSystemTest.java
- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileOutputMeta.java
- kettle-plugins/hdfs/src/test/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileOutputMetaTest.java
- kettle-plugins/pig/src/it/java/org/pentaho/big/data/kettle/plugins/pig/JobEntryPigScriptExecutorIT.java
* change the vfs capabilities on the fly
> [BAD-297] - Hadoop file output fails append to file

- assemblies/legacy-plugin/pom.xml
> [ENGOPS-1442] Refactor legacy assembly artifact id

- kettle-plugins/mapreduce/src/main/java/org/pentaho/big/data/kettle/plugins/mapreduce/JobEntryHadoopJobExecutor.java
- kettle-plugins/mapreduce/src/test/java/org/pentaho/big/data/kettle/plugins/mapreduce/JobEntryHadoopJobExecutorTest.java
It needs to load whether connected to the repo or not
> [BACKLOG-4013] - Loading nc config with metastore

- kettle-plugins/common/namedClusterBridge/pom.xml
- kettle-plugins/common/ui/pom.xml
- kettle-plugins/guiTestActionHandlers/pom.xml
- kettle-plugins/hdfs/pom.xml
- kettle-plugins/mapreduce/pom.xml
- kettle-plugins/pig/pom.xml
* Changed dependecy for swt.* packages to optional (in case these bundles are trying to start on cluster without UI)
> [BACKLOG-5864] - REG: PMR: Reducer fails on the client due to job running.

- legacy/src/main/java/org/pentaho/di/job/entries/sqoop/AbstractSqoopJobEntry.java
- legacy/src/main/java/org/pentaho/di/ui/job/entries/sqoop/AbstractSqoopJobEntryController.java
- legacy/src/test/java/org/pentaho/di/job/entries/sqoop/AbstractSqoopJobEntryTest.java
> [BAD-435]: Sqoop steps: database connections deleted after restart Spoon

- impl/shim/sqoop/pom.xml
> [BACKLOG-3894] Fixing version reference for shim-api.

- kettle-plugins/oozie/src/main/java/org/pentaho/big/data/kettle/plugins/oozie/OozieJobExecutorJobEntry.java
- kettle-plugins/oozie/src/test/java/org/pentaho/big/data/kettle/plugins/oozie/OozieJobExecutorJobEntryTest.java
Addresses the case where the named cluster cannot be
loaded from the metastore or config.
http://jira.pentaho.com/browse/BACKLOG-6408
> [BACKLOG-6408]  Regression: NPE Error while launching Oozie on DI-server

- kettle-plugins/oozie/src/main/java/org/pentaho/big/data/kettle/plugins/oozie/OozieJobExecutorJobEntry.java
- kettle-plugins/oozie/src/test/java/org/pentaho/big/data/kettle/plugins/oozie/OozieJobExecutorJobEntryTest.java
Added variable subtitution in getEffectiveOozieUrl
http://jira.pentaho.com/browse/BACKLOG-6472
> [BACKLOG-6472] "Invalid Oozie URL" error message if Oozie URL is set by variable

- impl/shim/mapreduce/src/main/java/org/pentaho/big/data/impl/shim/mapreduce/MapReduceJobBuilderImpl.java
- impl/shim/mapreduce/src/main/java/org/pentaho/big/data/impl/shim/mapreduce/PentahoMapReduceJobBuilderImpl.java
- impl/shim/mapreduce/src/test/java/org/pentaho/big/data/impl/shim/mapreduce/PentahoMapReduceJobBuilderImplTest.java
* Added setting serialized VariableSpace into configuration
> [BACKLOG-6510] - Regression: If Mapper transformation has variable, PMR jobs fails

- impl/shim/mapreduce/src/main/java/org/pentaho/big/data/impl/shim/mapreduce/PentahoMapReduceJobBuilderImpl.java
Reverts pentaho/big-data-plugin#628
> Revert "[PDI-15058] - set java.system.pentaho.working.dir.as.karaf.data.paren…"

- assemblies/legacy-plugin/pom.xml
- pom.xml
Pack hdp24 shim into big-data-plugin CE.
> [BACKLOG-7479]: Create and Compile HDP 2.4 SHIM

- kettle-plugins/mapreduce/src/main/java/org/pentaho/big/data/kettle/plugins/mapreduce/ui/entry/pmr/JobEntryHadoopTransJobExecutorController.java
- kettle-plugins/mapreduce/src/test/java/org/pentaho/big/data/kettle/plugins/mapreduce/ui/entry/pmr/JobEntryHadoopTransJobExecutorControllerTest.java
There are fix and a bit refactoring to avoid code duplication and cover methods editNamedCluster/createNamedCluster with a couple of unit tests.
> [BAD-491]: NullPointerException error appears when user trying to save a new named cluster (or save changes in existed named cluster after edit)

- assemblies/features/src/main/resources/features.xml
Split big-data feature into api/plugin/impl features
@mkambol
> [BACKLOG-7514]Split big-data plugin features

- assemblies/features/src/main/resources/features.xml
EE will have alternate implementation bundles
Depends on https://github.com/pentaho/pentaho-karaf-assembly/pull/195
> [BACKLOG-7514]Check for community-edition before loading impl

- assemblies/legacy-plugin/pom.xml
- pom.xml
Pack cdh57 shim into big-data-plugin CE.
> [BAD-516]: Create and Compile CDH 5.7 SHIM against Pentaho 7.0 (master)

- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/output/HBaseOutputMeta.java
- kettle-plugins/hbase/src/test/java/org/pentaho/big/data/kettle/plugins/hbase/output/HBaseOutputMetaTest.java
Added missing assignment of this.namedCluster in .readRep.
@hudak
> [BACKLOG-8518]  HBaseOutputMeta fails to set namedCluster when trans opened.

- legacy/src/main/java/org/pentaho/amazon/s3/S3FileOutputDialog.java
Updated File Format option to use logic from base TextFileOutputDialog class
> [PDI-12971] - S3 File Output Missing Format Option

- assemblies/pmr-libraries/pom.xml
- assemblies/pmr-libraries/src/main/descriptors/assembly.xml
Reverts pentaho/big-data-plugin#669
> Revert "[BACKLOG-8389] - Upgrade antlr to version 3.4 across Pentaho product suite - changes for pentaho big-data-plugin repository"

- assemblies/legacy-plugin/pom.xml
@pamval, build failed (http://10.177.176.19/job/master-snapshot/job/big-data-plugin/708/) becuse of incorrect xpp3 groupID/artifactID. This is PR with correct values.
> [PPP-3537] - xpp3 groupId and artifactId correcting.

- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/FilterDefinition.java
- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/MappingDefinition.java
- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/input/HBaseInput.java
- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/input/HBaseInputMeta.java
- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/input/OutputFieldDefinition.java
- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/mapping/MappingUtils.java
- kettle-plugins/hbase/src/main/resources/org/pentaho/big/data/kettle/plugins/hbase/input/messages/messages_en_US.properties
- kettle-plugins/hbase/src/test/java/org/pentaho/big/data/kettle/plugins/hbase/input/HBaseInputMetaInjectionTest.java
- kettle-plugins/hbase/src/test/java/org/pentaho/big/data/kettle/plugins/hbase/mapping/MappingUtilsTest.java
@bmorrise , @mdamour1976 please review
> [BACKLOG-7939] - Add Metadata Injection (MDI) support to the HBase Input step

- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/output/HBaseOutput.java
- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/output/HBaseOutputMeta.java
- kettle-plugins/hbase/src/main/resources/org/pentaho/big/data/kettle/plugins/hbase/output/messages/messages_en_US.properties
- kettle-plugins/hbase/src/test/java/org/pentaho/big/data/kettle/plugins/hbase/output/HBaseOutputMetaInjectionTest.java
@bmorrise , @mdamour1976 could you please review the next Hbase MDI case?
> [BACKLOG-7940] - Add Metadata Injection (MDI) support to the HBase Output step

- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/rowdecoder/HBaseRowDecoder.java
- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/rowdecoder/HBaseRowDecoderMeta.java
- kettle-plugins/hbase/src/main/resources/org/pentaho/big/data/kettle/plugins/hbase/rowdecoder/messages/messages_en_US.properties
- kettle-plugins/hbase/src/test/java/org/pentaho/big/data/kettle/plugins/hbase/rowdecoder/HBaseRowDecoderMetaInjectionTest.java
@bmorrise , @mdamour1976 please review the last case for HBase.
> [BACKLOG-7955] - Add Metadata Injection (MDI) support to the HBase Row Decoder

- kettle-plugins/hbase/src/main/resources/org/pentaho/big/data/kettle/plugins/hbase/input/messages/messages_en_US.properties
@bmorrise, @mkambol  please review
> [BACKLOG-7939] - Add Metadata Injection (MDI) support to the HBase Input step - fix UI message

- assemblies/legacy-plugin/pom.xml
- pom.xml
Pack emr46 shim into big-data-plugin CE.
> [BACKLOG-8533]: Create the EMR 4.6 Shim (against Pentaho Master/7.0)

- kettle-plugins/hive/src/main/java/org/pentaho/big/data/kettle/plugins/hive/SparkSimbaDatabaseMeta.java
- kettle-plugins/hive/src/test/java/org/pentaho/big/data/kettle/plugins/hive/SparkSimbaDatabaseMetaTest.java
> [BACKLOG-9125] Determine whether we can override "test connection" logic for SparkSQL

- kettle-plugins/hive/src/main/java/org/pentaho/big/data/kettle/plugins/hive/ImpalaDatabaseDialect.java
- kettle-plugins/hive/src/main/java/org/pentaho/big/data/kettle/plugins/hive/ImpalaDatabaseMeta.java
- kettle-plugins/hive/src/test/java/org/pentaho/big/data/kettle/plugins/hive/ImpalaDatabaseDialectTest.java
- kettle-plugins/hive/src/test/java/org/pentaho/big/data/kettle/plugins/hive/ImpalaDatabaseMetaTest.java
* changes to separate hive and impala urls
> [BACKLOG-9547]-[DEV]-Update the impersonation code to add impersonating impala driver to the map of loaded drivers

- assemblies/legacy-plugin/pom.xml
- pom.xml
Updated poms with the proper shim list:
CDH 5.7
EMR 4.6
HDP 2.4
MapR 4.1.0
> [BACKLOG-9674]: Update Big Data Plugin Contents

- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/input/HBaseInputMeta.java
- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/output/HBaseOutputMeta.java
- kettle-plugins/hbase/src/test/java/org/pentaho/big/data/kettle/plugins/hbase/input/HBaseInputMetaTest.java
- kettle-plugins/hbase/src/test/java/org/pentaho/big/data/kettle/plugins/hbase/output/HBaseOutputMetaTest.java
> [BACKLOG-9629] Removed empty code from HBaseOutputMeta and moved code in HBaseInputMeta under if, so it would be called only when MDI is used

- legacy/src/main/java/org/pentaho/di/core/hadoop/HadoopModule.java
> [BACKLOG-9591]-As a BDS administrator, I want one place to configure big data security to ease configuration tasks.

- assemblies/legacy-plugin/pom.xml
- pom.xml
Added mapr510 to the following pom files:
- assemblies/legacy-plugin/pom.xml;
- pom.xml.
> [BACKLOG-8540] - Create the MapR 5.1 Shim (against Pentaho Master/7.0) - add mapr510

- api/jdbc/src/main/java/org/pentaho/big/data/api/jdbc/impl/ClusterInitializingDriver.java
- api/jdbc/src/test/java/org/pentaho/big/data/api/jdbc/impl/ClusterInitializingDriverTest.java
Logging true failures as ERROR.  Logs for shim not being specified
to DEBUG.
> [BACKLOG-10984] ClusterInitiazation during driver load causes sys init to hang

- assemblies/legacy-plugin/pom.xml
- pom.xml
Added cdh58 to the following pom files:
- assemblies/legacy-plugin/pom.xml;
- pom.xml.
> [BACKLOG-10490] - Create and Dev Validate the cdh58 shim against Pentaho 7.0 (master) - add cdh58

- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileInputMeta.java
> [PDI-14133] Transformation Steps Missing Help Links

- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileInputMeta.java
> [SP-2838][PDI-14133] Transformation Steps Missing Help Links

- kettle-plugins/hive/src/main/java/org/pentaho/big/data/kettle/plugins/hive/Activator.java
- kettle-plugins/hive/src/main/java/org/pentaho/big/data/kettle/plugins/hive/BaseSimbaDatabaseMeta.java
- kettle-plugins/hive/src/main/java/org/pentaho/big/data/kettle/plugins/hive/Hive2SimbaDatabaseDialect.java
- kettle-plugins/hive/src/main/java/org/pentaho/big/data/kettle/plugins/hive/ImpalaSimbaDatabaseDialect.java
- kettle-plugins/hive/src/main/java/org/pentaho/big/data/kettle/plugins/hive/SimbaUrl.java
- kettle-plugins/hive/src/main/java/org/pentaho/big/data/kettle/plugins/hive/SparkSimbaDatabaseDialect.java
- kettle-plugins/hive/src/test/java/org/pentaho/big/data/kettle/plugins/hive/BaseSimbaDatabaseMetaTest.java
- kettle-plugins/hive/src/test/java/org/pentaho/big/data/kettle/plugins/hive/Hive2SimbaDatabaseDialectTest.java
- kettle-plugins/hive/src/test/java/org/pentaho/big/data/kettle/plugins/hive/ImpalaSimbaDatabaseDialectTest.java
- kettle-plugins/hive/src/test/java/org/pentaho/big/data/kettle/plugins/hive/SimbaUrlTest.java
- kettle-plugins/hive/src/test/java/org/pentaho/big/data/kettle/plugins/hive/SparkSimbaDatabaseDialectTest.java
Adding a Dialect implementation for SparkSQL.  Formerly only the
Meta was created.
> [BACKLOG-10454] SparkSQL connections cause NPE in pentaho server

- kettle-plugins/hive/src/main/java/org/pentaho/big/data/kettle/plugins/hive/ImpalaSimbaDatabaseMeta.java
- kettle-plugins/hive/src/test/java/org/pentaho/big/data/kettle/plugins/hive/ImpalaSimbaDatabaseMetaTest.java
> [BACKLOG-11272] Cloudera Impala connections can hang if the wrong security info is used

- kettle-plugins/common/job/src/main/java/org/pentaho/big/data/kettle/plugins/job/JobEntrySerializationHelper.java
@mkambol, @mbatchelor, @dkincade, could please take a look?
> [PPP-3506] - XXE Security Vulnerability in xml parsers

- kettle-plugins/spark/src/main/java/org/pentaho/di/job/entries/spark/JobEntrySparkSubmit.java
- legacy/src/main/resources/org/pentaho/di/ui/hadoop/configuration/messages/messages_en_US.properties
@pentaho/millenniumfalcon @pamval @mdamour1976 please review
> [BACKLOG-11918] Hadoop Distribution and Spark Submit help documentation update

- osgi-jaas/src/main/java/org/pentaho/hadoop/shim/common/osgi/jaas/JaasRealmsRegistrar.java
- osgi-jaas/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- osgi-jaas/src/test/java/org/pentaho/hadoop/shim/common/osgi/jaas/JaasRealmsRegistrarTest.java
> [BACKLOG-11123]-Executing Oozie job brings up password dialog when connecting to secured cluster with no kerberos ticket and authentication disabled

- assemblies/legacy-plugin/pom.xml
- pom.xml
Added cdh59 to the following pom files:
- assemblies/legacy-plugin/pom.xml;
- pom.xml.
> [BAD-554] - Create and Dev Validate the cdh59 shim against Pentaho 7.1 (Master)

- assemblies/legacy-plugin/pom.xml
- legacy/pom.xml
- pom.xml
> [PPP-3571] Use of vulnerable component httpclient-4.2.5.jar - CVE-2014-3577

- assemblies/legacy-plugin/pom.xml
- legacy/pom.xml
- pom.xml
> [SP-3006] Backport of PPP-3571 - Use of vulnerable component httpclient-4.2.5.jar - CVE-2014-3577 (7.0 Suite)

- assemblies/legacy-plugin/pom.xml
- legacy/pom.xml
- pom.xml
> [SP-3007] Backport of PPP-3571 - Use of vulnerable component httpclient-4.2.5.jar - CVE-2014-3577 (6.1 Suite)

- api/cluster/src/main/java/org/pentaho/big/data/api/cluster/NamedCluster.java
- api/hdfs/src/main/java/org/pentaho/bigdata/api/hdfs/HadoopFileSystemFactory.java
- api/hdfs/src/main/java/org/pentaho/bigdata/api/hdfs/HadoopFileSystemLocator.java
- api/hdfs/src/main/java/org/pentaho/bigdata/api/hdfs/impl/HadoopFileSystemLocatorImpl.java
- api/hdfs/src/test/java/org/pentaho/bigdata/api/hdfs/impl/HadoopFileSystemLocatorImplTest.java
- impl/cluster/src/main/java/org/pentaho/big/data/impl/cluster/NamedClusterImpl.java
- impl/shim/hdfs/src/main/java/com/pentaho/big/data/bundles/impl/shim/hdfs/HadoopFileSystemFactoryImpl.java
- impl/shim/hdfs/src/main/java/com/pentaho/big/data/bundles/impl/shim/hdfs/HadoopFileSystemFactoryLoader.java
- impl/shim/hdfs/src/test/java/com/pentaho/big/data/bundles/impl/shim/hdfs/HadoopFileSystemFactoryImplTest.java
- impl/shim/hdfs/src/test/java/com/pentaho/big/data/bundles/impl/shim/hdfs/HadoopFileSystemFactoryLoaderTest.java
- impl/shim/mapreduce/src/main/java/org/pentaho/big/data/impl/shim/mapreduce/MapReduceJobBuilderImpl.java
- impl/vfs/hdfs/src/main/java/org/pentaho/big/data/impl/vfs/hdfs/HDFSFileProvider.java
- impl/vfs/hdfs/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- impl/vfs/hdfs/src/test/java/org/pentaho/big/data/impl/vfs/hdfs/HDFSFileProviderTest.java
- kettle-plugins/common/namedClusterBridge/src/main/java/org/pentaho/big/data/plugins/common/ui/named/cluster/bridge/NamedClusterBridgeImpl.java
- legacy/src/main/java/org/pentaho/di/core/namedcluster/model/NamedCluster.java
Changes to allow us to work with hdi cluster with hdp25 shim
> [BACKLOG-14108]-Document on how to convert HDP shim to work with the Azure/HD Insight cluster

- assemblies/pmr-libraries/pom.xml
- assemblies/pmr-libraries/src/main/descriptors/assembly.xml
subject to merge of https://github.com/pentaho/pentaho-commons-json/pull/8
> [ENGOPS-2639] json GAV change

- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/ServiceStatus.java
- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/input/HBaseInputDialog.java
- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/input/HBaseInputMeta.java
- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/mapping/MappingEditor.java
- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/output/HBaseOutputDialog.java
- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/output/HBaseOutputMeta.java
- kettle-plugins/hbase/src/main/resources/org/pentaho/big/data/kettle/plugins/hbase/input/messages/messages_en_US.properties
- kettle-plugins/hbase/src/main/resources/org/pentaho/big/data/kettle/plugins/hbase/output/messages/messages_en_US.properties
[SP-3316] Backport of BAD-569 - Unable to load for editing ktr with HBase Input/Output steps if KDC host is unavailable (7.0 Suite)
> [SP-3316] Backport of BAD-569 - Unable to load for editing ktr with HBase

- kettle-plugins/mapreduce/src/main/resources/org/pentaho/big/data/kettle/plugins/mapreduce/ui/entry/JobEntryHadoopTransJobExecutorDialog.xul
This fix validated by Dean fixes the Windows only problem with scrollbars appear on the user settings tab.  @mdamour1976 @bmorrise
> [BACKLOG-12439] - Fixed auto-scrollbar in user setting tab.

- impl/shim/oozie/src/main/java/org/pentaho/big/data/impl/shim/oozie/FallbackOozieClientImpl.java
- impl/shim/oozie/src/main/java/org/pentaho/big/data/impl/shim/oozie/OozieJobInfoImpl.java
- impl/shim/oozie/src/main/java/org/pentaho/big/data/impl/shim/oozie/OozieServiceImpl.java
- legacy/src/main/java/org/pentaho/di/job/entries/oozie/OozieClientImpl.java
- legacy/src/main/java/org/pentaho/di/job/entries/oozie/OozieJobInfoImpl.java
> [PDI-13106] Oozie exceptions are hidden. Need to provide more info

- assemblies/pmr-libraries/pom.xml
- assemblies/pmr-libraries/src/main/descriptors/assembly.xml
TO BE MERGED BY BUILDTEAM ONLY!   Pending upstream mavenization of reporting.
> [BACKLOG-12334] GAV changes for reporting

- assemblies/pmr-libraries/pom.xml
Reverts pentaho/big-data-plugin#826
> Revert "[PDI-15059]-Updated slf4j jars to 1.7.22 version in pmr libraries"

- api/cluster/src/main/java/org/pentaho/big/data/api/cluster/NamedCluster.java
- api/cluster/src/main/java/org/pentaho/big/data/api/cluster/NamedClusterService.java
- assemblies/features/src/main/resources/features.xml
- impl/cluster/pom.xml
- impl/cluster/src/main/java/org/pentaho/big/data/impl/cluster/NamedClusterImpl.java
- impl/cluster/src/main/java/org/pentaho/big/data/impl/cluster/NamedClusterManager.java
- impl/cluster/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- impl/cluster/src/test/java/org/pentaho/big/data/impl/cluster/NamedClusterImplTest.java
- impl/cluster/src/test/java/org/pentaho/big/data/impl/cluster/NamedClusterManagerTest.java
- kettle-plugins/common/namedClusterBridge/src/main/java/org/pentaho/big/data/plugins/common/ui/named/cluster/bridge/NamedClusterBridgeImpl.java
- kettle-plugins/common/ui/src/main/java/org/pentaho/big/data/plugins/common/ui/NamedClusterComposite.java
- kettle-plugins/common/ui/src/main/java/org/pentaho/big/data/plugins/common/ui/NamedClusterDialogImpl.java
- kettle-plugins/common/ui/src/main/resources/org/pentaho/big/data/plugins/common/ui/messages/messages_en_US.properties
- legacy/src/main/java/org/pentaho/di/core/hadoop/HadoopConfigurationBootstrap.java
- legacy/src/main/java/org/pentaho/di/core/namedcluster/NamedClusterManager.java
- legacy/src/main/java/org/pentaho/di/core/namedcluster/model/NamedCluster.java
- legacy/src/main/resources/org/pentaho/di/ui/core/namedcluster/dialog/messages/messages_en_US.properties
- legacy/src/test/java/org/pentaho/di/core/namedcluster/NamedClusterManagerTest.java
Reverts pentaho/big-data-plugin#847
> Revert "[BACKLOG-14915]-Dynamically populate storage list box on the cluster …"

- kettle-plugins/common/ui/src/main/java/org/pentaho/big/data/plugins/common/ui/NamedClusterComposite.java
"hdfs" (lower case) by default
> [BACKLOG-15585] PDI:Hadoop cluster settings: "Storage" dropdown have

- kettle-plugins/mapreduce/src/main/resources/org/pentaho/big/data/kettle/plugins/mapreduce/ui/entry/JobEntryHadoopTransJobExecutorDialog.xul
> [BACKLOG-12439] Adjusted layout for map reduce dialog

- kettle-plugins/common/ui/src/main/resources/org/pentaho/big/data/plugins/common/ui/messages/messages_en_US.properties
- legacy/src/main/resources/org/pentaho/di/ui/hadoop/configuration/messages/messages_en_US.properties
> [BACKLOG-14619] Updated help links for 7.1

- assemblies/pmr-libraries/pom.xml
Reverts pentaho/big-data-plugin#864
> Revert "[BACKLOG-15879] Upgrading POI to 3.15 due to vulnerabilities"

- assemblies/legacy-plugin/pom.xml
- pom.xml
make big-data-plugin include only latest emr531 shim
> [BACKLOG-15005]-emr531 for 8.0, remove emr52 from big-data-plugin in master branch

- api/cluster/src/main/java/org/pentaho/big/data/api/cluster/NamedCluster.java
- impl/cluster/src/main/java/org/pentaho/big/data/impl/cluster/NamedClusterImpl.java
- kettle-plugins/common/namedClusterBridge/src/main/java/org/pentaho/big/data/plugins/common/ui/named/cluster/bridge/NamedClusterBridgeImpl.java
- kettle-plugins/common/ui/src/main/java/org/pentaho/big/data/plugins/common/ui/NamedClusterComposite.java
- kettle-plugins/common/ui/src/main/java/org/pentaho/big/data/plugins/common/ui/NamedClusterDialogImpl.java
- kettle-plugins/common/ui/src/main/resources/org/pentaho/big/data/plugins/common/ui/messages/messages_en_US.properties
- legacy/src/main/java/org/pentaho/di/core/namedcluster/model/NamedCluster.java
> [BACKLOG-16187]-[DEV] - Update the named cluster to include knox

- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/job/JobEntryHadoopCopyFiles.java
- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/job/JobEntryHadoopCopyFilesDialog.java
> [PDI-14734]-Dialog's table discards input after losing focus

- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/job/JobEntryHadoopCopyFiles.java
- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/job/JobEntryHadoopCopyFilesDialog.java
> [SP-3600][PDI-14734]-Dialog's table discards input after losing focus

- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/job/JobEntryHadoopCopyFiles.java
- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/job/JobEntryHadoopCopyFilesDialog.java
> [SP-3601][PDI-14734]-Dialog's table discards input after losing focus

- assemblies/legacy-plugin/pom.xml
- assemblies/legacy-plugin/src/main/assembly/descriptors/plugin.xml
- assemblies/standalone/pom.xml
- impl/shim/sqoop/pom.xml
- kettle-plugins/common/job/pom.xml
- kettle-plugins/hbase/pom.xml
- kettle-plugins/hdfs/pom.xml
- kettle-plugins/mapreduce/pom.xml
- kettle-plugins/oozie/pom.xml
- kettle-plugins/pig/pom.xml
- kettle-plugins/spark/pom.xml
- kettle-plugins/sqoop/pom.xml
- legacy/pom.xml
DO NOT MERGE prior to merge of kettle mavenization!
> [BACKLOG-12995] changes for upstream kettle mavenization

- api/runtimeTest/pom.xml
- api/runtimeTest/src/main/java/org/pentaho/runtime/test/network/impl/GatewayConnectivityTestImpl.java
- api/runtimeTest/src/test/java/org/pentaho/runtime/test/network/impl/GatewayConnectivityTestImplTest.java
- assemblies/pmr-libraries/pom.xml
- assemblies/pmr-libraries/src/main/descriptors/assembly.xml
- assemblies/pmr-libraries/src/main/resources/classes/org/apache/commons/vfs2/impl/providers.xml
- legacy/pom.xml
- legacy/src/main/java/org/pentaho/di/trans/steps/couchdbinput/CouchDbInput.java
- legacy/src/test/java/org/pentaho/di/trans/steps/couchdbinput/CouchDbInputMetaTest.java
- legacy/src/test/java/org/pentaho/di/trans/steps/couchdbinput/CouchDbInputTest.java
- pom.xml
Reverts pentaho/big-data-plugin#917
> Revert "[PPP-3735] - Use of vulnerable component httpclient-3.0.1.jar, common…"

- impl/shim/mapreduce/src/main/java/org/pentaho/big/data/impl/shim/mapreduce/PentahoMapReduceJobBuilderImpl.java
- impl/shim/mapreduce/src/test/java/org/pentaho/big/data/impl/shim/mapreduce/PentahoMapReduceJobBuilderImplTest.java
- Property extracting was changed
- Tests were improved
> [PDI-16335] Pentaho Plugins not pushed to HDFS even if they are listed in pmr.kettle.additional.plugins

- assemblies/features/src/main/resources/features.xml
- kettle-plugins/formats/pom.xml
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/parquet/input/ParquetInputMeta.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/parquet/output/ParquetOutputMeta.java
- kettle-plugins/formats/src/main/resources/OSGI-INF/blueprint/blueprint.xml
@bmorrise please review.
This commit brings formats plugin to pdi-client as a bundle.
> [BACKLOG-16741] - Convert formats plugin to bundle

- impl/shim/mapreduce/src/main/java/org/pentaho/big/data/impl/shim/mapreduce/MapReduceJobBuilderImpl.java
- impl/shim/mapreduce/src/main/java/org/pentaho/big/data/impl/shim/mapreduce/MapReduceServiceFactoryImpl.java
- impl/shim/mapreduce/src/main/java/org/pentaho/big/data/impl/shim/mapreduce/MapReduceServiceFactoryLoader.java
- impl/shim/mapreduce/src/main/java/org/pentaho/big/data/impl/shim/mapreduce/MapReduceServiceImpl.java
- impl/shim/mapreduce/src/main/java/org/pentaho/big/data/impl/shim/mapreduce/PentahoMapReduceJobBuilderImpl.java
- impl/shim/mapreduce/src/main/resources/org/pentaho/big/data/impl/shim/mapreduce/messages/messages_en_US.properties
- impl/shim/mapreduce/src/test/java/org/pentaho/big/data/impl/shim/mapreduce/MapReduceServiceImplTest.java
- impl/shim/mapreduce/src/test/java/org/pentaho/big/data/impl/shim/mapreduce/PentahoMapReduceJobBuilderImplTest.java
- legacy/src/main/java/org/pentaho/di/job/entries/hadoopjobexecutor/JarUtility.java
Reverts pentaho/big-data-plugin#929
> Revert "Backlog 17803"

- api/cluster/src/main/java/org/pentaho/big/data/api/cluster/NamedCluster.java
- impl/cluster/src/main/java/org/pentaho/big/data/impl/cluster/NamedClusterImpl.java
- impl/cluster/src/test/java/org/pentaho/big/data/impl/cluster/NamedClusterImplTest.java
- kettle-plugins/common/namedClusterBridge/src/main/java/org/pentaho/big/data/plugins/common/ui/named/cluster/bridge/NamedClusterBridgeImpl.java
- kettle-plugins/common/namedClusterBridge/src/test/java/org/pentaho/big/data/plugins/common/ui/named/cluster/bridge/NamedClusterBridgeImplTest.java
- kettle-plugins/common/ui/src/main/java/org/pentaho/big/data/plugins/common/ui/NamedClusterComposite.java
- kettle-plugins/common/ui/src/main/java/org/pentaho/big/data/plugins/common/ui/NamedClusterDialogImpl.java
- kettle-plugins/common/ui/src/main/resources/org/pentaho/big/data/plugins/common/ui/messages/messages_en_US.properties
- legacy/src/main/java/org/pentaho/di/core/namedcluster/model/NamedCluster.java
- legacy/src/main/resources/org/pentaho/di/ui/core/namedcluster/dialog/messages/messages_en_US.properties
> [BACKLOG-17647] Dev - Add Kafka Bootstrap servers to name cluster dialog

- kettle-plugins/sqoop/src/main/java/org/pentaho/big/data/kettle/plugins/sqoop/AbstractSqoopJobEntry.java
- kettle-plugins/sqoop/src/main/java/org/pentaho/big/data/kettle/plugins/sqoop/SqoopUtils.java
- added environment substitution and password decryption in database configuring
> [PDI-16186] Passwords not get Decrypted in Sqoop Import and Export Steps

- kettle-plugins/common/ui/src/main/java/org/pentaho/big/data/plugins/common/ui/NamedClusterDialogImpl.java
> [BACKLOG-16947] I want my consumer Kafka connections to be authenticated with Kerberos

- impl/shim/mapreduce/src/main/java/org/pentaho/big/data/impl/shim/mapreduce/PentahoMapReduceJobBuilderImpl.java
- impl/shim/mapreduce/src/test/java/org/pentaho/big/data/impl/shim/mapreduce/PentahoMapReduceJobBuilderImplTest.java
> [SP-3713] Backport of PDI-16335 - Pentaho Plugins not pushed to HDFS even if they are listed in pmr.kettle.additional.plugins (6.1 Suite)

- impl/shim/mapreduce/src/main/java/org/pentaho/big/data/impl/shim/mapreduce/PentahoMapReduceJobBuilderImpl.java
- impl/shim/mapreduce/src/test/java/org/pentaho/big/data/impl/shim/mapreduce/PentahoMapReduceJobBuilderImplTest.java
> [SP-3712] Backport of PDI-16335 - Pentaho Plugins not pushed to HDFS even if they are listed in pmr.kettle.additional.plugins (7.1 Suite)

- kettle-plugins/sqoop/src/main/java/org/pentaho/big/data/kettle/plugins/sqoop/AbstractSqoopJobEntry.java
- kettle-plugins/sqoop/src/main/java/org/pentaho/big/data/kettle/plugins/sqoop/SqoopUtils.java
> [SP-3744] Backport of PDI-16186 - Passwords not get Decrypted in Sqoop Import and Export Steps (7.1 Suite)

- kettle-plugins/sqoop/src/main/java/org/pentaho/big/data/kettle/plugins/sqoop/AbstractSqoopJobEntry.java
- kettle-plugins/sqoop/src/main/java/org/pentaho/big/data/kettle/plugins/sqoop/SqoopUtils.java
> [SP-3745] Backport of PDI-16186 - Passwords not get Decrypted in Sqoop Import and Export Steps (6.1 Suite)

- assemblies/legacy-plugin/pom.xml
- pom.xml
@alexzhk please view and merge
> [BAD-987]-BigData Plugin update, emr58 added.

- .gitignore
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/output/AvroOutputDialog.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/output/AvroOutputMeta.java
- kettle-plugins/formats/src/main/resources/AO.svg
- kettle-plugins/formats/src/main/resources/org/pentaho/big/data/kettle/plugins/formats/avro/output/messages/messages_en_US.properties
@rmansoor , @bmorrise , @ddiroma .  Hello gents.  Please take a look at PR for AvroOutputDialog.
> BACKLOG-18551 - Implemented code for the avro output dialog according to the ux specification.

- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/output/AvroOutput.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/output/AvroOutputDialog.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/output/AvroOutputMeta.java
Reverts pentaho/big-data-plugin#1004
> Revert "[BACKLOG-18602]-Implement write Avro format functionality in PDI step…"

- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInputDialog.java
- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInputMeta.java
- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaFactory.java
- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaProducerOutputDialog.java
- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaProducerOutputMeta.java
- kettle-plugins/kafka/src/main/resources/org/pentaho/big/data/kettle/plugins/kafka/messages/messages_en_US.properties
- kettle-plugins/kafka/src/test/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInputMetaTest.java
- kettle-plugins/kafka/src/test/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaFactoryTest.java
- kettle-plugins/kafka/src/test/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaProducerOutputMetaTest.java
MDI for consumer and producer configs
> [BACKLOG-18206] I want to pass advanced config properties to Kafka Producer

- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/output/AvroOutputDialog.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/output/AvroOutputMeta.java
- kettle-plugins/formats/src/main/resources/org/pentaho/big/data/kettle/plugins/formats/avro/messages/messages_en_US.properties
-Separate field for Schema file name
-Make the table editable
-Persist all date to xml, repository and meta
> [BACKLOG-18320] - Update the UI according to UX specification.

- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/BaseAvroStepDialog.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/output/AvroOutputDialog.java
- Clear the Filename text box once use changes location
- Map name from the previous field to the avro path and name of the avro output field table
> [BACKLOG-18320] - Update avro output dialog with UX requirement

- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/output/AvroOutputDialog.java
@rmansoor @tkafalas @ddiroma please take a look at PR.
> BACKLOG-18764 - made following changes to fields table:  made 'null'a drop down.  default 'null' value to 'yes' if user did not specify'

- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/parquet/output/ParquetOutputMetaBase.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/output/ParquetOutputMeta.java
Added methods for getting Parquet File Options
Going to create unit-tests for both Parquet steps.
See this pull request along with https://github.com/AlexanderBuloichik/pentaho-ee/pull/2
> [BACKLOG-17239]-Parquet Output Step - Write file using Spark engine

- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/output/AvroOutputMetaBase.java
- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/parquet/output/ParquetOutputMetaBase.java
@rmansoor @tkafalas please take a look
> BACKLOG-18904 - fixed issue with fields not being read from repo correctly.  Fixed for both Avro and Parquet output

- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/output/AvroOutput.java
-Avro content generator now uses the default value when generating content for a column which does not have any data.
-Converts other data types to avro data type.
-Enable renaming of a column in avro schema..
-Enable removing of columns from the avro schema
> [BACKLOG-18641] - Updated Avro output generator to resolve issues

- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/output/AvroOutput.java
output step and data from the previous step
> [BACKLOG-18907]-[DEV] - Implement code to use meta data from the avro

- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInputDialog.java
- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaDialogHelper.java
- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaProducerOutputDialog.java
NOTE: Merge only after Andrew and Kirby approval
> [BACKLOG-18206][BACKLOG-16946] Add security.protocol options with default value of PLAINTEXT

- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInput.java
- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInputData.java
- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInputDialog.java
- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInputMeta.java
- kettle-plugins/kafka/src/main/resources/org/pentaho/big/data/kettle/plugins/kafka/messages/messages_en_US.properties
- kettle-plugins/kafka/src/test/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInputMetaTest.java
- kettle-plugins/kafka/src/test/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInputTest.java
This reverts commit e50070fda344284cc12ca72c46947f419846af07.
> [BACKLOG-18066] REVERT Kafka Plugin - Add running duration timeout

- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/BaseParquetStepDialog.java
> [BACKLOG-17671] - Parquet Input/Output Step - Create UI dialogs to UX specification - fix browse files dialog

- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/parquet/input/ParquetInputMetaBase.java
- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/parquet/output/ParquetOutputMetaBase.java
!Review and merge this PR first: https://github.com/pentaho/pentaho-kettle/pull/4411
@bmorrise please review.
> [BACKLOG-17900] - Implement read/write Parquet format functionality in PDI steps via Shim API - resolve Hadoop cluster file paths for AEL

- legacy/src/main/resources/org/pentaho/di/trans/steps/avroinput/messages/messages_en_US.properties
> [BACKLOG-18321] Fixed capitalization in Avro Input dialog

- legacy/src/main/java/org/pentaho/di/trans/steps/avroinput/AvroInputDialog.java
> [BACKLOG-18321] Center preview button

- impl/shim/common/src/main/java/com/pentaho/big/data/bundles/impl/shim/common/ShimBridgingClassloader.java
- impl/shim/common/src/test/java/com/pentaho/big/data/bundles/impl/shim/common/ShimBridgingClassloaderTest.java
> [BACKLOG-19039] - Yarn step for secure cluster stop working after license verifier check

- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInputMeta.java
- kettle-plugins/kafka/src/test/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInputMetaTest.java
> [BACKLOG-18982] Kafka: add Namedclusters to embedded metastore when

- legacy/src/main/java/org/pentaho/di/trans/steps/avroinput/AvroInputDialog.java
> [BACKLOG-18321] Fix for avro input file name tooltip

- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/parquet/output/ParquetOutputMetaBase.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/output/ParquetOutput.java
Reverts pentaho/big-data-plugin#1071
> Revert "[BACKLOG-18970] Add Date/Time to filename"

- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/output/AvroOutputMetaBase.java
> [BACKLOG-18976]-[DEV] - Enable Avro ouput step to use hadoop cluster url

- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/parquet/output/ParquetOutputMetaBase.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/output/ParquetOutputDialog.java
- kettle-plugins/formats/src/main/resources/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/output/messages/messages_en_US.properties
@bmorrise  @bmorrise  please review UI changes for BACKLOG-18970
> [BACKLOG-18970] - Parquet Output - Add new options - Date/Time Stamp & File extension - UI changes

- legacy/src/main/java/org/pentaho/di/trans/steps/avroinput/AvroInputDialog.java
> [BACKLOG-18321] Removed unnecessary tooltips from avro input

- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/BaseParquetStepDialog.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/output/ParquetOutputDialog.java
- kettle-plugins/formats/src/main/resources/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/messages/messages_en_US.properties
- kettle-plugins/formats/src/main/resources/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/output/messages/messages_en_US.properties
@bmorrise please review this new fix created according PJ's comments
> [BACKLOG-18970] - Parquet Output - Add new options - Date/Time Stamp & File extension - fix for UI changes

- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/NullableValuesEnum.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/output/AvroOutputDialog.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/output/ParquetOutputDialog.java
!Review and merge this PR https://github.com/pentaho/pentaho-kettle/pull/4468 first!
@bmorrise please review
> [BACKLOG-18970] - Parquet Output - Add new options - Date/Time Stamp & File extension - fix option tab controls

- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/output/AvroOutputMetaBase.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/output/AvroOutputMeta.java
- kettle-plugins/formats/src/main/resources/org/pentaho/big/data/kettle/plugins/formats/impl/avro/messages/messages_en_US.properties
- kettle-plugins/formats/src/main/resources/org/pentaho/big/data/kettle/plugins/formats/impl/avro/output/messages/messages_en_US.properties
> BACKLOG-19246 - added support for metadata injection for avro output

- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/FormatInputFile.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/input/ParquetInputMeta.java
- kettle-plugins/formats/src/main/resources/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/input/messages/messages_en_US.properties
- kettle-plugins/formats/src/test/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/input/ParquetInputMetaInjectionTest.java
> [BACKLOG-19013] - Parquet Input - Support Metadata Injection

- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/BaseParquetStepDialog.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/input/ParquetInputDialog.java
@bmorrise please review.
I substituted type check to class name check to avoid importing additional packages for the format bundle.
> [BACKLOG-19181] - Parquet Input - Canceling the Hadoop Distirbution dialog pop-up an error to user and console

- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/output/ParquetOutputDialog.java
> [BACKLOG-18984] - Parquet Output - Overwrite Existing File Flag - actualize meta.changed flag

- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/input/AvroInputMetaBase.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/input/AvroInputMeta.java
- kettle-plugins/formats/src/main/resources/org/pentaho/big/data/kettle/plugins/formats/impl/avro/input/messages/messages_en_US.properties
> BACKLOG-19349 - added metadata injections support for AvroInput

- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/parquet/input/ParquetInputMetaBase.java
- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/parquet/output/ParquetOutputMetaBase.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/input/ParquetInput.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/output/ParquetOutput.java
> [BACKLOG-17671] - Parquet Input/Output Step - Create UI dialogs to UX specification - fix for variables resolving

- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/output/ParquetOutputDialog.java
> [BACKLOG-19453] - Disable date and time checkboxes if specify date time format is selected

- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/input/AvroInputMetaBase.java
- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/output/AvroOutputMetaBase.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/input/AvroInput.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/output/AvroOutput.java
> [BACKLOG-19438]-Avro Input/Output file path cannot use kettle internal

- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/parquet/output/ParquetOutputMetaBase.java
> [BACKLOG-19460] - Parquet Output for 'Specify date time format' does not allow parameters/variables

- kettle-plugins/formats/src/main/resources/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/input/messages/messages_en_US.properties
- kettle-plugins/formats/src/main/resources/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/output/messages/messages_en_US.properties
> [BACKLOG-17671] - Parquet Input/Output Step - Create UI dialogs to UX specification - fix tooltips

- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/input/ParquetInputDialog.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/output/ParquetOutputDialog.java
> [BACKLOG-19491] - Parquet Input/output is sorting empty lines and theirs values

- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/output/ParquetOutputDialog.java
- kettle-plugins/formats/src/main/resources/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/output/messages/messages_en_US.properties
! Please process this PR https://github.com/pentaho/pentaho-kettle/pull/4531 first!
@bmorrise please review
> [BACKLOG-19241] - Parquet output get fields dialog fixes

- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/input/AvroInputDialog.java
> [BACKLOG-19532]-Avro Input - Correct issues with Fields Datagrid - fix

- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/output/ParquetOutputDialog.java
- kettle-plugins/formats/src/main/resources/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/output/messages/messages_en_US.properties
@dkincade , @kcruzada please review.
! Please process this PR https://github.com/pentaho/pentaho-kettle/pull/4539 first!
Master PR: https://github.com/pentaho/big-data-plugin/pull/1135
> [BACKLOG-19241] - Parquet output get fields dialog fixes (#1135)

- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/output/ParquetOutputDialog.java
> [BACKLOG-19242] - Parquet output options width on Ubuntu - change options widths for linux

- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInputDialog.java
- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInputMeta.java
- kettle-plugins/kafka/src/main/resources/org/pentaho/big/data/kettle/plugins/kafka/messages/messages_en_US.properties
- kettle-plugins/kafka/src/test/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInputMetaTest.java
> [BACKLOG-19553] As a Kafka User I want to open the referenced subtrans from the Kafka Consumer Step

- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/orc/output/OrcOutputMetaBase.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/BaseAvroStepDialog.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/orc/BaseOrcStepDialog.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/orc/output/OrcOutputDialog.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/BaseParquetStepDialog.java
- kettle-plugins/formats/src/main/resources/org/pentaho/big/data/kettle/plugins/formats/impl/orc/output/messages/messages_en_US.properties
> [BACKLOG-20029] ORC Output Step - Create UI dialog to UX specification

- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/orc/BaseOrcStepDialog.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/orc/input/OrcInputDialog.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/orc/output/OrcOutputDialog.java
The previous UX update changed the Orc Base Dialog logic and while it brought the UX up to par with the mockup for Orc Input Step it broke the layout of the Orc Output Step. Both Input and Output Dialogs have now been updated to match the UX mockups.
> [BACKLOG-20027] ORC Input Step - Create UI dialog to UX specification

- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/orc/output/OrcOutputMetaBase.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/orc/output/OrcOutput.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/orc/output/OrcOutputDialog.java
- kettle-plugins/formats/src/main/resources/org/pentaho/big/data/kettle/plugins/formats/impl/orc/output/messages/messages_en_US.properties
> [BACKLOG-20291] Add overwrite existing flag in Orc Output Step

- assemblies/pmr-libraries/pom.xml
- impl/cluster/pom.xml
- impl/clusterTests/pom.xml
- impl/shim/initializer/pom.xml
- impl/shim/jaas/pom.xml
- impl/shim/shimTests/pom.xml
- impl/vfs/hdfs/pom.xml
- kettle-plugins/common/job/pom.xml
- kettle-plugins/common/namedClusterBridge/pom.xml
- kettle-plugins/common/ui/pom.xml
- kettle-plugins/guiTestActionHandlers/pom.xml
- kettle-plugins/hbase/pom.xml
- kettle-plugins/hdfs/pom.xml
- kettle-plugins/hive/pom.xml
- kettle-plugins/kafka/pom.xml
- kettle-plugins/mapreduce/pom.xml
- kettle-plugins/oozie/pom.xml
- kettle-plugins/pig/pom.xml
- kettle-plugins/sqoop/pom.xml
- legacy/pom.xml
- pom.xml
@lgrill-pentaho @emartin-pentaho @VasilinaTerehova
> [ENGOPS-3719] fix shims version

- kettle-plugins/formats/pom.xml
- kettle-plugins/hbase/pom.xml
- kettle-plugins/oozie/pom.xml
- kettle-plugins/pig/pom.xml
@lgrill-pentaho @emartin-pentaho @VasilinaTerehova
> [ENGOPS-3719] fix pig and oozie shim versions

- assemblies/features/src/main/resources/features.xml
- pom.xml
@VasilinaTerehova @lgrill-pentaho
> [ENGOPS-3719] clean up feature versions

- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/orc/input/OrcInputDialog.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/orc/input/OrcInputMeta.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/orc/output/OrcOutputMeta.java
- kettle-plugins/formats/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Moved orc to new karaf structure
See this pull request along with https://github.com/pentaho/pentaho-hadoop-shims/pull/670
> [BACKLOG-20178]-Move parquet/avro/orc to karaf

- kettle-plugins/mapreduce/src/main/java/org/pentaho/big/data/kettle/plugins/mapreduce/entry/pmr/JobEntryHadoopTransJobExecutor.java
Reverts pentaho/big-data-plugin#1035
> Revert "[PDI-16436]-Issues with 3 steps when exporting - importing in an EE repository"

- assemblies/features/src/main/resources/features.xml
> Separate shims features, remove shim features from spark karaf start

- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/orc/input/OrcInput.java
> [BACKLOG-20028] ORC Input Step - Implement a working input step using format shim

- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/orc/output/OrcOutput.java
> [BACKLOG-20239] Update the UI and shims to write orc output file

- assemblies/legacy-plugin/pom.xml
- pom.xml
@VasilinaTerehova could you please take a view and merge?
> [BAD-1241]-Create and Dev Validate EMR 5.9 Shim against Pentaho 8.1 (Master)

- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInputDialog.java
Goes with https://github.com/pentaho/pentaho-kettle/pull/4722
> [BACKLOG-20601] - Kafka: Create New Sub-transformation Flow

- kettle-plugins/kafka/src/test/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInputTest.java
- kettle-plugins/mqtt/pom.xml
Also switched the parent artifact of mqtt to be kettle-plugins.
> [CLEANUP] Correcting issue with too many threads being created

- impl/shim/hdfs/src/main/java/com/pentaho/big/data/bundles/impl/shim/hdfs/HadoopFileSystemFactoryImpl.java
> [BAD-1280]-Create and Dev Validate Mapr 6.0 Shim against Pentaho 8.1 (Master), hdfs fix

- assemblies/legacy-plugin/pom.xml
- assemblies/legacy-plugin/src/main/assembly/descriptors/plugin.xml
- pom.xml
@lgrill-pentaho @emartin-pentaho @arunimagupta
> [BAD-1279] add OSS license file back into plugin assembly

- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/orc/input/OrcInputMetaBase.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/orc/input/OrcInput.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/orc/input/OrcInputDialog.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/orc/input/OrcInputMeta.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/input/ParquetInputDialog.java
- kettle-plugins/formats/src/main/resources/org/pentaho/big/data/kettle/plugins/formats/impl/orc/input/messages/messages_en_US.properties
> [BACKLOG-20033] ORC Input Metadata injection support

- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/orc/input/OrcInputMetaBase.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/orc/input/OrcInput.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/orc/input/OrcInputDialog.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/orc/input/OrcInputMeta.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/input/ParquetInputDialog.java
- kettle-plugins/formats/src/main/resources/org/pentaho/big/data/kettle/plugins/formats/impl/orc/input/messages/messages_en_US.properties
This killed the downstream pdi-daemon.
> Revert "[BACKLOG-20033] ORC Input Metadata injection support"

- assemblies/legacy-plugin/pom.xml
- impl/shim/hbase/src/main/java/com/pentaho/big/data/bundles/impl/shim/hbase/HBaseServiceImpl.java
- impl/shim/hbase/src/test/java/com/pentaho/big/data/bundles/impl/shim/hbase/HBaseServiceImplTest.java
- pom.xml
> [BAD-1281]-Develop and DEV Validate the Mapr 6.0 Shim against Pentaho 8.1 (Master)

- legacy/pom.xml
- pom.xml
Associated with:
https://github.com/pentaho/pentaho-s3-vfs/pull/30
https://github.com/pentaho/pentaho-kettle/pull/4796
> [BACKLOG-20908] Upgrade jets3t to version 0.9.4

- assemblies/pmr-libraries/pom.xml
- pom.xml
@pentaho/2-1b
Depends on pentaho/pentaho-commons-xul#143
> [BACKLOG-20423] Update downstreams

- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInputMeta.java
- kettle-plugins/kafka/src/test/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInputMetaTest.java
- kettle-plugins/mqtt/pom.xml
Extracting the subtrans KTR to be apart of the BaseStreamMetaData and
moving mqtt jars to be apart of data-integration/lib so they can be used
by AEL/Spark
> [BACKLOG-20859] Run MQTT Step in AEL/Spark

- kettle-plugins/formats-meta/pom.xml
- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/input/AvroInputField.java
- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/input/AvroInputMetaBase.java
- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/output/AvroOutputField.java
- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/output/AvroOutputMetaBase.java
- kettle-plugins/formats-meta/src/test/java/org/pentaho/big/data/kettle/plugins/formats/avro/input/AvroInputMetaBaseTest.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/input/AvroInput.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/input/AvroInputDialog.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/input/AvroInputMeta.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/output/AvroOutput.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/output/AvroOutputDialog.java
- kettle-plugins/formats/src/main/resources/org/pentaho/big/data/kettle/plugins/formats/impl/avro/output/messages/messages_en_US.properties
- kettle-plugins/formats/src/test/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/input/AvroInputMetaTest.java
[BACKLOG-20715] Fixing Avro output execution
[BACKLOG-20721] [BACKLOG-20715] Read & write generic Avro files (non …
[BACKLOG-20887] - fix for get field after avro input
[BACKLOG-20890] Implement code to read avro data file generated using…
BACKLOG-20716 Avro AEL Output using avro field specification
> Feature: Non-AEL Avro Input and Output, AEL Avro Output

- assemblies/pmr-libraries/pom.xml
- assemblies/pmr-libraries/src/main/descriptors/assembly.xml
@pentaho/2-1b gav change
for pentaho/pentaho-metadata/pull/186
> [BACKLOG-13306] GAV change

- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/output/AvroOutputField.java
- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/output/AvroOutputMetaBase.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/output/AvroOutputDialog.java
- kettle-plugins/formats/src/main/resources/org/pentaho/big/data/kettle/plugins/formats/impl/avro/output/messages/messages_en_US.properties
[BACKLOG-21076] Update the AvroOutput Dialog to support BigDecimal precision and scale.
[BACKLOG-21077] Update the shim to store and read data using decimal type with precision and scale
> [BACKLOG-21076][BACKLOG-21077] Update the AvroOutput Dialog to support BigDecimal precision and scale.

- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileInputDialog.java
> [CLEANUP] change Pentaho to Hitachi Vantara and update copyright date.

- assemblies/pmr-libraries/pom.xml
- assemblies/pmr-libraries/src/main/descriptors/assembly.xml
@pentaho/2-1b 
Depends on https://github.com/pentaho/pentaho-registry/pull/11
> [BACKLOG-13943] Downstream updates

- kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTStreamSource.java
depends on pentaho/pentaho-kettle#4903
> [BACKLOG-20780] MQTT Consumer log the Quality of Service Level

- kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTConsumer.java
- kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTStreamSource.java
- kettle-plugins/mqtt/src/test/java/org/pentaho/di/trans/step/mqtt/MQTTStreamSourceTest.java
Preparatory change.  Builder pattern for MQTTStreamSource.
https://jira.pentaho.com/browse/BACKLOG-21243
> [BACKLOG-21243] MQTT Consumer - Implement Secure Protocol Support

- kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTConsumerDialog.java
- kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTConsumerMeta.java
- kettle-plugins/mqtt/src/main/resources/org/pentaho/di/trans/step/mqtt/messages/messages_en_US.properties
Initial UI commit so we can work on the backend implementation
> [BACKLOG-21225][BACKLOG-21243] Add Security tab to MQTT Consumer

- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/output/AvroOutput.java
Variables were not resolved for most of the fields. Bounced code against dialog to ensure that fields with variable indicators resolve variables correctly now.
> [BAD-1425] - Compression value doesn't resolve variables

- kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTClientBuilder.java
- kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTConsumerDialog.java
- kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTConsumerMeta.java
- kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTProducerDialog.java
- kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTStreamSource.java
- kettle-plugins/mqtt/src/test/java/org/pentaho/di/trans/step/mqtt/MQTTConsumerMetaTest.java
Updates to MQTTConsumerMeta/dialog for ssl metadata,
as well as changes to StreamSource to support it.
https://jira.pentaho.com/browse/BACKLOG-21243
> [BACKLOG-21243] MQTT Consumer - SSL

- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/BaseFormatInputField.java
- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/BaseFormatOutputField.java
- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/input/AvroInputField.java
- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/input/AvroInputMetaBase.java
- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/output/AvroOutputField.java
- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/output/AvroOutputMetaBase.java
- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/orc/OrcInputField.java
- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/orc/input/OrcInputMetaBase.java
- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/orc/output/OrcOutputField.java
- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/orc/output/OrcOutputMetaBase.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/input/AvroInput.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/input/AvroInputDialog.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/output/AvroOutputDialog.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/orc/input/OrcInput.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/orc/input/OrcInputDialog.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/orc/input/OrcInputMeta.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/orc/output/OrcOutput.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/orc/output/OrcOutputDialog.java
- kettle-plugins/formats/src/main/resources/org/pentaho/big/data/kettle/plugins/formats/impl/orc/output/messages/messages_en_US.properties
[BACKLOG-21340] Update OrcOutput dialog to provide ORC type in a listbox instead of PDI types
[BACKLOG-21426] Implement new Orc input structure using orc specification (non-ael)
@pentaho/moseisley Please review
> [BACKLOG-21340][BACKLOG-21426] Feature Orc Output and Input

- assemblies/pmr-libraries/pom.xml
- assemblies/pmr-libraries/src/main/descriptors/assembly.xml
- kettle-plugins/hive/pom.xml
- pom.xml
@pentaho/x-wing 
Depends on https://github.com/pentaho/pentaho-commons-database/pull/149
> [BACKLOG-20414] pentaho-commons-database downstream update

- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/orc/output/OrcOutputMetaBase.java
> [BACKLOG-21440] Update OrcOutput dialog to provide ORC type in a listbox instead of PDI types

- kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTConstants.java
- kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTConsumer.java
- kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTConsumerDialog.java
- kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTConsumerMeta.java
- kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTProducer.java
- kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTProducerDialog.java
- kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTProducerMeta.java
- kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MqttDialogSecurityLayout.java
- kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/SslConfigHelper.java
- kettle-plugins/mqtt/src/test/java/org/pentaho/di/trans/step/mqtt/MQTTConsumerMetaTest.java
- kettle-plugins/mqtt/src/test/java/org/pentaho/di/trans/step/mqtt/MQTTProducerMetaTest.java
- kettle-plugins/mqtt/src/test/java/org/pentaho/di/trans/step/mqtt/SslConfigHelperTest.java
1)  Extracted common security layout UI widgets into a separate class.
2)  Added Meta elements for SSL
3)  Wired up connection properties for SSL.
TODO:
1)  refactor meta serialization and add support for repository r/w.
2)  Ux cleanup
https://jira.pentaho.com/browse/BACKLOG-21249
> [BACKLOG-21249] First pass at MQTT Producer + SSL support

- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileInputDialog.java
- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileInputMeta.java
- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileOutputDialog.java
- kettle-plugins/hdfs/src/main/resources/org/pentaho/big/data/kettle/plugins/hdfs/trans/messages/messages_en_US.properties
> [SP-4100] Backport of PDI-16816 - Hadoop File Input misses Environment field in ETL Metadata Injection (8.0 Suite)

- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/output/AvroOutput.java
> [SP-4144][BAD-1425]-Avro Output step: "Compression" dropdown doesn't use values via variables

- kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTProducerDialog.java
- kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MqttDialogSecurityLayout.java
https://jira.pentaho.com/browse/BACKLOG-21249
> [BACKLOG-21249] Ux tweaks to the SSL table and producer dialog size.

- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileInputDialog.java
- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileInputMeta.java
- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileOutputDialog.java
- kettle-plugins/hdfs/src/main/resources/org/pentaho/big/data/kettle/plugins/hdfs/trans/messages/messages_en_US.properties
Reverts pentaho/big-data-plugin#1311
> Revert "[SP-4100] Backport of PDI-16816 - Hadoop File Input misses Environment field in ETL Metadata Injection (8.0 Suite)"

- assemblies/pmr-libraries/pom.xml
@duarteteixeira @pamval @mbatchelor @mkambol
> [PPP-4019] Use of vulnerable component Apache POI 3.15 CVE-2017-12626

- kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTConsumerMeta.java
- kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTProducerMeta.java
- kettle-plugins/mqtt/src/test/java/org/pentaho/di/trans/step/mqtt/MQTTConsumerMetaTest.java
- kettle-plugins/mqtt/src/test/java/org/pentaho/di/trans/step/mqtt/MQTTProducerMetaTest.java
- kettle-plugins/mqtt/src/test/java/org/pentaho/di/trans/step/mqtt/MQTTProducerTest.java
- kettle-plugins/mqtt/src/test/resources/ConsumeRows.ktr
- kettle-plugins/mqtt/src/test/resources/ProduceFourRows.ktr
> [BACKLOG-21866] Updating MQTT Consumer/Producer to use the new

- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/input/AvroInputMetaBase.java
- kettle-plugins/formats-meta/src/test/java/org/pentaho/big/data/kettle/plugins/formats/avro/input/AvroInputMetaBaseTest.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/input/AvroInput.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/input/AvroInputDialog.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/input/AvroInputMeta.java
- kettle-plugins/formats/src/main/resources/org/pentaho/big/data/kettle/plugins/formats/impl/avro/output/messages/messages_en_US.properties
- kettle-plugins/formats/src/test/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/input/AvroInputMetaTest.java
Reverts pentaho/big-data-plugin#1338
> Revert "[BACKLOG-22075] - Enable metadata injection support AvroInput and AvroOutput"

- assemblies/legacy-plugin/pom.xml
- pom.xml
> [BAD-1457]-BigData Plugin update, remove mapr520 and emr59

- assemblies/features/pom.xml
- pom.xml
@pentaho/x-wing 
Depends on https://github.com/pentaho/maven-parent-poms/pull/53
> [ENGOPS-2977] Update build helper plugin

- kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTConsumerMeta.java
- kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTProducerDialog.java
- kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTProducerMeta.java
https://github.com/pentaho/pentaho-kettle/pull/5032
> [BACKLOG.20158] StepDialog name changed to PluginDialog

- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/BaseParquetStepDialog.java
> [PDI-17081]-Parquet Input & Output steps: User password is not hidden by asterisks in the field "Folder/File Name"

- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/FormatInputFile.java
- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/input/AvroInputMetaBase.java
- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/orc/input/OrcInputMetaBase.java
- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/parquet/input/ParquetInputMetaBase.java
- kettle-plugins/formats-meta/src/test/java/org/pentaho/big/data/kettle/plugins/formats/avro/input/AvroInputMetaBaseTest.java
- kettle-plugins/formats-meta/src/test/java/org/pentaho/big/data/kettle/plugins/formats/orc/input/OrcInputMetaBaseTest.java
- kettle-plugins/formats-meta/src/test/java/org/pentaho/big/data/kettle/plugins/formats/parquet/input/ParquetInputMetaBaseTest.java
option "Run resulting transformation" is unchecked
> [PDI-16986] - Metadata Injection: Get "index out of bound" error when

- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInputDialog.java
[BACKLOG-22283] Move variable icon from outside of topic table to inside each cell
> [BACKLOG-22283] Move variable icon from outside of topic table to inside each cell

- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/BaseAvroStepDialog.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/input/AvroInput.java
Reverts pentaho/big-data-plugin#1366
> Revert "[BACKLOG-21321] Avro Streaming enhancments ( pass fields from prior s…"

- kettle-plugins/kafka/src/main/resources/org/pentaho/big/data/kettle/plugins/kafka/messages/messages_en_US.properties
https://jira.pentaho.com/browse/BACKLOG-22361
> [BACKLOG-22361] Adding desc for kafka SUB_STEP metadata injection

- kettle-plugins/kafka/src/main/resources/org/pentaho/big/data/kettle/plugins/kafka/messages/messages_en_US.properties
https://jira.pentaho.com/browse/BACKLOG-22361
> [BACKLOG-22361] Incorrect message key used in prev commit

- kettle-plugins/formats-meta/pom.xml
- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/parquet/output/ParquetOutputMetaBase.java
- kettle-plugins/formats-meta/src/test/java/org/pentaho/big/data/kettle/plugins/formats/parquet/output/ParquetOutputMetaBaseTest.java
- fixed: change compare from equals to equalsIgnoreCase and use "None" as default value
> [SP-4266][BAD-1423]-Parquet Output step: NPE appears if a user use in "Compression" dropdown values with different letter case or another value

- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/BaseParquetStepDialog.java
> [SP-4263][PDI-17081]-Parquet Input & Output steps: User password is not hidden by asterisks in the field "Folder/File Name"

- legacy/src/main/java/org/pentaho/amazon/emr/job/AmazonElasticMapReduceJobExecutor.java
- legacy/src/main/java/org/pentaho/amazon/hive/job/AmazonHiveJobExecutor.java
…ep, JMS Producer step, Amazon EMR Job Executor entry, and Amazon Hive Job entry
> Help Links need to be created for the JMS Consumer step, JMS Producer step, Amazon EMR Job Executor entry, and Amazon Hive Job entry

- legacy/pom.xml
Reverts pentaho/big-data-plugin#1401
> Revert "[PPP-4108] - Use of vulnerable component jackson-databind-2.8.8.jar, …"

- kettle-plugins/common/ui/pom.xml
- kettle-plugins/common/ui/src/main/java/org/pentaho/big/data/plugins/common/ui/NamedClusterComposite.java
> [BACKLOG-20237] - Update the Named Cluster Dialog to provide the user a way to set the shim identifier.

- kettle-plugins/hdfs/pom.xml
- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileInputMeta.java
- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileMeta.java
- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileOutputMeta.java
- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/analyzer/HadoopBaseStepAnalyzer.java
- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/analyzer/HadoopFileInputExternalResourceConsumer.java
- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/analyzer/HadoopFileInputStepAnalyzer.java
- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/analyzer/HadoopFileOutputExternalResourceConsumer.java
- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/analyzer/HadoopFileOutputStepAnalyzer.java
- kettle-plugins/hdfs/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- kettle-plugins/hdfs/src/main/resources/graph.properties
- kettle-plugins/hdfs/src/test/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileInputMetaTest.java
- kettle-plugins/hdfs/src/test/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileOutputDialogTest.java
- kettle-plugins/hdfs/src/test/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/analyzer/HadoopBaseStepAnalyzerTest.java
- kettle-plugins/hdfs/src/test/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/analyzer/HadoopFileInputStepAnalyzerTest.java
- kettle-plugins/hdfs/src/test/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/analyzer/HadoopFileOutputStepAnalyzerTest.java
- kettle-plugins/hdfs/src/test/resources/graph.properties
- kettle-plugins/spark/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- pom.xml
Additionally, fixed a benign typo in the spark blueprint.xml and a previously failing HadoopFileOutputDialogTest
> [BACKLOG-24279][BACKLOG-24281] Data Lineage analyzers for the Hadoop file input and output steps

- assemblies/pmr-libraries/pom.xml
- impl/clusterTests/pom.xml
- impl/shim/common/pom.xml
- pom.xml
This reverts commit 022bd3ad03e68bca2da9a77ec4d451ddeece5b47.
> Revert "[BACKLOG-24517] Fixes bundle version issues."

- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/output/ParquetOutputDialog.java
> [BACKLOG-24815] Parquet: Add support for INT96 (NON-AEL)

- kettle-plugins/kafka/src/main/resources/org/pentaho/big/data/kettle/plugins/kafka/messages/messages_en_US.properties
- kettle-plugins/kafka/src/test/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInputTest.java
[BACKLOG-23963] Add MDI description for Kafka offset control
> [BACKLOG-23963] Add MDI description for Kafka offset control

- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/analyzer/HadoopBaseStepAnalyzer.java
- kettle-plugins/hdfs/src/test/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/analyzer/HadoopBaseStepAnalyzerTest.java
Additionally, performed some cleanup of unnecessary File sub-types
Related PRs:
https://github.com/pentaho/pentaho-kettle/pull/5736
https://github.com/pentaho/pentaho-metaverse/pull/482
https://github.com/pentaho-es/pdi-igc-lineage-plugin/pull/3
> [BACKLOG-25105] Adding HDFS input/output resources

- kettle-plugins/kafka/src/main/resources/org/pentaho/big/data/kettle/plugins/kafka/messages/messages_en_US.properties
[BACKLOG-23963] Update MDI description for Kafka offset control
> [BACKLOG-23963] Update MDI description for Kafka offset control

- kettle-plugins/spark/src/main/java/org/pentaho/di/job/entries/spark/JobEntrySparkSubmit.java
- kettle-plugins/spark/src/main/java/org/pentaho/di/job/entries/spark/JobEntrySparkSubmitAnalyzer.java
Related PRs:
https://github.com/pentaho-es/pdi-igc-lineage-plugin/pull/7
https://github.com/pentaho/pentaho-metaverse/pull/484
> [BACKLOG-25113] Add application jar path to spark submit step

- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/analyzer/HadoopBaseStepAnalyzer.java
- kettle-plugins/hdfs/src/test/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/analyzer/HadoopBaseStepAnalyzerTest.java
- kettle-plugins/spark/src/main/java/org/pentaho/di/job/entries/spark/JobEntrySparkSubmit.java
- kettle-plugins/spark/src/main/java/org/pentaho/di/job/entries/spark/JobEntrySparkSubmitAnalyzer.java
> [SP-4635][SP-4634] Backport of BACKLOG-25105, Backport of BACKLOG-25113

- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/analyzer/HadoopBaseStepAnalyzer.java
- kettle-plugins/hdfs/src/test/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/analyzer/HadoopBaseStepAnalyzerTest.java
> [SP-4635] Adding HDFS input/output resources

- assemblies/features/src/main/resources/features.xml
> [CLEANUP] Fixing broken build

- legacy/src/main/java/org/pentaho/amazon/s3/S3NVfsFileChooserDialog.java
AWS credentials error was not being handled properly
> [BACKLOG-24871] - Fixed UI error in S3 open file dialog

- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/input/AvroInputField.java
- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/input/AvroInputMetaBase.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/input/AvroInputDialog.java
Moved indexes and keys to the index column
Made path column read only
Made index column editable
> [BACKLOG-25986] - Moved indexes and keys to the index column

- kettle-plugins/hbase-meta/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/meta/AELHBaseValueMetaImpl.java
Converts types based on input type and HBase mapping output type
> BACKLOG-26151 HBase Type Conversions

- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/input/AvroInputMetaBase.java
- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/input/AvroLookupField.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/input/AvroInput.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/input/AvroInputDialog.java
> [BACKLOG-25763] - Avro Input - Add extra features from the Legacy Avro Input Step

- kettle-plugins/hbase-meta/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/meta/AELHBaseValueMetaImpl.java
- kettle-plugins/hbase-meta/src/test/java/org/pentaho/big/data/kettle/plugins/hbase/meta/AELHBaseValueMetaTest.java
Pulls boolean conversions code from shims and integrates with AEL
> BACKLOG-26153 adds boolean conversions to HBase Input

- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/input/AvroInput.java
- kettle-plugins/formats/src/test/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/input/AvroInputTest.java
> [BACKLOG-25763] - Avro Input - Add support for reading JSON from a field.

- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/input/AvroInputMetaBase.java
- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/input/AvroLookupField.java
- kettle-plugins/formats-meta/src/test/java/org/pentaho/big/data/kettle/plugins/formats/avro/input/AvroInputMetaBaseTest.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/BaseAvroStepDialog.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/input/AvroInput.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/input/AvroInputDialog.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/input/AvroInputMeta.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/output/AvroOutputDialog.java
- kettle-plugins/formats/src/main/resources/org/pentaho/big/data/kettle/plugins/formats/impl/avro/input/messages/messages_en_US.properties
- kettle-plugins/formats/src/test/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/input/AvroInputMetaTest.java
> [BACKLOG-25974] Avro Input - Add metainjection support

- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileInputMeta.java
- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileOutputDialog.java
- kettle-plugins/hdfs/src/test/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileInputMetaTest.java
Also fix some breaking unit tests and add new ones to detect this problem in the future.
> [BACKLOG-26420] 8.1 HadoopFileInput/OutputStep does not load in 8.2.

- assemblies/features/src/main/resources/features.xml
Combined HDP26 CE shim into single jar (pentaho-hadoop-shims-hdp26-common)
> [BACKLOG-26717] Combined HDP26 CE shim into single jar

- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaDialogHelper.java
Reverting back to logic before the sonar cleanup (df4e19b172b41fe3)
I had formerly modified to avoid losing any exceptions thrown
within the CompletableFuture threads in DialogHelper.clusterNameChanged,
but it's actually okay to ignore exceptions in this block since
it should just result in an empty drop down.
https://jira.pentaho.com/browse/BACKLOG-27044
> [BACKLOG-27044] Kafka topic-drop down times out.

- assemblies/pmr-libraries/pom.xml
- assemblies/pmr-libraries/src/main/descriptors/assembly.xml
@pentaho/moseisley please review.
> [BACKLOG-26856] - Enable Pentaho MapReduce with multiple concurrent shims.

- kettle-plugins/kafka/pom.xml
- kettle-plugins/kafka/src/it/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerStepAnalyzerIT.java
- kettle-plugins/kafka/src/it/resources/solution/system/pentahoObjects.spring.xml
- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerERC.java
- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerStepAnalyzer.java
- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaProducerStepAnalyzer.java
- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaStepAnalyzer.java
- kettle-plugins/kafka/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Add support for mulitple topics on a consumer.
> [BACKLOG-26934] Implement linking between parent trans and subtrans.

- impl/shim/hbase/pom.xml
- impl/shim/hdfs/pom.xml
- impl/shim/initializer/pom.xml
- impl/shim/mapreduce/pom.xml
- impl/shim/oozie/pom.xml
- impl/shim/pig/pom.xml
- impl/shim/shimTests/pom.xml
> [BACKLOG-27564] Centralize Aries Blueprint dependency management

- api/jdbc/pom.xml
- impl/cluster/pom.xml
- impl/shim/common/pom.xml
- impl/shim/format/pom.xml
- impl/shim/hbase/pom.xml
- impl/shim/hdfs/pom.xml
- impl/shim/hive/pom.xml
- impl/shim/initializer/pom.xml
- impl/shim/jaas/pom.xml
- impl/shim/mapreduce/pom.xml
- impl/shim/oozie/pom.xml
- impl/shim/pig/pom.xml
- impl/shim/shimTests/pom.xml
- impl/shim/sqoop/pom.xml
- kettle-plugins/hive/pom.xml
- osgi-jaas/pom.xml
- pom.xml
> [BACKLOG-27567] Centralize org.osgi dependencies management

- assemblies/pmr-libraries/pom.xml
- assemblies/pmr-libraries/src/main/descriptors/assembly.xml
> [BACKLOG-27575] Remove Felix Main dependency

- assemblies/legacy-plugin/pom.xml
- legacy/pom.xml
- pom.xml
This is a series of PRs to update the version of AWS Java SDK across all repositories.
See: https://github.com/pentaho/maven-parent-poms/pull/114
@pentaho/tatooine @ssamora
> [PDI-17867] Fixes not closing connections leading to timeouts

- legacy/pom.xml
- legacy/src/test/java/org/pentaho/amazon/AbstractAmazonJobExecutorTest.java
> [BACKLOG-27762] Fix accidental reversion in pom file, update unit test

- kettle-plugins/mapreduce/src/main/resources/org/pentaho/big/data/kettle/plugins/mapreduce/ui/entry/JobEntryHadoopJobExecutorDialog.xul
Reverts pentaho/big-data-plugin#1655
> Revert "[SP-4997] - Backport of PDI-17630 - PDI - Hadoop Job Executor step do…"

- assemblies/legacy-plugin/pom.xml
- pom.xml
@tkafalas @lucboudreau Please review.
> [BAD-1781][BAD-1782] - Removed the hdp26 and cdh514 shim.

- assemblies/legacy-plugin/src/main/assembly/resources/plugin.properties
@bantonio82, @smmribeiro
cc @pentaho-lmartins, @ssamora + @gryphendowre, @wseyler, @emartin-pentaho
> [SP-5081] Partial Revert of 46feb4e95e33fd4216b5179ff784f8c49e7cdb8b commit

- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/output/AvroOutputMeta.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/orc/input/OrcInputMeta.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/orc/output/OrcOutputMeta.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/input/ParquetInputMeta.java
- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/output/ParquetOutputMeta.java
- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/input/HBaseInputMeta.java
- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/output/HBaseOutputMeta.java
- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/job/JobEntryHadoopCopyFiles.java
- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileInputMeta.java
- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileOutputMeta.java
- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInputMeta.java
- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaProducerOutputMeta.java
- kettle-plugins/mapreduce/src/main/java/org/pentaho/big/data/kettle/plugins/mapreduce/entry/pmr/JobEntryHadoopTransJobExecutor.java
- kettle-plugins/mapreduce/src/main/java/org/pentaho/big/data/kettle/plugins/mapreduce/step/enter/HadoopEnterMeta.java
- kettle-plugins/mapreduce/src/main/java/org/pentaho/big/data/kettle/plugins/mapreduce/step/exit/HadoopExitMeta.java
- kettle-plugins/spark/src/main/java/org/pentaho/di/job/entries/spark/JobEntrySparkSubmit.java
- legacy/src/main/java/org/pentaho/amazon/emr/job/AmazonElasticMapReduceJobExecutor.java
- legacy/src/main/java/org/pentaho/amazon/hive/job/AmazonHiveJobExecutor.java
- legacy/src/main/java/org/pentaho/di/trans/steps/avroinput/AvroInputMeta.java
- legacy/src/main/java/org/pentaho/di/trans/steps/couchdbinput/CouchDbInputMeta.java
> [BACKLOG-29422] Update and Validate In-Product Links in 8.3

- legacy/src/main/resources/org/pentaho/di/ui/hadoop/configuration/messages/messages_en_US.properties
> [BACKLOG-29422] updated the hadoop distribution help link in PDI

- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/input/AvroInputMeta.java
- legacy/src/main/java/org/pentaho/amazon/s3/S3FileOutputMeta.java
> [BACKLOG-29422] more updated doc links for 8.3

- assemblies/pmr-libraries/pom.xml
- assemblies/pmr-libraries/src/main/descriptors/assembly.xml
CC:
@pentaho/millenniumfalcon 
@jgminder 
@nantunes 
@graimundo
> [BACKLOG-29706] - PMR-CE assembly - Migrating from deprecated old style

- assemblies/pmr-libraries/pom.xml
- impl/shim/sqoop/pom.xml
- kettle-plugins/common/job/pom.xml
- kettle-plugins/hbase/pom.xml
- kettle-plugins/mapreduce/pom.xml
- kettle-plugins/oozie/pom.xml
- kettle-plugins/sqoop/pom.xml
@pentaho/tatooine @pentaho-lmartins @wseyler 
* [PDI-17794] Removed version references due to maven-parent-poms controlling that aspect
* [PDI-17794] Removing dependencies due to being marked as unused and declared via dependency:analyze (impl/shim/sqoop/pom.xml, kettle-plugins/mapreduce/pom.xml, kettle-plugins/oozie/pom.xml, kettle-plugins/hbase/pom.xml)
This pull request is part of a series of pull requests:
- https://github.com/pentaho/maven-parent-poms/pull/137
- https://github.com/pentaho/adaptive-execution-layer/pull/3
- https://github.com/pentaho/big-data-plugin/pull/1682
- https://github.com/webdetails/cdf/pull/1075
- https://github.com/pentaho/commons-ee/pull/1
- https://github.com/webdetails/cpf/pull/144
- https://github.com/webdetails/cpk/pull/82
- …
> [PDI-17794] Warnings in Spoon console due to wrong version of log4j

- kettle-plugins/common/ui/src/main/java/org/pentaho/big/data/plugins/common/ui/HadoopClusterDelegateImpl.java
Reverts pentaho/big-data-plugin#1742
> Revert "[BACKLOG-28399] Change to debug failing test on server."

- kettle-plugins/hadoop-cluster/ui/src/main/java/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/endpoints/HadoopClusterManager.java
> [BACKLOG-27754] Hadoop Cluster UX - Create New Unsecured Cluster Configuration from Site XML

- kettle-plugins/hadoop-cluster/ui/src/main/javascript/app/components/creating/creating.component.js
- kettle-plugins/hadoop-cluster/ui/src/main/javascript/app/components/hadoopcluster/hadoopcluster.component.js
- kettle-plugins/hadoop-cluster/ui/src/main/javascript/app/components/hadoopcluster/hadoopcluster.css
- kettle-plugins/hadoop-cluster/ui/src/main/javascript/app/components/hadoopcluster/hadoopcluster.html
- kettle-plugins/hadoop-cluster/ui/src/main/javascript/app/service/data.service.js
- kettle-plugins/hadoop-cluster/ui/src/main/resources/i18n/hadoop-cluster/messages.properties
- kettle-plugins/hadoop-cluster/ui/src/main/resources/i18n/hadoop-cluster/messages_en.properties
UI changes.
https://jira.pentaho.com/browse/BACKLOG-30592
https://xd.adobe.com/view/9355e214-e06a-4057-6026-d68aebe06663-e564/?fullscreen
> [BACKLOG-30592] Add Shim/driver to Cluster Configuration

- kettle-plugins/common/ui/src/test/java/org/pentaho/big/data/plugins/common/ui/HadoopClusterDelegateImplTest.java
> Cleanup failing unit test; test was expecting a metastore directory to

- assemblies/pmr-libraries/src/main/descriptors/assembly.xml
These entries already exist above (lines 75-76).
@angel-ramoscardona
> [CLEANUP] Remove duplicated entries

- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInputDialog.java
the parent streaming transformation
> [BACKLOG-31578] - pulling logic for determining sub-trans fields up to

- kettle-plugins/hadoop-cluster/ui/src/main/java/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/endpoints/HadoopClusterEndpoints.java
- kettle-plugins/hadoop-cluster/ui/src/main/java/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/endpoints/HadoopClusterManager.java
- kettle-plugins/hadoop-cluster/ui/src/main/resources-filtered/OSGI-INF/blueprint/beans.xml
- kettle-plugins/hadoop-cluster/ui/src/test/java/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/endpoints/HadoopClusterManagerTest.java
Internal shim should not be directly selectable in the UI.
https://jira.pentaho.com/browse/BACKLOG-30640
> [BACKLOG-30640] Filtering out the internal shim from the list.

- impl/cluster/src/main/java/org/pentaho/big/data/impl/cluster/NamedClusterManager.java
- impl/vfs/hdfs/src/main/java/org/pentaho/big/data/impl/vfs/hdfs/nc/NamedClusterProvider.java
- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileOutputMeta.java
- kettle-plugins/mapreduce/src/main/java/org/pentaho/big/data/kettle/plugins/mapreduce/entry/NamedClusterLoadSaveUtil.java
- kettle-plugins/oozie/src/main/java/org/pentaho/big/data/kettle/plugins/oozie/OozieJobExecutorJobEntry.java
carte jobs running on a cluster.
> [BACKLOG-30160] Copy metastore to big-data-plugin directory for use in

- impl/cluster/src/main/java/org/pentaho/big/data/impl/cluster/NamedClusterManager.java
- impl/cluster/src/main/resources/org/pentaho/big/data/impl/cluster/messages/messages_en_US.properties
> [BACKLOG-30160] Handle exception when trying to get the big data plugin

- legacy/src/main/java/org/pentaho/amazon/s3/S3Details.java
https://jira.pentaho.com/browse/BACKLOG-30638
> [BACKLOG-30638] making props mutable-  was breaking serialization.

- kettle-plugins/common/ui/src/main/java/org/pentaho/big/data/plugins/common/ui/HadoopClusterDelegateImpl.java
- kettle-plugins/common/ui/src/main/resources/org/pentaho/big/data/plugins/common/ui/messages/messages_en_US.properties
Hey @angel-ramoscardona, @jgminder, @peterrinehart: Could you please take a look at this pull request?
Now sure if I should leave the null input parameter validations or perhaps throw exceptions when those are null?
Please let me know, thanks!
> [BACKLOG-29907] Adding function to backup old vendor shim config and add new one as needed

- kettle-plugins/hive/src/main/java/org/pentaho/big/data/kettle/plugins/hive/Hive2DatabaseMeta.java
- kettle-plugins/hive/src/main/java/org/pentaho/big/data/kettle/plugins/hive/ImpalaDatabaseMeta.java
- kettle-plugins/hive/src/test/java/org/pentaho/big/data/kettle/plugins/hive/ImpalaDatabaseMetaTest.java
[BACKLOG-32219] Adding changes to support hadoop cluster field in database connection
[BACKLOG-32219] Adding unit tests for impala database meta
[BACKLOG-32219] Adding changes to getNamedClusterList edge cases
Hey @angel-ramoscardona, @jgminder, @peterrinehart: Could you please take a look at this pull request? Thanks!
> Impala Connection - Update UI for Named Cluster

- kettle-plugins/common/ui/src/main/java/org/pentaho/big/data/plugins/common/ui/HadoopClusterDelegateImpl.java
- kettle-plugins/hadoop-cluster/ui/src/main/java/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/endpoints/HadoopClusterManager.java
clobbering local cluster config files.
> [BACKLOG-31726] Detect when connected to a repository to avoid

- legacy/src/main/java/org/pentaho/amazon/s3/provider/S3Provider.java
The S3 client library uses the SaxParserFactory, which relies
on the TCCL for loading implementations.  This change set TCCL
so the cl used has access to the correct sax implementation.
https://jira.pentaho.com/browse/BACKLOG-32300
> [BACKLOG-32300] VFS test can fail due to class not found error.

- impl/cluster/src/main/java/org/pentaho/big/data/impl/cluster/NamedClusterManager.java
> [BACKLOG-32234] Need to ensure metastore is not null before list

- kettle-plugins/oozie/src/main/java/org/pentaho/big/data/kettle/plugins/oozie/OozieJobExecutorJobEntry.java
- kettle-plugins/oozie/src/main/resources/org/pentaho/big/data/kettle/plugins/oozie/messages/messages_en_US.properties
- kettle-plugins/oozie/src/test/java/org/pentaho/big/data/kettle/plugins/oozie/OozieJobExecutorJobEntryTest.java
> [BACKLOG-32234] Improve error messages during validation; do not just

- kettle-plugins/mapreduce/src/main/java/org/pentaho/big/data/kettle/plugins/mapreduce/ui/entry/hadoop/JobEntryHadoopJobExecutorController.java
- kettle-plugins/mapreduce/src/main/resources/org/pentaho/big/data/kettle/plugins/mapreduce/ui/entry/JobEntryHadoopJobExecutorDialog.xul
> [BACKLOG-32247] Move named cluster GUI to main panel, improve error

- assemblies/features/src/main/feature/feature.xml
- kettle-plugins/hadoop-cluster/ui/src/main/javascript/app/service/data.service.js
- kettle-plugins/hadoop-cluster/ui/src/main/resources-filtered/app/index.html
hadoop-cluster-ui on pentaho server
> [BACKLOG-32449] - adjusting paths and including features for running

- kettle-plugins/hadoop-cluster/ui/src/main/java/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/dialog/HadoopClusterDialog.java
- kettle-plugins/hadoop-cluster/ui/src/main/javascript/app/components/kerberos/kerberos.html
- kettle-plugins/hadoop-cluster/ui/src/main/javascript/app/components/newEdit/newEdit.component.js
when not connected to the Server
https://jira.pentaho.com/browse/BACKLOG-32617
> [BACKLOG-32617] Hadoop Cluster UX - Hide Impersonation for Kerberos

- kettle-plugins/hadoop-cluster/ui/src/main/javascript/app/components/newEdit/newEdit.component.js
- kettle-plugins/hadoop-cluster/ui/src/main/javascript/app/components/newEdit/newEdit.html
https://jira.pentaho.com/browse/BACKLOG-32701
> [BACKLOG-32701]Cluster Dialog -prevent /

- kettle-plugins/hadoop-cluster/ui/src/main/javascript/app/components/import/import.component.js
- kettle-plugins/hadoop-cluster/ui/src/main/javascript/app/components/import/import.html
Missed the import page for handling both the "connectedToRepo"
flag, and slash prevention.
https://jira.pentaho.com/browse/BACKLOG-32449
> [BACKLOG-32449] Update Cluster UX and options for Client/Repo

- legacy/src/main/java/org/pentaho/di/ui/hadoop/configuration/HadoopConfigurationsSpoonPlugin.java
Spoon; no longer needed.  This entire legacy plugin needs to be
re-examined for relevance.
> [BACKLOG-32850] Remove the Hadoop Distribution... menu option from

- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileInputMeta.java
- kettle-plugins/hdfs/src/test/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileInputMetaTest.java
> [BACKLOG-32812] Avoid trying to connect to hadoop cluster if no cluster

- kettle-plugins/hadoop-cluster/ui/src/main/javascript/app/components/newEdit/newEdit.component.js
Hey @ricksjames, could you please take a look at this pull request? Thanks!
> [BACKLOG-32978] Adding validation to warn user of cluster duplication by name

- kettle-plugins/hadoop-cluster/ui/src/main/resources/app/css/index.css
Updated CSS.
https://jira.pentaho.com/browse/BACKLOG-33067
> [BACKLOG-33067] Hadoop Cluster dialog-black box on scrollbar

- kettle-plugins/hadoop-cluster/ui/src/main/javascript/app/components/accordianItem/accordianItem.component.js
- kettle-plugins/hadoop-cluster/ui/src/main/javascript/app/components/accordianItem/accordianItem.html
- kettle-plugins/hadoop-cluster/ui/src/main/resources/i18n/hadoopCluster/messages.properties
- kettle-plugins/hadoop-cluster/ui/src/main/resources/i18n/hadoopCluster/messages_en.properties
[BACKLOG-32813] Changing documentation link for 9.0 code line
> [BACKLOG-32813] Adding hyperlink for big data issues

- assemblies/pmr-libraries/pom.xml
- assemblies/pmr-libraries/src/main/resources/classes/org/apache/commons/vfs2/impl/providers.xml
- impl/cluster/pom.xml
- impl/cluster/src/test/java/org/pentaho/big/data/impl/cluster/NamedClusterImplTest.java
- impl/vfs/hdfs/pom.xml
- impl/vfs/hdfs/src/test/java/org/pentaho/big/data/impl/vfs/hdfs/HDFSFileNameParserTest.java
- impl/vfs/hdfs/src/test/java/org/pentaho/big/data/impl/vfs/hdfs/MapRFileNameParserTest.java
- kettle-plugins/hbase/pom.xml
- kettle-plugins/hdfs/pom.xml
- kettle-plugins/hdfs/src/test/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileOutputDialogTest.java
- kettle-plugins/kafka/pom.xml
- legacy/pom.xml
- pom.xml
@pentaho/tatooine @pentaho-lmartins @ssamora 
* [PDI-17775] Removing version reference, maven parent pom will control version.
* [PDI-17775] Modifying tests to mock scheme retrieval
* [PDI-17775] Update providers file to point to new Http4 provider designed to fix VFS issues (and point to proper dependency)
This PR is a part of a series of PR to upgrade commons-vfs2 and fix VFS issues with HTTP:
- https://github.com/pentaho/apache-vfs-browser/pull/60
- https://github.com/pentaho/big-data-plugin/pull/1929
- https://github.com/webdetails/cpk/pull/85
- https://github.com/pentaho/data-access/pull/1083
- https://github.com/pentaho/maven-parent-poms/pull/185
- https://github.com/pentaho/mondrian/pull/1177
- https://github.com/pentaho/pdi-jms-plugin/pull/73
- …
> [PDI-17775] Process Files step no longer supports HTTP scheme

- legacy/src/main/java/org/pentaho/amazon/s3/provider/S3Provider.java
- caught exception, return empty list
> [PDI-18608] When AWS token has expires using VFS Browser no indication

- impl/cluster/src/main/java/org/pentaho/big/data/impl/cluster/NamedClusterImpl.java
- impl/cluster/src/main/java/org/pentaho/big/data/impl/cluster/NamedClusterManager.java
- impl/cluster/src/test/java/org/pentaho/big/data/impl/cluster/NamedClusterImplTest.java
- impl/cluster/src/test/java/org/pentaho/big/data/impl/cluster/NamedClusterManagerTest.java
- impl/clusterTests/src/main/java/org/pentaho/big/data/impl/cluster/tests/hdfs/GatewayPingFileSystemEntryPoint.java
- kettle-plugins/common/namedClusterBridge/src/main/java/org/pentaho/big/data/plugins/common/ui/named/cluster/bridge/NamedClusterBridgeImpl.java
- kettle-plugins/common/ui/src/main/java/org/pentaho/big/data/plugins/common/ui/NamedClusterComposite.java
- kettle-plugins/common/ui/src/main/java/org/pentaho/big/data/plugins/common/ui/NamedClusterDialogImpl.java
- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/vfs/HadoopVfsConnection.java
- kettle-plugins/hdfs/src/test/java/org/pentaho/big/data/kettle/plugins/hdfs/vfs/HadoopVfsConnectionTest.java
- legacy/src/main/java/org/pentaho/di/core/namedcluster/NamedClusterManager.java
- legacy/src/main/java/org/pentaho/di/core/namedcluster/model/NamedCluster.java
* [BAD-1907] Updating License Headers
> [BAD-1907] Plain text password is stored in the shim configuration files

- kettle-plugins/hadoop-cluster/ui/src/main/java/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/endpoints/HadoopClusterManager.java
Cherry-pick of https://github.com/pentaho/big-data-plugin/pull/2009
> [SP-5386] Backport of PDI-18590 - Multi-Cluster - Hadoop Distro names not listed alphabetically in Driver Drop down list (9.0 Suite)

- assemblies/pmr-libraries/pom.xml
- assemblies/pmr-libraries/src/main/resources/classes/org/apache/commons/vfs2/impl/providers.xml
- impl/cluster/pom.xml
- impl/cluster/src/test/java/org/pentaho/big/data/impl/cluster/NamedClusterImplTest.java
- impl/vfs/hdfs/pom.xml
- impl/vfs/hdfs/src/test/java/org/pentaho/big/data/impl/vfs/hdfs/HDFSFileNameParserTest.java
- impl/vfs/hdfs/src/test/java/org/pentaho/big/data/impl/vfs/hdfs/MapRFileNameParserTest.java
- kettle-plugins/hbase/pom.xml
- kettle-plugins/hdfs/pom.xml
- kettle-plugins/hdfs/src/test/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileOutputDialogTest.java
- kettle-plugins/kafka/pom.xml
- legacy/pom.xml
- pom.xml
This reverts commit 8d975521ae74eb7a0a4a11afc9c6bab3e47d8b0a, reversing
changes made to 61088496e0a2e20c4834483a4cdf39865c07f79b.
This Revert PR is part of a series:
- https://github.com/pentaho/maven-parent-poms/pull/229
- https://github.com/pentaho/apache-vfs-browser/pull/62
- https://github.com/pentaho/big-data-plugin/pull/2040
- https://github.com/webdetails/cpk/pull/87
- https://github.com/pentaho/data-access/pull/1091
- https://github.com/pentaho/mondrian/pull/1202
- https://github.com/pentaho/pdi-jms-plugin/pull/76
- https://github.com/pentaho/pdi-platform-utils-plugin/pull/104
- https://github.com/pentaho/pdi-plugins-ee/pull/174
- https://github.com/pentaho/pdi-sap-hana-bulk-loader-plugin/pull/84
- https://github.com/pentaho/pdi-teradata-tpt-plugin/pull/53
- …
> Revert "Merge pull request #2035 from gryphendowre/SP-5370"

- impl/cluster/pom.xml
- impl/cluster/src/main/java/org/pentaho/big/data/impl/cluster/NamedClusterImpl.java
- impl/cluster/src/main/java/org/pentaho/big/data/impl/cluster/NamedClusterManager.java
- impl/cluster/src/test/java/org/pentaho/big/data/impl/cluster/NamedClusterImplTest.java
- impl/cluster/src/test/java/org/pentaho/big/data/impl/cluster/NamedClusterManagerTest.java
- impl/clusterTests/src/main/java/org/pentaho/big/data/impl/cluster/tests/hdfs/GatewayPingFileSystemEntryPoint.java
- kettle-plugins/common/namedClusterBridge/src/main/java/org/pentaho/big/data/plugins/common/ui/named/cluster/bridge/NamedClusterBridgeImpl.java
- kettle-plugins/common/ui/src/main/java/org/pentaho/big/data/plugins/common/ui/NamedClusterComposite.java
- kettle-plugins/common/ui/src/main/java/org/pentaho/big/data/plugins/common/ui/NamedClusterDialogImpl.java
- kettle-plugins/hadoop-cluster/ui/src/main/java/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/endpoints/HadoopClusterManager.java
- kettle-plugins/hadoop-cluster/ui/src/test/java/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/endpoints/HadoopClusterManagerTest.java
- kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/vfs/HadoopVfsConnection.java
- kettle-plugins/hdfs/src/test/java/org/pentaho/big/data/kettle/plugins/hdfs/vfs/HadoopVfsConnectionTest.java
- legacy/src/main/java/org/pentaho/di/core/namedcluster/NamedClusterManager.java
- legacy/src/main/java/org/pentaho/di/core/namedcluster/model/NamedCluster.java
This reverts commit 61088496e0a2e20c4834483a4cdf39865c07f79b, reversing
changes made to 9ce6452ae0f4de12fa59d31ba9261abd15360ab4.
PR is a set of Revert PRs:
- https://github.com/pentaho/pentaho-hadoop-shims/pull/1125
- https://github.com/pentaho/pentaho-yarn-kettle-plugin/pull/404
- https://github.com/pentaho/big-data-plugin/pull/2041
- https://github.com/pentaho/pentaho-big-data-ee/pull/445
- https://github.com/pentaho/pentaho-kettle/pull/7336
> Revert "Merge pull request #2025 from gryphendowre/SP-5422"

- s3-vfs/src/main/java/org/pentaho/s3common/S3CommonFileObject.java
- s3-vfs/src/test/java/org/pentaho/s3n/vfs/S3NFileObjectTest.java
Regression introduced by 3689605e2387f006dc86dad152f7d9553e49716a
@pentaho-lmartins 
@pentaho/r2d2
> [PDI-18788] S3 File Output step not creating new files in AWS S3

- assemblies/legacy-plugin/pom.xml
- pom.xml
Added dataproc1421 specific PMR libraries to hadoop configurations
> [BACKLOG-33825] Added dataproc1421 specific PMR libraries

- assemblies/legacy-plugin/src/main/assembly/resources/plugin.properties
- impl/shim/mapreduce/src/main/java/org/pentaho/big/data/impl/shim/mapreduce/PentahoMapReduceJobBuilderImpl.java
files from plugins that are pulled into a PMR deployment to the cluster.
> [SP-5678] Backport of PDI-18840.  Provide a way to exclude individual

- impl/vfs/hdfs/src/main/java/org/pentaho/big/data/impl/vfs/hdfs/nc/NamedClusterFileObject.java
- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/input/AvroInputMetaBase.java
- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/output/AvroOutputMetaBase.java
- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/orc/input/OrcInputMetaBase.java
- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/orc/output/OrcOutputMetaBase.java
- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/parquet/input/ParquetInputMetaBase.java
- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/parquet/output/ParquetOutputMetaBase.java
> [BACKLOG-34530] converts s3 to s3a for AEL PVFS files

- api/hbase/src/main/java/org/pentaho/bigdata/api/hbase/HBaseConnection.java
- impl/shim/hbase/src/main/java/com/pentaho/big/data/bundles/impl/shim/hbase/HBaseConnectionImpl.java
- impl/shim/hbase/src/main/java/com/pentaho/big/data/bundles/impl/shim/hbase/HBaseConnectionWrapper.java
- kettle-plugins/hbase/pom.xml
- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/HbaseUtil.java
- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/input/HBaseInputDialog.java
- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/input/HBaseInputMeta.java
- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/mapping/MappingAdmin.java
- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/mapping/MappingEditor.java
- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/output/HBaseOutputDialog.java
- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/output/HBaseOutputMeta.java
- kettle-plugins/hbase/src/test/java/org/pentaho/big/data/kettle/plugins/hbase/HbaseUtilTest.java
- kettle-plugins/hbase/src/test/java/org/pentaho/big/data/kettle/plugins/hbase/mapping/MappingAdminTest.java
- kettle-plugins/hbase/src/test/java/org/pentaho/big/data/kettle/plugins/hbase/mapping/MockHBaseByteConverterUsingJavaByteBuffer.java
Reverts pentaho/big-data-plugin#2136
> Revert "Revert "[SP-5778] Enable namespace nomenclature on hbase input/output steps""

- api/hbase/src/main/java/org/pentaho/bigdata/api/hbase/HBaseConnection.java
- impl/shim/hbase/src/main/java/com/pentaho/big/data/bundles/impl/shim/hbase/HBaseConnectionImpl.java
- impl/shim/hbase/src/main/java/com/pentaho/big/data/bundles/impl/shim/hbase/HBaseConnectionWrapper.java
- kettle-plugins/hbase/pom.xml
- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/HbaseUtil.java
- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/input/HBaseInputDialog.java
- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/input/HBaseInputMeta.java
- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/mapping/MappingAdmin.java
- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/mapping/MappingEditor.java
- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/output/HBaseOutputDialog.java
- kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/output/HBaseOutputMeta.java
- kettle-plugins/hbase/src/test/java/org/pentaho/big/data/kettle/plugins/hbase/HbaseUtilTest.java
- kettle-plugins/hbase/src/test/java/org/pentaho/big/data/kettle/plugins/hbase/mapping/MappingAdminTest.java
- kettle-plugins/hbase/src/test/java/org/pentaho/big/data/kettle/plugins/hbase/mapping/MockHBaseByteConverterUsingJavaByteBuffer.java
Reverts pentaho/big-data-plugin#2137
> Revert "Revert "[SP-5778] Enable namespace nomenclature on hbase input/output…"

- assemblies/legacy-plugin/pom.xml
- pom.xml
Changes required for new Cdpdc71 shim
> BACKLOG-34725 Cdpdc71 Shim integration

- legacy-amazon/src/main/java/org/pentaho/amazon/s3/S3FileOutputDialog.java
- legacy-amazon/src/main/java/org/pentaho/amazon/s3/S3FileOutputMeta.java
- legacy-amazon/src/test/java/org/pentaho/amazon/AbstractAmazonJobExecutorTest.java
- s3-vfs/src/main/java/org/pentaho/amazon/s3/S3Util.java
- s3-vfs/src/main/java/org/pentaho/s3/vfs/S3FileName.java
- s3-vfs/src/main/java/org/pentaho/s3/vfs/S3FileNameParser.java
- s3-vfs/src/main/java/org/pentaho/s3a/vfs/S3AFileName.java
- s3-vfs/src/main/java/org/pentaho/s3a/vfs/S3AFileNameParser.java
- s3-vfs/src/main/java/org/pentaho/s3common/S3CommonFileSystem.java
- s3-vfs/src/main/java/org/pentaho/s3n/vfs/S3NFileNameParser.java
- s3-vfs/src/test/java/org/pentaho/amazon/s3/S3UtilTest.java
- s3-vfs/src/test/java/org/pentaho/s3/vfs/S3FileNameParserTest.java
- s3-vfs/src/test/java/org/pentaho/s3/vfs/S3FileNameTest.java
- s3-vfs/src/test/java/org/pentaho/s3/vfs/S3FileObjectTest.java
- s3-vfs/src/test/java/org/pentaho/s3a/vfs/S3AFileNameParserTest.java
- s3-vfs/src/test/java/org/pentaho/s3n/vfs/S3NFileNameParserTest.java
@bcostahitachivantara @smmribeiro @moraesvc
> [PDI-18834] Hard coded access and secret keys in a S3 URI no longer work in 8.3

- impl/cluster/src/main/java/org/pentaho/big/data/impl/cluster/NamedClusterImpl.java
- impl/cluster/src/main/java/org/pentaho/big/data/impl/cluster/NamedClusterManager.java
- impl/cluster/src/test/java/org/pentaho/big/data/impl/cluster/NamedClusterImplTest.java
- kettle-plugins/hadoop-cluster/ui/src/main/java/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/endpoints/CachedFileItemStream.java
- kettle-plugins/hadoop-cluster/ui/src/main/java/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/endpoints/HadoopClusterEndpoints.java
- kettle-plugins/hadoop-cluster/ui/src/main/java/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/endpoints/HadoopClusterManager.java
- kettle-plugins/hadoop-cluster/ui/src/main/javascript/app/service/helper.service.js
- kettle-plugins/hadoop-cluster/ui/src/test/java/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/endpoints/HadoopClusterEndpointsTest.java
- kettle-plugins/hadoop-cluster/ui/src/test/java/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/endpoints/HadoopClusterManagerTest.java
> [BAD-1920] Optional automatic updates of Hadoop *-site.xml in cluster definition

- assemblies/pmr-libraries/pom.xml
(cherry picked from commit 8d2e98cfce46e6fe25e40d5e37e7585dbb8c0789)
> [SP-5969][BISERVER-14200] Upgrade Janino jar

- assemblies/pmr-libraries/pom.xml
(cherry picked from commit 8d2e98cfce46e6fe25e40d5e37e7585dbb8c0789)
> [SP-5968][BISERVER-14200] Upgrade Janino jar

- impl/cluster/src/main/java/org/pentaho/big/data/impl/cluster/NamedClusterManager.java
(cherry picked from commit 1ab467c041775d51ec639748c25aba0ce2aae90f)
> [SP-6013][BAD-1919] Fix site file autoload when running from pan/kitchen

- kettle-plugins/hadoop-cluster/ui/src/main/resources-filtered/app/index.html
- kettle-plugins/hadoop-cluster/ui/src/main/resources-filtered/app/package.json
> [CUST-253] - Requesting CUST for BAD-1920

- kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/output/ParquetOutput.java
- kettle-plugins/formats/src/test/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/output/ParquetOutputTest.java
@ssamora 
@smmribeiro 
@moraesvc
> [PDI-18832] - Parquet Output does not show the correct Output results in the log

- impl/shim/pig/src/main/java/org/pentaho/big/data/impl/shim/pig/KettleLogChannelFilter.java
- impl/shim/pig/src/main/java/org/pentaho/big/data/impl/shim/pig/PigServiceImpl.java
- impl/shim/pig/src/main/java/org/pentaho/big/data/impl/shim/pig/WriterAppenderManager.java
- impl/shim/pig/src/test/java/org/pentaho/big/data/impl/shim/pig/PigServiceImplTest.java
- impl/shim/pig/src/test/java/org/pentaho/big/data/impl/shim/pig/WriterAppenderManagerTest.java
> [SP-6106] [BACKLOG-35556] Ensure pig logs get sent to the kettle logging

- kettle-plugins/common/ui/src/main/resources/cdp71sampleconfig.properties
[BACKLOG-35705] : [Bigdata|CDP71] - Incorrect config.properties file related changes
> [BACKLOG-35705] : [Bigdata|CDP71] - Incorrect config.properties file related changes

- legacy-amazon/src/test/java/org/pentaho/amazon/AbstractAmazonJobExecutorTest.java
- s3-vfs/src/test/java/org/pentaho/s3/vfs/S3FileNameTest.java
- s3-vfs/src/test/java/org/pentaho/s3n/vfs/S3NFileNameTest.java
This commit is a cherry-pick from master 4f7bf54b
> [BACKLOG-35758] Unit test cleanup.

- kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/output/AvroOutputMetaBase.java
SP-6146: Backport changes related to PDI 19373
> [ SP-6146 ] : Backport changes related to PDI 19373

- kettle-plugins/browse/pom.xml
- kettle-plugins/browse/src/main/java/org/pentaho/big/data/impl/browse/NamedClusterProvider.java
- kettle-plugins/browse/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- kettle-plugins/hadoop-cluster/ui/pom.xml
- kettle-plugins/hadoop-cluster/ui/src/main/java/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/endpoints/HadoopClusterEndpoints.java
- kettle-plugins/hadoop-cluster/ui/src/main/resources-filtered/OSGI-INF/blueprint/beans.xml
- kettle-plugins/hadoop-cluster/ui/src/test/java/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/endpoints/HadoopClusterEndpointsTest.java
- kettle-plugins/hadoop-cluster/ui/src/test/java/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/endpoints/HadoopClusterManagerTest.java
> [BACKLOG-35939] Big data plugins need to reference new metastore locator

- assemblies/pmr-libraries/pom.xml
- impl/shim/common/pom.xml
- kettle-plugins/browse/pom.xml
- s3-vfs/pom.xml
This commit is a cherry-pick from master 3c0c6d88
> [SP-6179] [PPP-4654] Get commons-io version from parent pom

- kettle-plugins/hdfs/pom.xml
- legacy-amazon/pom.xml
- legacy-amazon/src/test/java/org/pentaho/amazon/AbstractAmazonJobExecutorTest.java
> [TEST] Unit test cleanup; missing dependency and environment not set up

- kettle-plugins/browse/src/main/java/org/pentaho/big/data/impl/browse/NamedClusterProvider.java
> [BACKLOG-35995] File provider needs to register itself with the file

- kettle-plugins/browse/src/main/java/org/pentaho/big/data/impl/browse/model/NamedClusterFile.java
ensure proper function within the Eclipse widgets.
> [BACKLOG-36268] Need to override the equals method for all file types to

- s3-vfs/src/main/java/org/pentaho/amazon/s3/S3DetailComposite.java
- s3-vfs/src/main/resources/org/pentaho/amazon/s3/messages/messages_en_US.properties
- Fix widget expansion off screen when text is long
- Fix Variable assignment in S3 region combo box.  It was not saving the variable.
- Check if a same name connection exists in another type before saving and disallow if it does.
> [BACKLOG-36255][BACKLOG-36309][BACKLOG-36304]

- kettle-plugins/browse/src/main/java/org/pentaho/big/data/impl/browse/NamedClusterProvider.java
> [BACKLOG-35955] Need to update call to Utils and provide the file

- s3-vfs/src/main/java/org/pentaho/amazon/s3/provider/S3Provider.java
locations so that the exception can be caught and reported by the file dialog.
> [BACKLOG-36560] Re-throw any exceptions hit while trying to get S3

- kettle-plugins/browse/src/main/java/org/pentaho/big/data/impl/browse/model/NamedClusterFile.java
a704ba7274ab988d1443b3f1ed0c31d70c946321
> [BACKLOG-36556] Fix for possible NPE in .equals implementation

- s3-vfs/src/main/java/org/pentaho/s3common/S3CommonFileObject.java
Please review this PR without merge until we get approval to push changes to master due 9.4 release code freeze.
@ssamora 
@smmribeiro 
@andreramos89 
@renato-s
> [PDI-19598] - "Create File" step does not create a file in the folder when S3(VFS) path is given.

- s3-vfs/pom.xml
- s3-vfs/src/main/java/org/pentaho/s3common/S3CommonFileObject.java
- s3-vfs/src/test/java/org/pentaho/s3/vfs/S3FileObjectTest.java
- s3-vfs/src/test/java/org/pentaho/s3n/vfs/S3NFileObjectTest.java
> [CUST-271] - Requesting CUST for PDI-19691 on 9.3.0.0-428

- assemblies/legacy-plugin/pom.xml
- legacy-amazon/pom.xml
- legacy/pom.xml
- s3-vfs/pom.xml
> [CUST-271] - Fixing pom versions

- assemblies/pmr-libraries/pom.xml
> [PPP-4660] - Use of Vulnerable Component: Components/jackson-databind:2.9.10.2

- assemblies/pmr-libraries/pom.xml
> [PPP-4815] - Vulnerable Component: Ini4j 0.5.1

- s3-vfs/src/main/java/org/pentaho/s3common/S3CommonFileObject.java
> [SP-6268] - Backport of PDI-19598 - "Create File" step does not create a file in the folder when S3(VFS) path is given. (9.3 Suite)

- s3-vfs/src/main/java/org/pentaho/s3common/S3CommonFileObject.java
> [SP-6269] - Backport of PDI-19598 - "Create File" step does not create a file in the folder when S3(VFS) path is given. (9.4 Suite)

- assemblies/pmr-libraries/pom.xml
> [SP-6282] - Backport of PPP-4815 - Vulnerable Component: Ini4j 0.5.1 (9.3 Suite)

- assemblies/pmr-libraries/pom.xml
- assemblies/pmr-libraries/src/main/descriptors/assembly.xml
@bcostahitachivantara @renato-s @andreramos89
> [PPP-4783] Vulnerable Component: nekohtml

- assemblies/pmr-libraries/pom.xml
@andreramos89 
@smmribeiro 
Original PR:
- https://github.com/pentaho/big-data-plugin/pull/2384
> [SP-6283] - Backport of PPP-4815 - Vulnerable Component: Ini4j 0.5.1 (9.4 Suite)

- assemblies/pmr-libraries/pom.xml
- assemblies/pmr-libraries/src/main/descriptors/assembly.xml
> [PPP-4828] - Component Rome is outdated

- assemblies/pmr-libraries/pom.xml
- assemblies/pmr-libraries/src/main/descriptors/assembly.xml
@smmribeiro 
@andreramos89 
@renato-s
> [PPP-3713] - Beanshell version we're using is vulnerable to serialization exploit - CVE-2016-2510

- assemblies/pmr-libraries/pom.xml
> [SP-6306] - Backport of PPP-4610 - Use of Vulnerable Component: Components/snakeyaml:1.25 (9.4 Suite)

- assemblies/pmr-libraries/pom.xml
> [SP-6305] - Backport of PPP-4610 - Use of Vulnerable Component: Components/snakeyaml:1.25 (9.3 Suite)

- impl/vfs/hdfs/src/main/java/org/pentaho/big/data/impl/vfs/hdfs/nc/NamedClusterFileObject.java
- kettle-plugins/browse/src/main/java/org/pentaho/big/data/impl/browse/NamedClusterProvider.java
- kettle-plugins/browse/src/main/java/org/pentaho/big/data/impl/browse/model/NamedClusterDirectory.java
- kettle-plugins/browse/src/main/java/org/pentaho/big/data/impl/browse/model/NamedClusterFile.java
- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInput.java
- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInputData.java
- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInputDialog.java
- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInputMeta.java
- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaDialogHelper.java
- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaFactory.java
- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaProducerOutput.java
- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaProducerOutputDialog.java
- kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaProducerOutputMeta.java
- kettle-plugins/kafka/src/test/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInputTest.java
- s3-vfs/src/main/java/org/pentaho/s3common/S3CommonFileObject.java
[BACKLOG-37508] S3 support for Vfs Metastore
[BACKLOG-37508]: https://hv-eng.atlassian.net/browse/BACKLOG-37508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-36830] - Kafka Enhancements (Plug-in Release)

- legacy-amazon/src/main/java/org/pentaho/amazon/AbstractAmazonJobExecutor.java
- legacy-amazon/src/main/java/org/pentaho/amazon/AbstractAmazonJobExecutorController.java
- s3-vfs/pom.xml
- s3-vfs/src/test/java/org/pentaho/s3/vfs/S3FileSystemTest.java
- s3-vfs/src/test/java/org/pentaho/s3n/vfs/S3NFileSystemTest.java
This reverts commit ca8c78caaf9f4c9d58e373586dd68ed4fe9fcfb1.
> Revert "[PDI-18433] Fix api changes from VFS upgrade"

- assemblies/pmr-libraries/pom.xml
- assemblies/pmr-libraries/src/main/descriptors/assembly.xml
- impl/vfs/hdfs/pom.xml
- legacy-amazon/src/main/java/org/pentaho/amazon/AbstractAmazonJobExecutor.java
- legacy-amazon/src/main/java/org/pentaho/amazon/AbstractAmazonJobExecutorController.java
- pom.xml
- s3-vfs/pom.xml
- s3-vfs/src/main/java/org/pentaho/amazon/s3/S3DetailComposite.java
- s3-vfs/src/main/java/org/pentaho/amazon/s3/provider/S3Provider.java
- s3-vfs/src/main/resources/org/pentaho/amazon/s3/messages/messages_en_US.properties
- s3-vfs/src/test/java/org/pentaho/s3/vfs/S3FileSystemTest.java
- s3-vfs/src/test/java/org/pentaho/s3n/vfs/S3NFileSystemTest.java
[PPP-4829] Upgrade Rhino on PRD and PDI
[PPP-4829]: https://hv-eng.atlassian.net/browse/PPP-4829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PPP-4829] Upgrade Rhino on PRD and PDI

- kettle-plugins/common/job/pom.xml
- legacy-amazon/pom.xml
- legacy/pom.xml
> [PPP-4833] H2-2.1.210 shipped it is currently vulnerable to specify password in cleartext

- assemblies/pmr-libraries/pom.xml
[PPP-4747]-Vulnerable Component :batik:1.19
[PPP-4747]: https://hv-eng.atlassian.net/browse/PPP-4747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PPP-4747]-Vulnerable Component :batik:1.19

- assemblies/pmr-libraries/pom.xml
- kettle-plugins/common/ui/pom.xml
[PPP-4936]-Vulnerable Component -Guava
[PPP-4936]: https://hv-eng.atlassian.net/browse/PPP-4936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PPP-4936]-Vulnerable Component -Guava

- s3-vfs/src/main/java/org/pentaho/amazon/s3/provider/S3Provider.java
@pentaho/hoth 
To be merged with:
https://github.com/pentaho/pentaho-scheduler-plugin/pull/57
https://github.com/pentaho/pentaho-platform/pull/5476
https://github.com/pentaho/pentaho-commons-gwt-modules/pull/1001
https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/68
https://github.com/pentaho/pdi-plugins-ee/pull/956
> [BACKLOG-37872] - Fix issues with runtime exception on test method

- s3-vfs/src/main/java/org/pentaho/amazon/s3/provider/S3Provider.java
Part of PR set: https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/89
/cc @pentaho/hoth
> [BACKLOG-39480] Fixed runtime exceptions passing through implementations of VFSConnectionProvider.test methods (for S3)

- assemblies/pmr-libraries/pom.xml
- assemblies/pmr-libraries/src/main/descriptors/assembly.xml
This reverts commit a26256ea4f111e7fee4fbcff972357e7947eabb0.
> Revert "[BACKLOG-39663] Hibernate Error starting Pentaho CE"

- kettle-plugins/hadoop-cluster/pom.xml
- kettle-plugins/hadoop-cluster/ui/pom.xml
@pentaho/millenniumfalcon please review
> chore: update requirejs artifact used in build [BACKLOG-39952]

- s3-vfs/src/main/java/org/pentaho/amazon/s3/S3Details.java
- s3-vfs/src/test/java/org/pentaho/amazon/s3/S3DetailsTest.java
To be merged after https://github.com/pentaho/pentaho-kettle/pull/9283
Part of PR group
https://github.com/pentaho/pdi-plugins-ee/pull/1050
https://github.com/pentaho/pentaho-kettle/pull/9283
https://github.com/pentaho/metastore/pull/89
> [BACKLOG-40063] - VFS Connection Manager : Allow permission to be applied on the VFS connections created from PUC

- kettle-plugins/mapreduce/pom.xml
- kettle-plugins/mapreduce/src/test/java/org/pentaho/big/data/kettle/plugins/mapreduce/entry/NamedClusterLoadSaveUtilTest.java
- kettle-plugins/mapreduce/src/test/java/org/pentaho/big/data/kettle/plugins/mapreduce/step/exit/HadoopExitTest.java
- kettle-plugins/mapreduce/src/test/java/org/pentaho/big/data/kettle/plugins/mapreduce/ui/entry/pmr/JobEntryHadoopTransJobExecutorControllerTest.java
- legacy/pom.xml
- legacy/src/test/java/org/pentaho/di/trans/steps/avroinput/AvroInputMetaAvroFieldTest.java
- legacy/src/test/java/org/pentaho/di/trans/steps/avroinput/AvroInputMetaLookupFieldTest.java
- legacy/src/test/java/org/pentaho/di/trans/steps/avroinput/AvroInputMetaTest.java
- legacy/src/test/java/org/pentaho/di/trans/steps/couchdbinput/CouchDbInputMetaTest.java
- legacy/src/test/java/org/pentaho/di/trans/steps/couchdbinput/CouchDbInputTest.java
- legacy/src/test/java/org/pentaho/hadoop/PropertiesConfigurationPropertiesTest.java
There are also updates required in other modules, but these ones should get the tests passing
> [TEST] Unit test fixes for JDK17

- kettle-plugins/sqoop/src/main/java/org/pentaho/big/data/kettle/plugins/sqoop/SqoopExportJobEntry.java
- kettle-plugins/sqoop/src/main/java/org/pentaho/big/data/kettle/plugins/sqoop/SqoopImportJobEntry.java
Fix SqoopExport/SqoopImport
@pentaho/tatooine_dev
> [SP-6555] Update and validate in-product links in Pentaho 9.3.0.8

- pom.xml
[PPP-5083]-Vulnerable Component: ion java
[PPP-5083]: https://hv-eng.atlassian.net/browse/PPP-5083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PPP-5083]-Vulnerable Component: ion java

- kettle-plugins/hadoop-cluster/pom.xml
- pom.xml
[PPP-4760]-Vulnerable Component: Apache CXF 3.3.1
[PPP-4760]: https://hv-eng.atlassian.net/browse/PPP-4760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PPP-4760]-Vulnerable Component: Apache CXF 3.3.1

- kettle-plugins/hadoop-cluster/pom.xml
- pom.xml
Revert - [PPP-4760]-Vulnerable Component: Apache CXF 3.3.1
[PPP-4760]: https://hv-eng.atlassian.net/browse/PPP-4760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Revert - [PPP-4760]-Vulnerable Component: Apache CXF 3.3.1

- kettle-plugins/sqoop/src/test/java/org/pentaho/big/data/kettle/plugins/sqoop/AbstractSqoopJobEntryTest.java
[BACKLOG-41345] - use new APIs for Tree
[BACKLOG-41345]: https://hv-eng.atlassian.net/browse/BACKLOG-41345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-41345] - use new APIs for Tree

- kettle-plugins/hive/src/main/java/org/pentaho/big/data/kettle/plugins/hive/BaseSimbaDatabaseMeta.java
- kettle-plugins/hive/src/main/java/org/pentaho/big/data/kettle/plugins/hive/Hive2SimbaDatabaseDialect.java
- kettle-plugins/hive/src/main/java/org/pentaho/big/data/kettle/plugins/hive/Hive2SimbaDatabaseMeta.java
- kettle-plugins/hive/src/main/java/org/pentaho/big/data/kettle/plugins/hive/ImpalaSimbaDatabaseDialect.java
- kettle-plugins/hive/src/main/java/org/pentaho/big/data/kettle/plugins/hive/ImpalaSimbaDatabaseMeta.java
- kettle-plugins/hive/src/main/java/org/pentaho/big/data/kettle/plugins/hive/SimbaUrl.java
- kettle-plugins/hive/src/test/java/org/pentaho/big/data/kettle/plugins/hive/BaseSimbaDatabaseMetaTest.java
- kettle-plugins/hive/src/test/java/org/pentaho/big/data/kettle/plugins/hive/Hive2SimbaDatabaseDialectTest.java
- kettle-plugins/hive/src/test/java/org/pentaho/big/data/kettle/plugins/hive/Hive2SimbaDatabaseMetaTest.java
- kettle-plugins/hive/src/test/java/org/pentaho/big/data/kettle/plugins/hive/ImpalaSimbaDatabaseMetaTest.java
- kettle-plugins/hive/src/test/java/org/pentaho/big/data/kettle/plugins/hive/SimbaUrlTest.java
> [PDI-18031] - ODBC access type does not work and should be removed from connection dialogs

- kettle-plugins/hadoop-cluster/pom.xml
@pentaho/millenniumfalcon please review
> chore: centralize dojo.version [PPP-4824]

- kettle-plugins/hadoop-cluster/pom.xml
@pentaho/millenniumfalcon please review
Original PR:
- https://github.com/pentaho/big-data-plugin/pull/2613
Depends on:
- https://github.com/pentaho/maven-parent-poms/pull/611
> [SP-6590] Backport of PPP-4824 - Vulnerable Component: dojo 1.9.3 (10.2 Suite)

- assemblies/legacy-plugin/pom.xml
- kettle-plugins/common/ui/src/main/resources/dataproc1421sampleconfig.properties
- kettle-plugins/common/ui/src/main/resources/emr521sampleconfig.properties
- kettle-plugins/common/ui/src/main/resources/hdi40sampleconfig.properties
- pom.xml
Reverts pentaho/big-data-plugin#2623
> Revert "[BACKLOG-42279] Remove obsolete shim drivers for 10.2.0.1 build pipel…"

- assemblies/features/src/main/feature/feature.xml
- assemblies/pmr-libraries/pom.xml
- assemblies/pmr-libraries/src/main/descriptors/assembly.xml
- kettle-plugins/hadoop-cluster/ui/pom.xml
- kettle-plugins/hadoop-cluster/ui/src/main/java/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/endpoints/CachedFileItemStream.java
- kettle-plugins/hadoop-cluster/ui/src/main/java/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/endpoints/HadoopClusterManager.java
- kettle-plugins/hadoop-cluster/ui/src/test/java/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/endpoints/HadoopClusterManagerTest.java
[BACKLOG-42759]-Upgrading big-data-plugin from Java EE to Jakarta EE
[BACKLOG-42759]: https://hv-eng.atlassian.net/browse/BACKLOG-42759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-42759]-Upgrading big-data-plugin from Java EE to Jakarta EE

- assemblies/legacy-plugin/pom.xml
- assemblies/legacy-plugin/src/main/assembly/descriptors/plugin.xml
- pom.xml
Merge pull request #2634 from smaring/DEVO-10693-10.2.0.0
[DEVO-10639] remove oss license html attachments
(cherry picked from commit d16305536b438f234c238288122a076e772cb3e9)
[DEVO-10639]: https://hv-eng.atlassian.net/browse/DEVO-10639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PPP-5411] License Notice in EE Splash Screen Cherry Picks: Remove oss license html attachments

- pom.xml
- s3-vfs/src/main/java/org/pentaho/s3/vfs/S3FileObject.java
- s3-vfs/src/test/java/org/pentaho/s3/vfs/S3FileObjectTest.java
[SP-6643]-Backport of PPP-5083 - Vulnerable Component: ion java (10.2 Suite)
[SP-6643]: https://hv-eng.atlassian.net/browse/SP-6643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SP-6643]-Backport of PPP-5083 - Vulnerable Component: ion java (10.2 Suite)

- kettle-plugins/hadoop-cluster/ui/src/main/java/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/dialog/wizard/AddDriverDialog.java
- kettle-plugins/hadoop-cluster/ui/src/main/java/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/dialog/wizard/NamedClusterDialog.java
- kettle-plugins/hadoop-cluster/ui/src/main/java/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/dialog/wizard/pages/ClusterSettingsPage.java
- kettle-plugins/hadoop-cluster/ui/src/main/resources/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/dialog/wizard/pages/messages/messages.properties
- kettle-plugins/hadoop-cluster/ui/src/main/resources/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/dialog/wizard/pages/messages/messages_en_US.properties
[BACKLOG-42836] the "Import Cluster" title is missing
[BACKLOG-42837] the "Add Driver" title section needs to match to what is existing
[BACKLOG-42836]: https://hv-eng.atlassian.net/browse/BACKLOG-42836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BACKLOG-42837]: https://hv-eng.atlassian.net/browse/BACKLOG-42837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-42836] the "Import Cluster" title is missing [BACKLOG-42837] the "Add Driver" title section needs to match to what is existing

- assemblies/legacy-plugin/pom.xml
- legacy-amazon/pom.xml
- legacy/pom.xml
- pom.xml
> [SP-6634] Backporting PPP-4780 upgrading libthrift library to avoid security issues

- kettle-plugins/hive/src/main/java/org/pentaho/big/data/kettle/plugins/hive/BaseSimbaDatabaseMeta.java
- kettle-plugins/hive/src/main/java/org/pentaho/big/data/kettle/plugins/hive/Hive2SimbaDatabaseDialect.java
- kettle-plugins/hive/src/main/java/org/pentaho/big/data/kettle/plugins/hive/Hive2SimbaDatabaseMeta.java
- kettle-plugins/hive/src/main/java/org/pentaho/big/data/kettle/plugins/hive/ImpalaSimbaDatabaseDialect.java
- kettle-plugins/hive/src/main/java/org/pentaho/big/data/kettle/plugins/hive/ImpalaSimbaDatabaseMeta.java
- kettle-plugins/hive/src/main/java/org/pentaho/big/data/kettle/plugins/hive/SimbaUrl.java
- kettle-plugins/hive/src/test/java/org/pentaho/big/data/kettle/plugins/hive/BaseSimbaDatabaseMetaTest.java
- kettle-plugins/hive/src/test/java/org/pentaho/big/data/kettle/plugins/hive/Hive2SimbaDatabaseDialectTest.java
- kettle-plugins/hive/src/test/java/org/pentaho/big/data/kettle/plugins/hive/Hive2SimbaDatabaseMetaTest.java
- kettle-plugins/hive/src/test/java/org/pentaho/big/data/kettle/plugins/hive/ImpalaSimbaDatabaseMetaTest.java
- kettle-plugins/hive/src/test/java/org/pentaho/big/data/kettle/plugins/hive/SimbaUrlTest.java
(cherry picked from commit 826e4850e35b06f46641f04365fe5ced94e5993c)
@pentaho/tatooine_dev
> [SP-6661] Backport of PDI-18031 - ODBC access type does not work and should be removed from connection dialogs (10.2 Suite)

- kettle-plugins/pig/src/main/java/org/pentaho/big/data/kettle/plugins/pig/JobEntryPigScriptExecutor.java
https://hv-eng.atlassian.net/browse/PPP-5537
> [PPP-5537] Deprecate the Pig Script Executor Job Entry

- assemblies/features/src/main/feature/feature.xml
- kettle-plugins/hadoop-cluster/pom.xml
- kettle-plugins/hadoop-cluster/ui/pom.xml
- kettle-plugins/hadoop-cluster/ui/src/main/java/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/endpoints/CachedFileItemStream.java
- kettle-plugins/hadoop-cluster/ui/src/main/java/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/endpoints/HadoopClusterManager.java
- kettle-plugins/hadoop-cluster/ui/src/test/java/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/endpoints/HadoopClusterManagerTest.java
- pom.xml
[BACKLOG-43209]-OSGi Assembly Issues
[BACKLOG-43209]: https://hv-eng.atlassian.net/browse/BACKLOG-43209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-43209]-OSGi Assembly Issues

- assemblies/features/pom.xml
[BACKLOG-43874]-Fix JDK21 test pipeline(test1) build failures
[BACKLOG-43874]: https://hv-eng.atlassian.net/browse/BACKLOG-43874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-43874]-Fix JDK21 test pipeline(test1) build failures

- kettle-plugins/hbase-meta/pom.xml
Reference PR: https://github.com/pentaho/big-data-plugin/pull/2776
> [SP-6874] Backport of PPP-5643 - Vulnerable Component: protobuf (deep scan) - Hadoop (10.2 Suite)

- impl/cluster/pom.xml
- impl/cluster/src/main/java/org/pentaho/big/data/impl/cluster/NamedClusterImpl.java
Reverts pentaho/big-data-plugin#2835
> Revert "[BACKLOG-45746] Modified getShimIdentifier to return active shim conf…"

- assemblies/pmr-libraries/src/main/resources/classes/log4j2.xml
> chore[PPP-5981]: add monitorInterval to log4j2 configuration

- impl/cluster/src/main/java/org/pentaho/big/data/impl/cluster/NamedClusterImpl.java
> fix[PPP-5982]: add proper initialization to XML parser
