src/org/pentaho/di/ui/job/entries/hadoopjobexecutor/JobEntryHadoopJobExecutorController.java
Dialog failed to open if jar could not be read or if driver class is not found.
E.g. if jar path is parameterized
http://jira.pentaho.com/browse/PDI-13380
=> [PDI-13380]Allow Hadoop Job Executor dialog to open if Driver Class is not found

src/org/pentaho/di/ui/job/entries/hadoopjobexecutor/JobEntryHadoopJobExecutorController.java
Allow edits to cluster infomation via Named Cluster Edit dialog
Also allow saving job entry without any existing named clusters (using only built-in properties)
=> [PDI-13380] Allow configuring Hadoop Job Executor clusters without names

ivy.xml
replace cdh52 shim by the new cdh53 one
should be merged after the following two have been merged:
https://github.com/pentaho/pentaho-big-data-ee/pull/57
https://github.com/pentaho/pentaho-hadoop-shims/pull/207
@mattyb149 @brosander could you please review/merge?
@lgrill-pentaho keeping you in the loop since there are some items to be done for build process for new shim
@mbradbury2014 FYI :)
=> [BAD-176] - Compile CDH 5.3 Shim

src/org/pentaho/di/ui/vfs/hadoopvfsfilechooserdialog/HadoopVfsFileChooserDialog.java
VFS file browser is not working with variable values after "Named Cluster" functionality was implemented
=> [BACKLOG-2648] VFS file browser is not working with variable values

build.properties, ivy.xml
* Updated jets3t version
* included required httpclient dependencies
* Also include emr32 shim
Related to https://github.com/pentaho/pentaho-s3-vfs/pull/4 and should be merged after https://github.com/pentaho/pentaho-hadoop-shims/pull/231
=> [BAD-220] - Extend BD functionality to S3

src/org/pentaho/di/trans/steps/hbaserowdecoder/HBaseRowDecoderMeta.java, test-src/org/pentaho/di/trans/steps/hbaserowdecoder/HBaseRowDecoderMetaTest.java
There is a situation when  the step contains the mapping without any name.
The cause of this issue is a such case.
In this case we get no one output fields in RowMeta for this step (method HBaseRowDecoderMeta.getFields())
And then during verification TransMeta (method JobEntryHadoopTransJobExecutor.verifyTransMeta()) we throw KettleException on checking meta of Hadoop Output step.
So the fix is to allow getting fields from mapping without name (so-called "local" mapping).
Also added a couple of unit tests.
=> [PDI-13675]: Saving HBase mapping in HBaseRowDecoder step causes error

src/org/pentaho/di/job/ArgumentWrapper.java, src/org/pentaho/di/job/CommandLineArgument.java, src/org/pentaho/di/job/entries/sqoop/SqoopConfig.java, src/org/pentaho/di/job/entries/sqoop/SqoopExportConfig.java, src/org/pentaho/di/job/entries/sqoop/SqoopImportConfig.java, src/org/pentaho/di/job/entries/sqoop/SqoopUtils.java, src/org/pentaho/di/ui/job/entries/sqoop/AbstractSqoopJobEntryController.java, test-src/org/pentaho/di/job/entries/sqoop/ArgumentWrapperTest.java, test-src/org/pentaho/di/job/entries/sqoop/SqoopConfigTest.java, test-src/org/pentaho/di/job/entries/sqoop/SqoopImportConfigTest.java, test-src/org/pentaho/di/job/entries/sqoop/SqoopUtilsTest.java, test-src/org/pentaho/di/trans/steps/hadoopexit/HadoopExitMetaTest.java
1. Added a number of new parameters previously not supported by Kettle
2. Parameters were regrouped (those common for both import and export were moved to SqoopConfig)
3. Added support for single-dash params (Hadoop generic arguments for sqoop)
4. Added support for ordering parameters:
- to provide order on UI
- to make sure Hadoop single-dashed params are always specified before Sqoop specific ones
5. unit tests
6. check style
7. license header (copyright year - 2015)
@mattyb149 @brosander please ...
=> [PDI-12715] - Improvement: Sqoop Job Entries

src/org/pentaho/di/job/entries/sqoop/AbstractSqoopJobEntry.java, test-src/org/pentaho/di/job/entries/sqoop/AbstractSqoopJobEntryTest.java
1. use getConnect() instead of getConnectFromAdvanced()
2. Sort out logic dependent on UI mode
3. Split configure() method to configureDatabase() and configureShim()
4. Unit test added
5. CheckStyle fixes
@mattyb149 @brosander could you please review
=> [BAD-131] - Sqoop job fails when running from Advanced mode with "argument -connect is missing" error

samples/jobs/hadoop/Pentaho MapReduce - weblogs.kjb, samples/jobs/hadoop/Pentaho MapReduce - wordcount.kjb, test-src/org/pentaho/hadoop/mapreduce/test/PentahoMapReduceIntegrationTest.java
* Deleted unit test. Was discussed in http://jira.pentaho.com/browse/PDI-12749 and resulted to forbid using "GroupBy" step in singleThreaded mode.
=> [PDI-12749][TEST] - PMR: Bad Results in Group-By if an entire key is filtered earlier

src/org/pentaho/di/job/entries/sqoop/AbstractSqoopJobEntry.java, src/org/pentaho/di/job/entries/sqoop/SqoopConfig.java, src/org/pentaho/di/job/entries/sqoop/SqoopUtils.java, src/org/pentaho/di/job/entries/sqoop/messages/messages_en_US.properties, src/org/pentaho/di/ui/job/entries/sqoop/AbstractSqoopJobEntryController.java, test-src/org/pentaho/di/job/entries/sqoop/AbstractSqoopJobEntryTest.java
the cause of the issue it that Spoon.getInstance().getMetaStore() is used what would apparently not work in environment other than Spoon (DI/BA Server, PMR etc.)
Alternative approach has been implemented similar to user BigData JobEntries:
store NamedCluster within the Job and use this if repository (MetaStore) is not available.
The only drawback: the Sqoop Entries stored after the NamedCluster had been incorporated should be re-saved in Spoon.
@mdamour1976 @e-cuellar @mattyb149 @brosander @deinspanjer please - take a look
=> [BACKLOG-3242] - Sqoop Import/Export jobs are failing on DI Server

src/org/pentaho/di/ui/trans/steps/hadoopfileinput/HadoopFileInputDialog.java
1. make creds be saved along with S3 URL (the same as for BACKLOG-3474)
2. do not cut out S3 scheme while filling in input-file-grid
@kcruzada @e-cuellar
=> [BACKLOG-3560] - REG:Hadoop File Input fails to read from S3 storage

src/org/pentaho/di/ui/trans/steps/hadoopfileinput/HadoopFileInputDialog.java
forward-port of https://github.com/pentaho/big-data-plugin/pull/394 to master
1. make creds be saved along with S3 URL (the same as for BACKLOG-3474)
2. do not cut out S3 scheme while filling in input-file-grid
@kcruzada @e-cuellar
=> [BACKLOG-3560] - REG:Hadoop File Input fails to read from S3 storage - MASTER

samples/jobs/hadoop/Pentaho MapReduce - weblogs.kjb, samples/jobs/hadoop/Pentaho MapReduce - wordcount.kjb, test-src/org/pentaho/hadoop/mapreduce/test/PentahoMapReduceIntegrationTest.java
* Deleted unit test. Was discussed in http://jira.pentaho.com/browse/PDI-12749 and resulted to forbid using "GroupBy" step in singleThreaded mode.
=> [SP-1830][TEST] - PMR: Bad Results in Group-By if an entire key is filtered earlier

legacy/src/main/java/org/pentaho/di/trans/steps/hbaseinput/HBaseInput.java, legacy/src/main/java/org/pentaho/di/trans/steps/hbaseinput/HBaseInputDialog.java, legacy/src/main/java/org/pentaho/di/trans/steps/hbaseinput/HBaseInputMeta.java, legacy/src/main/java/org/pentaho/di/trans/steps/hbaseoutput/HBaseOutput.java, legacy/src/main/java/org/pentaho/di/trans/steps/hbaseoutput/HBaseOutputDialog.java, legacy/src/main/java/org/pentaho/hbase/mapping/MappingAdmin.java, legacy/src/main/java/org/pentaho/hbase/mapping/MappingEditor.java, legacy/src/main/resources/org/pentaho/di/trans/steps/hbaseinput/messages/messages_en_US.properties, legacy/src/main/resources/org/pentaho/di/trans/steps/hbaseoutput/messages/messages_en_US.properties
The way how HBase 1.0 API has been implemented requires explicitly close HBaseConnection.
In order to do this the HBase shim API is changed and new close() method is exposed.
This commit contains changes done on UI and step layers to accomplish closing connections.
@mattyb149 @brosander do you mind to review?
=> [BAD-312] - Support for HBase 1.0

legacy/pom.xml, legacy/src/main/java/org/pentaho/hadoop/PluginPropertiesUtil.java, legacy/src/test/java/org/pentaho/hadoop/PluginPropertiesUtilTest.java
The @VERSION@ placeholder used to be filled in on build time with real release version.
After mavinization the substtution has gone. It's very hard to implement the same build step with maven.
Looking through sources it was figured out that the build time replacement is not needed at all.
The version is read from version.properties file what is quite reliable.
The PluginPropertiesUtils class was modified to return the version read from the properties file.
Additional constructor was added to allow reading from another location (primaraly for testing purpose)
remove comments about ant-replacements
check style
=> [BACKLOG-4688] - PMR installation HDFS directory path contains @VERSION@ string instead of actual value

legacy/src/main/java/org/pentaho/di/job/entries/hadooptransjobexecutor/JobEntryHadoopTransJobExecutor.java
Store log file in user's temp directory, instead of in the current working directory in case the user does not have write permissions to the folder
=> [PDI-13426] - Fix KettleFileAppender error

kettle-plugins/common/ui/src/main/java/org/pentaho/big/data/plugins/common/ui/ClusterTestDialog.java, kettle-plugins/common/ui/src/main/java/org/pentaho/big/data/plugins/common/ui/ClusterTestResultsDialog.java, kettle-plugins/common/ui/src/main/resources/org/pentaho/big/data/plugins/common/ui/messages/messages_en_US.properties
- Added help button and correct URLs for troubleshooting guide
- Fixed widget background (all inherit from parent)
- Restored fonts and image sizes to default
- Fixed margin/spacing between test result widgets
=> [BACKLOG-4505] UX Rework for Cluster Test dialog

api/cluster/pom.xml, api/hdfs/pom.xml, api/initializer/pom.xml, api/pig/pom.xml, api/runtimeTest/pom.xml, assemblies/features/pom.xml, assemblies/legacy-plugin/pom.xml, assemblies/pmr-libraries/pom.xml, assemblies/samples/pom.xml, assemblies/standalone/pom.xml, impl/cluster/pom.xml, impl/clusterTests/pom.xml, impl/shim/common/pom.xml, impl/shim/hdfs/pom.xml, impl/shim/initializer/pom.xml, impl/shim/pig/pom.xml, impl/shim/shimTests/pom.xml, impl/vfs/hdfs/pom.xml, kettle-plugins/common/namedClusterBridge/pom.xml, kettle-plugins/common/ui/pom.xml, kettle-plugins/pig/pom.xml, legacy/pom.xml, pom.xml
knocks about 40 mins off the unit test and sonar publishing  ... tested here http://cerberus.pentaho.com/job/6.0-engops-testing/job/big-data-plugin-features/4/
@lgrill-pentaho
=> [ENGOPS-1367] updated ce parent pom for site phase nullifcation of parents

legacy/src/main/java/org/pentaho/di/job/entries/sqoop/SqoopUtils.java, legacy/src/test/java/org/pentaho/di/job/entries/sqoop/SqoopUtilsTest.java
Remove value quoting and escaping for the case when sqoop is run from grid mode.
=> [BACKLOG-4928] - additional fix

impl/shim/shimTests/src/main/java/org/pentaho/big/data/impl/shim/tests/TestShimLoad.java, kettle-plugins/common/ui/src/main/java/org/pentaho/big/data/plugins/common/ui/ClusterTestDialog.java, kettle-plugins/common/ui/src/main/java/org/pentaho/big/data/plugins/common/ui/ClusterTestResultsDialog.java, kettle-plugins/common/ui/src/main/resources/org/pentaho/big/data/plugins/common/ui/messages/messages_en_US.properties
The change in TestShimLoad is needed as the shim type is not displayed when you test a cluster without having loaded a shim (which is the immediate use case for users). The rest correspond to the UX findings in the case/mockups.
=> [BACKLOG-5026] Final fixes and UX adjustments for cluster test dialogs

legacy/src/main/java/org/pentaho/di/trans/steps/hbaseinput/HBaseInputData.java
the issue was caused by changes for new HBase filters.
in order to implement key filtering the corresponding column was added to the alias-map
however, as soon as the "key" is a synthetic column it was not available by the alias.
Solution is to skip the "key" alias resolution when looping through columns' map.
@mattyb149 @brosander @dkincade
=> [BACKLOG-5230] - REGRESSION: HBase Input fails with "null key value" error message

kettle-plugins/common/ui/src/main/java/org/pentaho/big/data/plugins/common/ui/ClusterTestDialog.java
Removed computeSize() and pack(), which caused the progress bar not to show up on Windows
=> [BACKLOG-5026] Windows does not honor pack() for progress bar

legacy/src/main/java/org/pentaho/di/ui/trans/steps/hadoopfileoutput/HadoopFileOutputDialog.java, legacy/src/test/java/org/pentaho/di/ui/trans/steps/hadoopfileoutput/HadoopFileOutputDialogTest.java
Only removing root prefix if there is one
=> [BAD-347] - Variable fix in HadoopFileOutputStep

legacy/src/main/java/org/pentaho/hbase/mapping/MappingAdmin.java, legacy/src/test/java/org/pentaho/hbase/mapping/MappingAdminTest.java
By default key is small cased in usual mapping and uppercased in tupple
* Added test
=> [BACKLOG-5262] - REG: HBase transformation failed due to error in reading table mappings

assemblies/features/src/main/resources/features.xml
feature.big-data commons-ui depends on runtime test
feature
=> [BACKLOG-5260] - Adding the RuntimeTest to the main testless big-data

impl/shim/common/src/main/java/com/pentaho/big/data/bundles/impl/shim/common/ShimBridgingClassloader.java
In the case that the returned class was loaded from the system classloader, give parent classloader a chance to load a different one
=> [BACKLOG-5265] - Boot delegation workaround

impl/clusterTests/src/test/java/org/pentaho/big/data/impl/cluster/tests/hdfs/PingFileSystemEntryPointTestTest.java, impl/clusterTests/src/test/java/org/pentaho/big/data/impl/cluster/tests/mr/PingJobTrackerTestTest.java, impl/clusterTests/src/test/java/org/pentaho/big/data/impl/cluster/tests/oozie/PingOozieHostTestTest.java, impl/clusterTests/src/test/java/org/pentaho/big/data/impl/cluster/tests/zookeeper/PingZookeeperEnsembleTestTest.java, impl/shim/shimTests/src/main/java/org/pentaho/big/data/impl/shim/tests/TestShimConfig.java, impl/shim/shimTests/src/test/java/org/pentaho/big/data/impl/shim/tests/TestShimConfigTest.java, legacy/src/test/java/org/pentaho/di/job/entries/hadooptransjobexecutor/JobEntryHadoopTransJobExecutorTest.java
@dkincade 
These are the cherry-picked commits from master that get the tests back to blue.  
All are test changes except for TestShimConfig's change which enhances the error message in the case that a shim cannot load.  It must have gotten mixed into the test commit but is good to have (if the new call fails, the next line would have had the same failure when trying to load the shim and then you at least know what shim it was trying to load)
/cc @mattyb149
=> 6.0 test fixes

legacy/src/main/resources/org/pentaho/di/ui/job/entries/oozie/xul/OozieJobExecutor.xul
- in 5.4, UI images were moved to kettle-ui.jar; fix the paths of buttons to make the visible
@mattyb149, @brosander, review it please
=> [PDI-14192] - PDI, "Oozie Job Executor" step: new properties can't be added manually

src/org/pentaho/di/ui/job/entries/oozie/xul/OozieJobExecutor.xul
- in 5.4, UI images were moved to kettle-ui.jar; fix the paths of buttons to make the visible
@mattyb149, @brosander, review it please. This is a backport of https://github.com/pentaho/big-data-plugin/pull/547
=> [SP-2065] - Backport of PDI-14192 - PDI, "Oozie Job Executor" step: new properties can't be added manually (5.4 Suite)

legacy/src/main/resources/org/pentaho/di/ui/job/entries/oozie/xul/OozieJobExecutor.xul
- in 5.4, UI images were moved to kettle-ui.jar; fix the paths of buttons to make the visible
(cherry picked from commit a8f1d43)
@mattyb149, @brosander, review it please. This is a backport of https://github.com/pentaho/big-data-plugin/pull/547
=> [SP-2202] - Backport of PDI-14192 - PDI, "Oozie Job Executor" step: new properties can't be added manually (6.0 Suite)

legacy/src/main/java/org/pentaho/di/ui/job/entries/hadoopcopyfiles/JobEntryHadoopCopyFilesDialog.java, legacy/src/main/java/org/pentaho/di/ui/trans/steps/hadoopfileinput/HadoopFileInputDialog.java, legacy/src/main/java/org/pentaho/di/ui/trans/steps/hadoopfileoutput/HadoopFileOutputDialog.java
The problem was caused with the case when the user types any nonsensical sequence of symbols in Path filed.
In such case defaultInitialFile=null and we have NPE.
Just Fixed NPEs without any changes in the logic of working on widgetSelected.
No unit tests have been added because these changes  are in UI components.
=> [BAD-341]: Hadoop File Input: NPE appears after click on "Browse" button

kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileOutputDialog.java
It's according the first point of the http://jira.pentaho.com/browse/BAD-297 :
1. In tab File, when the "Accept filename from field" is selected, the "Extension" field is greyed out indicating it is not used. However it still gets used.
So it was decided to enable for editing extension field (as it was and still is being used) to not break somebody`s existing ktrs.
=> [BAD-297] - Hadoop file output fails append to file

api/mapreduce/src/main/java/org/pentaho/bigdata/api/mapreduce/MapReduceJobBuilder.java, impl/shim/mapreduce/src/main/java/org/pentaho/big/data/impl/shim/mapreduce/MapReduceJobBuilderImpl.java, impl/shim/mapreduce/src/test/java/org/pentaho/big/data/impl/shim/mapreduce/MapReduceJobBuilderImplTest.java, kettle-plugins/mapreduce/src/main/java/org/pentaho/big/data/kettle/plugins/mapreduce/JobEntryHadoopJobExecutor.java
The issue was introduced with the commit: https://github.com/pentaho/big-data-plugin/commit/ceb855aa6b215b43a82f9b5c353527a29b83d3d7
On the line: https://github.com/pentaho/big-data-plugin/blob/ceb855aa6b215b43a82f9b5c353527a29b83d3d7/impl/shim/mapreduce/src/main/java/org/pentaho/big/data/impl/shim/mapreduce/MapReduceJobBuilderImpl.java#L193
we set into hadoop config.jar the path string after processing in resolveJarUrl method.
For the case when jarUrl has a space character (e.g. D:\PENT\ISSUES\6.1\BACKLOG-5885\Folder Test\pentaho-mapreduce-sample_MR2.jar),
we will set config.jar=file:/D:/PENT/ISSUES/6.1/BACKLOG-5885/Folder%20Test/pentaho-mapreduce-sample_MR2.jar with already encoded space.
Hadoop during processing jars (org.apache.hadoop.mapreduce.JobSubmitter.copyAndConfigureFiles(Job …
=> [BACKLOG-5885]: REG: Hadoop Job Executor: Error in case "Jar" field contains spaces in path

kettle-plugins/mapreduce/src/main/java/org/pentaho/big/data/kettle/plugins/mapreduce/JobEntryHadoopJobExecutorDialog.java
This issue has happened just because of missed Null check for NamedCluster in the fix https://github.com/pentaho/big-data-plugin/pull/588
So the fix is just to add null check.
No unit test because the change is on UI (in Dialog).
=> [BACKLOG-6065]: PDI: "Hadoop Job Executor" step can't be changed in a new job.

kettle-plugins/mapreduce/src/main/java/org/pentaho/big/data/kettle/plugins/mapreduce/entry/NamedClusterLoadSaveUtil.java, kettle-plugins/mapreduce/src/test/java/org/pentaho/big/data/kettle/plugins/mapreduce/entry/NamedClusterLoadSaveUtilTest.java
Just created step has NamedCluster=null, so at attempt to call any method on it we get an usual NPE.
Exactly this one occurs at calling getXML method (see in NamedClusterLoadSaveUtil.getXmlNamedCluster)on saving.
And also for saveRep method (see in NamedClusterLoadSaveUtil.saveNamedClusterRep).
The fix is just to add Null check +a couple of unit tests to cover these cases.
=> [BACKLOG-6064]: PDI: New job that contain Hadoop Job Executor step can't be saved.

impl/shim/oozie/pom.xml
Fixed invalid parent pom reference.
@lgrill-pentaho
=> [CLEANUP]  pom cleanup

impl/shim/hdfs/src/main/java/com/pentaho/big/data/bundles/impl/shim/hdfs/HadoopFileSystemCallable.java, impl/shim/hdfs/src/main/java/com/pentaho/big/data/bundles/impl/shim/hdfs/HadoopFileSystemFactoryImpl.java, impl/shim/hdfs/src/main/java/com/pentaho/big/data/bundles/impl/shim/hdfs/HadoopFileSystemImpl.java, impl/shim/hdfs/src/test/java/com/pentaho/big/data/bundles/impl/shim/hdfs/HadoopFileSystemImplTest.java
Change to access FileSystem via shim in order to have up-to-date kerberos ticket.
=> [PDI-14443] - Hadoop Kerberos security ticket not renewed after expire

assemblies/legacy-plugin/pom.xml, pom.xml
Updated poms with the proper shim list:
CDH 5.5
HDP 2.3
EMR 3.10
MapR 4.1
=> [BAD-475]: Need to update Big Data Plugin for Pentaho 6.1 with proper Shim List

kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/HBaseConnectionException.java, kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/mapping/MappingEditor.java, kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/mapping/MappingUtils.java, kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/rowdecoder/HBaseRowDecoderDialog.java, kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/rowdecoder/HBaseRowDecoderMeta.java, kettle-plugins/hbase/src/main/resources/OSGI-INF/blueprint/blueprint.xml, kettle-plugins/hbase/src/test/java/org/pentaho/big/data/kettle/plugins/hbase/mapping/MappingUtilsTest.java
Added saving selected NamedCluster, loading already saved values;
Added unit tests.
Also fixed the incorrect scope for HBaseRowDecoderMeta (please see /pentaho-big-data-kettle-plugins-hbase/src/main/resources/OSGI-INF/blueprint/blueprint.xml)
It should be: scope="prototype".
=> [BAD-482]: HBase Row Decoder: selected Hadoop cluster drop-down value is not saving

impl/shim/hbase/src/main/java/com/pentaho/big/data/bundles/impl/shim/hbase/HBaseServiceImpl.java, impl/shim/hbase/src/test/java/com/pentaho/big/data/bundles/impl/shim/hbase/HBaseServiceImplTest.java, kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/mapping/MappingEditor.java, kettle-plugins/hbase/src/main/resources/org/pentaho/big/data/kettle/plugins/hbase/mapping/messages/messages_en_US.properties
There are a fix of NPE and unit test on it.
Also added checks for the cases when user is trying to save/delete Mapping into HBase but there is no any selected named cluster on MappingEditor. Changes are only on UI so no unit tests for it.
=> [BACKLOG-6873]: Regression: NPE appears after clicking OK button if Hadoop Cluster is not chosen in "HBase Row Decoder" step

impl/shim/hbase/src/main/java/com/pentaho/big/data/bundles/impl/shim/hbase/HBaseConnectionWrapper.java, impl/shim/hbase/src/test/java/com/pentaho/big/data/bundles/impl/shim/hbase/HBaseConnectionWrapperTest.java
* Added ObtainAuthTokenForJob method delegation
=> [BAD-261] - PentahoTableInputFormat does not work on secured Hadoop cluster

kettle-plugins/common/ui/src/main/java/org/pentaho/big/data/plugins/common/ui/ClusterTestDialog.java
Stick right side of progress bar to the right side of the "Hadoop cluster test" dialog.
=> [BACKLOG-4505] Allow user to Test Hadoop Cluster Configuration

kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileInputDialog.java
Fixed like in HadoopFileOutputDialog. No unit test has been added because the change is only on UI component.
=> [BACKLOG-7925]: Spoon: Transformation becomes "modified" state when user close "Hadoop File Input" step's dialog using "Close" button.

kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileOutputDialog.java
Fixed like in HadoopFileInputDialog. No unit test has been added because the change is on UI component.
=> [BACKLOG-7927]: Spoon: Transformation doesn't become "modified" state when user close "Hadoop File Output" step's dialog using "OK" button.

assemblies/pmr-libraries/pom.xml, assemblies/pmr-libraries/src/main/descriptors/assembly.xml
Replace antlr-2.7.7 with antlr-3.4-complete which contains antlr-2.7.7.
To build pentaho-big-data-assemblies-pmr-libraries it previously needs to build:
- pentaho-reporting-engine-classic-core as it was changed to use antlr-3.4-complete (https://github.com/pentaho/pentaho-reporting/pull/790);
- pentaho-kettle-engine as it uses pentaho-reporting-engine-classic-core;
- pentaho-platform as it has dependency on antlr-3.4-complete, pentaho-kettle-engine, pentaho-reporting-engine-classic-core (https://github.com/pentaho/pentaho-platform/pull/2946).
=> [BACKLOG-8389] - Upgrade antlr to version 3.4 across Pentaho product suite - changes for pentaho big-data-plugin repository

impl/shim/hive/src/main/java/com/pentaho/big/data/bundles/impl/shim/hive/ShimDriverLoader.java, impl/shim/hive/src/main/java/com/pentaho/big/data/bundles/impl/shim/hive/SparkSimbaDriver.java, kettle-plugins/hive/pom.xml, kettle-plugins/hive/src/main/java/org/apache/hadoop/hive/jdbc/HiveDriver.java, kettle-plugins/hive/src/main/java/org/apache/hive/jdbc/HiveDriver.java, kettle-plugins/hive/src/main/java/org/apache/hive/jdbc/HiveSimbaDriver.java, kettle-plugins/hive/src/main/java/org/apache/hive/jdbc/ImpalaSimbaDriver.java, kettle-plugins/hive/src/main/java/org/apache/hive/jdbc/SparkSqlSimbaDriver.java, kettle-plugins/hive/src/main/java/org/pentaho/big/data/kettle/plugins/hive/BaseSimbaDatabaseMeta.java, kettle-plugins/hive/src/main/java/org/pentaho/big/data/kettle/plugins/hive/DummyDriver.java, kettle-plugins/hive/src/main/java/org/pentaho/big/data/kettle/plugins/hive/Hive2SimbaDatabaseMeta.java, kettle-plugins/hive/src/main/java/org/pentaho/big/data/kettle/plugins/hive/ImpalaSimbaDatabaseMeta.java, kettle-plugins/hive/src/main/java/org/pentaho/big/data/kettle/plugins/hive/SparkSimbaDatabaseMeta.java, kettle-plugins/hive/src/main/resources/OSGI-INF/blueprint/blueprint.xml, kettle-plugins/hive/src/test/java/org/pentaho/big/data/kettle/plugins/hive/BaseSimbaDatabaseMetaTest.java, kettle-plugins/hive/src/test/java/org/pentaho/big/data/kettle/plugins/hive/Hive2SimbaDatabaseDialectTest.java, kettle-plugins/hive/src/test/java/org/pentaho/big/data/kettle/plugins/hive/Hive2SimbaDatabaseMetaTest.java, kettle-plugins/hive/src/test/java/org/pentaho/big/data/kettle/plugins/hive/ImpalaSimbaDatabaseMetaTest.java, kettle-plugins/hive/src/test/java/org/pentaho/big/data/kettle/plugins/hive/SparkSimbaDatabaseMetaTest.java
Changes include a new DatabaseMeta for Spark, plus a wrapper
implementation in impl-shim.  Also refactored the other Simba
DatabaseMetas to eliminate code duplication.
http://jira.pentaho.com/browse/BACKLOG-8748
=> [BACKLOG-8748] Support for SparkSQL

kettle-plugins/hive/src/main/java/org/pentaho/big/data/kettle/plugins/hive/SparkSimbaDatabaseMeta.java, kettle-plugins/hive/src/test/java/org/pentaho/big/data/kettle/plugins/hive/SparkSimbaDatabaseMetaTest.java
Throwing an UnsupportedOperationException doesn't play
nicely with the "Feature List" option in the database dialog.
Returning empty strings for unsupported SQL instead.
http://jira.pentaho.com/browse/BACKLOG-8856
=> [BACKLOG-8856] Support for SparkSQL in EE.

assemblies/pmr-libraries/pom.xml, assemblies/pmr-libraries/src/main/descriptors/assembly.xml
Replace antlr-2.7.7 with antlr-complete-3.5.2 which contains antlr-2.7.7.
To build pentaho-big-data-assemblies-pmr-libraries it previously needs to build:
- pentaho-reporting-engine-classic-core as it was changed to use antlr-complete-3.5.2 (pentaho/pentaho-reporting#792);
- pentaho-kettle-engine (pentaho/pentaho-kettle#2665) as it uses pentaho-reporting-engine-classic-core;
- pentaho-platform  (pentaho/pentaho-platform#2964) as it has dependency on antlr-complete-3.5.2, pentaho-kettle-engine, pentaho-reporting-engine-classic-core.
=> [BACKLOG-8389] - Upgrade antlr to version 3.5.2 across Pentaho product suite - changes for pentaho big-data-plugin repository

assemblies/pmr-libraries/pom.xml, assemblies/pmr-libraries/src/main/descriptors/assembly.xml
The problem is:
During configuration the map runner is creating a new transformation.
The process creation of the transformation involves calling at org.pentaho.di.core.KettleEnvironment.init().
And then we are trying to register plugins and types: PluginRegistry.init(), BasePluginType.registerPluginJars();
We use scannotation to find all annotated classes in jars but scannotation uses javassist for this.
So if any of classes in jar contains Java 8 lambdas, we will have this issue.
This occurs because Java 8 lambdas uses invokedynamic to generate code in runtime but javassist 3.12.1.GA doesn't support it.
With the fix https://issues.jboss.org/browse/JASSIST-174 javassist has got support for the CONSTANT_InvokeDynamic=18
So the fix is just to upgrade javassist to the latest release …
=> [BACKLOG-9186]: Exception `invalid constant type` appears in PMR mapper logs on cluster

assemblies/pmr-libraries/pom.xml
The fix is needed due to using java 1.8, and incompatibility of asm old version (is used by jersey) reading new java 1.8 features 
The following scope of repositories is upgraded(except webdetails): The list is sorted in the order of build team runs
https://github.com/pentaho/pentaho-reporting
https://github.com/pentaho/mondrian
https://github.com/pentaho/pentaho-kettle
https://github.com/pentaho/pentaho-mondrianschemaworkbench-plugins
https://github.com/pentaho/pentaho-platform
https://github.com/webdetails/cpf
https://github.com/pentaho/pentaho-metaverse
https://github.com/pentaho/pdi-platform-utils-plugin
https://github.com/pentaho/pentaho-data-profiling
https://github.com/pentaho/data-access
https://github.com/pentaho/big-data-plugin
https://github.com/pentaho/pentaho-data-refinery …
=> [BACKLOG-8388] Upgrade Jersey to 1.19.1 across the suite for Java 8 compatibility

kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/output/HBaseOutputMeta.java, kettle-plugins/hbase/src/test/java/org/pentaho/big/data/kettle/plugins/hbase/output/HBaseOutputMetaTest.java
[SP-2816] Backport of PDI-15391 - NPE when reopening & editing transformations with HBase Output step in DI repository (6.1 Suite).
Added missing assignment of this.namedCluster in .readRep.
=> [SP-2816] Backport of PDI-15391 - NPE when reopening & editing transformations with HBase Output step in DI repository (6.1 Suite).

impl/shim/hbase/src/main/java/com/pentaho/big/data/bundles/impl/shim/hbase/table/HBaseTableImpl.java, impl/shim/hbase/src/main/java/com/pentaho/big/data/bundles/impl/shim/hbase/table/ResultScannerBuilderImpl.java, impl/shim/hbase/src/test/java/com/pentaho/big/data/bundles/impl/shim/hbase/table/ResultScannerBuilderImplTest.java
- Fix https://github.com/pentaho/big-data-plugin/pull/624/files was backported.
=> [SP-2806] Backport of BAD-487 - HBase cache size not set for hbase input (6.1 Suite)

impl/vfs/hdfs/src/main/java/org/pentaho/big/data/impl/vfs/hdfs/HDFSFileNameParser.java, impl/vfs/hdfs/src/test/java/org/pentaho/big/data/impl/vfs/hdfs/HDFSFileNameParserTest.java
fixed with overriding in HDFSFileNameParser method parseUri which in comparison to URLFileNameParser doesn't make host lower cased
=> [PDI-15565] PDI is not able to find Hadoop HA cluster name when it's defined in UPPERCASE

kettle-plugins/hive/src/main/java/org/pentaho/big/data/kettle/plugins/hive/SparkSimbaDatabaseMeta.java, kettle-plugins/hive/src/test/java/org/pentaho/big/data/kettle/plugins/hive/SparkSimbaDatabaseMetaTest.java
This will allow preview from the "Explore" dialog to limit results on
the server.
=> [BACKLOG-9978] Adding support for LIMIT to the SparkSimbaDatabaseMeta.

api/jdbc/src/main/java/org/pentaho/big/data/api/jdbc/impl/ClusterInitializingDriver.java, api/jdbc/src/test/java/org/pentaho/big/data/api/jdbc/impl/ClusterInitializingDriverTest.java
Removing some logic which determined the named cluster to
associated with a jdbc connection by looking at the Url.
That association is currently unnecessary since we are not yet
supporting jdbc connections within named clusters.  The logic
was creating circularity during init:  the ClusterInitializingDriver
could be called when JackRabbit makes a repository connection.
But determining named cluster in turn requires a Repository.
We'll need to rethink this design when we have functional requirements
to associate named clusters and JDBC connections.
=> [BACKLOG-10984] ClusterInitiazation during driver load causes sys init to hang

assemblies/pmr-libraries/pom.xml
This is part of a set of pull requests for the spring 4 upgrade work:
https://github.com/pentaho/pentaho-platform/pull/3104
https://github.com/webdetails/cpf/pull/98
https://github.com/webdetails/cdf/pull/870
https://github.com/webdetails/cda/pull/209
https://github.com/webdetails/cde/pull/718
https://github.com/pentaho/data-access/pull/783
https://github.com/pentaho/pentaho-reporting/pull/828
https://github.com/pentaho/pentaho-platform-plugin-reporting/pull/436
https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/842
https://github.com/pentaho/marketplace/pull/115
https://github.com/pentaho/big-data-plugin/pull/739
https://github.com/pentaho/pentaho-platform-ee/pull/972
https://github.com/pentaho/pentaho-platform-plugin-interactive-reporting/pull/477 …
=> [BACKLOG-10623] Upgrades the spring framework and security version

api/jdbc/src/main/java/org/pentaho/big/data/api/jdbc/impl/ClusterInitializingDriver.java, api/jdbc/src/test/java/org/pentaho/big/data/api/jdbc/impl/ClusterInitializingDriverTest.java
@mkambol,  @bmorrise , @mdamour1976  please review.
@mkambol  I tried to find a way to get information about acceptance criteria from big data drivers. But I could find a right way. I can suggest to hardcode these drivers somewhere else however it still be a hardcoded list of url patterns to match. Let me know if you have any suggestions.
=> [BACKLOG-6781] - 'Hadoop Distribution' dialog pop up when not using hadoop

assemblies/pmr-libraries/pom.xml
@pentaho/rogueone Upgrade to commons-fileupload-1.3.2. Please review.
=> [BACKLOG-11322] Resolve Security Vulnerabilities around Apache Common File Upload

assemblies/pmr-libraries/pom.xml
- eigenbase-xom dependency is updated to 1.3.5
@mbatchelor, @pamval, @lucboudreau, @mkambol, could you please take a look?
=> [PPP-3506] - XXE Security Vulnerability in xml parsers

assemblies/pmr-libraries/pom.xml, assemblies/pmr-libraries/src/main/descriptors/assembly.xml
Removing legacy ESAPI encoder from projects and replacing it by org.owasp.encoder
=> PDI-15515 - Removing legacy ESAPI encoder from projects

assemblies/legacy-plugin/pom.xml, pom.xml
according to the list of supported shims from here https://help.pentaho.com/Documentation/7.0/0D0/160/000
The following shims are included in the Pentaho Big Data plugin for Pentaho Version 7.0: Cloudera Distribution for Hadoop 5.8, Amazon EMR 4.1, Hortonworks 2.4, and MapR 5.1.  Other supported shims can be downloaded from the Pentaho Support Portal.
=> [OTHER] - fix list of shims in ce for 7.0

assemblies/legacy-plugin/pom.xml, pom.xml
according to the list of supported shims from here https://help.pentaho.com/Documentation/7.0/0D0/160/000
The following shims are included in the Pentaho Big Data plugin for Pentaho Version 7.0: Cloudera Distribution for Hadoop 5.8, Amazon EMR 4.1, Hortonworks 2.4, and MapR 5.1. Other supported shims can be downloaded from the Pentaho Support Portal.
=> [OTHER] - fix list of shims in ce for 7.0.0.1 

assemblies/legacy-plugin/pom.xml, pom.xml
Updated:
- assemblies/legacy-plugin/pom.xml (removed mapr410);
- pom.xml (removed mapr410).
=> [BACKLOG-13629]-Clean up SHIM projects in github - remove old versions

kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/job/JobEntryHadoopCopyFilesDialog.java
The problem conserns only ui dialog and caused by a passing null as a parameter to a method TableItem#setText which causes npe
=> PDI-14145 - Hadoop Copy Files - unable to edit step with a Destination Environment but without a Destination File/Folder path

assemblies/legacy-plugin/pom.xml, assemblies/legacy-plugin/src/main/assembly/descriptors/plugin.xml, assemblies/pmr-libraries/pom.xml, assemblies/pmr-libraries/src/main/descriptors/assembly.xml, impl/shim/hbase/pom.xml, impl/shim/hdfs/pom.xml, impl/shim/hive/pom.xml, impl/shim/initializer/pom.xml, impl/shim/mapreduce/pom.xml, impl/shim/oozie/pom.xml, impl/shim/pig/pom.xml, impl/shim/shimTests/pom.xml, impl/shim/sqoop/pom.xml, kettle-plugins/hbase/pom.xml, kettle-plugins/hdfs/pom.xml, kettle-plugins/mapreduce/pom.xml, kettle-plugins/pig/pom.xml, legacy/pom.xml
According to Pentaho requirements groupId for CE shims was changed from "pentaho" to "org.pentaho". Necessary changes were applied to big-data-plugin.
The following pull requests should be merged at the same time:
- https://github.com/pentaho/pentaho-hadoop-shims/pull/431;
- https://github.com/pentaho/pentaho-big-data-ee/pull/161;
- https://github.com/pentaho/pentaho-yarn-kettle-plugin/pull/264.
=> [BACKLOG-13800]-Update ant pentaho-big-data-plugin project in relation to transfering of pentaho-hadoop-shims to maven

assemblies/legacy-plugin/pom.xml, pom.xml
Removed emr46 and Added emr52 to the following pom files:
assemblies/legacy-plugin/pom.xml;
pom.xml.
=> [BACKLOG-12886]-Create EMR 5.2 shim against Pentaho 7.1/master

assemblies/legacy-plugin/pom.xml, pom.xml
Removed mapr510 and added mapr520 to the following pom files:
- assemblies/legacy-plugin/pom.xml;
- pom.xml.
Also created:
- mapr520 ce version of the shim (pentaho/pentaho-hadoop-shims#439);
- added mapr520 property to the global version properties file for 7.1-qat (pentaho/build-resources#104).
=> [BACKLOG-13633]-Create and Dev validate the MapR 5.2 shim against Pentaho master / 7.1

legacy/pom.xml, pom.xml
the reason is that https://svn.apache.org/repos/asf/httpcomponents/httpclient/tags/4.5.2/httpclient/src/main/java/org/apache/http/impl/auth/GGSSchemeBase.java -
final GSSName serverName = manager.createName(service + "@" + authServer, GSSName.NT_HOSTBASED_SERVICE); where service = host.getSchemeName().toUpperCase(Locale.ROOT); takes into consideration our url with https which is wrong
while in 4.5.3 new version the logic has been fixed(in 4.5 it's ok too)
https://svn.apache.org/repos/asf/httpcomponents/httpclient/tags/4.5.3/httpclient/src/main/java/org/apache/http/impl/auth/GGSSchemeBase.java - final GSSName serverName = manager.createName("HTTP@" + authServer, GSSName.NT_HOSTBASED_SERVICE);
where http is used
=> [BAD-599] - fix for SPNEGO download shared-object.xml

assemblies/legacy-plugin/pom.xml, pom.xml
added CDH 5.10 shim in list of the shims supplied by default;
deleted CDH 5.8 and CDH 5.9 from the list.
=> [BACKLOG-15075]: Pack CDH 5.10 in big-data-plugin on master branch by default

assemblies/legacy-plugin/pom.xml, assemblies/samples/pom.xml
When targeting the 7.1-SNAPSHOT parent poms, the Maven assembly plugin (v3.0+) requires the `<descriptors>` pom definition to wrap the `<descriptor>` definition.
This should fix the build failure on Cerberus:
http://cerberus.pentaho.com/job/master-snapshot/view/failing/job/big-data-plugin-assembly/529/consoleFull
=> [ENGOPS-2897] Use assembly plugin 3.0 descriptors pom definition

legacy/pom.xml, pom.xml
for s3 httpclient-4.5.3 has logic of switching classloader, which breaks pentaho logic for s3
"So in new code httpclient load Connection manager class using Thread.currentThread().getContextClassLoader();  (which is ApplicationClassloader)
Previously httpclient just uses Class.forName(ClassName) which used Classloader of the calling class. "
According to http://jira.pentaho.com/browse/BAD-599 both httpclient-4.5 and httpclient-4.5.3 works ok with SPENGO, checked with httpclient-4.5 – it doesn’t break s3 and doesn't have switching logic
=> BACKLOG-15193: httpclient to 4.5 - Connect to Amazon S3 storage fails

assemblies/legacy-plugin/pom.xml, pom.xml
What has been done:
Add HDP 2.6 shim into Big Data Plugin.
Delete HDP 2.5 shim from Big Data Plugin.
=> [BAD-673]: Pack HDP 2.6 in big-data-plugin on Pentaho 8.0 (master) branch by default

kettle-plugins/spark/pom.xml, kettle-plugins/spark/src/main/java/org/pentaho/di/job/entries/spark/JobEntrySparkSubmit.java, kettle-plugins/spark/src/main/java/org/pentaho/di/job/entries/spark/WinProcess.java, kettle-plugins/spark/src/main/resources/org/pentaho/di/job/entries/spark/messages/messages_en_US.properties, kettle-plugins/spark/src/test/java/org/pentaho/di/job/entries/spark/WinProcessTest.java, kettle-plugins/spark/src/test/resources/ChildProcessTester.java, kettle-plugins/spark/src/test/resources/process.cmd
Kill the child win process by pid and remove join operation for threads in case when blocking is enabled.
Added WinProcess class to kill child win processes.
See this pull request along with https://github.com/pentaho/pentaho-karaf-assembly/pull/363
=> [BAD-615]-Spark on Windows: PDI doesn't receive response from Resource Manager when "Blocking" is disabled in Spark submit step

impl/vfs/hdfs/src/main/java/org/pentaho/big/data/impl/vfs/hdfs/nc/NamedClusterFileObject.java, impl/vfs/hdfs/src/main/java/org/pentaho/big/data/impl/vfs/hdfs/nc/NamedClusterFileSystem.java, impl/vfs/hdfs/src/main/java/org/pentaho/big/data/impl/vfs/hdfs/nc/NamedClusterProvider.java, kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/input/ParquetInput.java, kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/output/ParquetOutput.java
!Review and merge this PR first: https://github.com/pentaho/pentaho-kettle/pull/4403
@bmorrise please review.
=> [BACKLOG-17900] - Implement read/write Parquet format functionality in PDI steps via Shim API - resolve Hadoop cluster file paths

assemblies/legacy-plugin/pom.xml, pom.xml
In big-data-plugin we should have only one latest shim for each vendor. As emr58 was added before, so emr56 has been removed. Also cdh511 has been removed.
See this pull request along with:
- https://github.com/pentaho/pentaho-hadoop-shims/pull/559
- https://github.com/pentaho/build-resources/pull/143
=> [BAD-1034]-remove emr56, cdh511 shims

assemblies/pmr-libraries/pom.xml, assemblies/pmr-libraries/src/main/descriptors/assembly.xml
=> [BACKLOG-18998] - Pentaho MapReduce with Hbase Row Decoder is failing in hdp26 secure due to org.apache.hadoop.hbase.UnknownScannerException

kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInputMeta.java, kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaProducerOutputMeta.java, kettle-plugins/kafka/src/test/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInputMetaTest.java, kettle-plugins/kafka/src/test/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaProducerOutputMetaTest.java, kettle-plugins/kafka/src/test/resources/abortParent.ktr
If a user entered a string with a space for the property the saving of
the KTR would break since the property is used as a tag. Moving property
to an attribute
=> [BACKLOG-19044] Kafka: Move consumer Options to be stored as attributes

kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/output/AvroOutput.java
This PR is a cherry pick from https://github.com/pentaho/big-data-plugin/pull/1120/commits/97303fb27170c2c51545ca4b3f193df99bf6a9dd
=> [BACKLOG-19399] AEL Spark - Not getting Step Metrics for Avro and Parquet Output steps

kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileInputDialog.java, kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileInputMeta.java, kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileOutputDialog.java, kettle-plugins/hdfs/src/main/resources/org/pentaho/big/data/kettle/plugins/hdfs/trans/messages/messages_en_US.properties
- injectable "Environment" field was added
- new HadoopFileInputMeta constructor was added
- new message string was added
=> [PDI-16816] Hadoop File Input misses Environment field in ETL Metadata Injection

assemblies/legacy-plugin/pom.xml, pom.xml
Update Big Data Plugin in order to include only the last shim version of CDH and EMR vendors.
=> [BAD-1420]-remove cdh512 and emr58 from big-data-plugin

kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/avro/output/AvroOutputField.java
Fixes an issue with opening 8.0 transformations with an AvroOutput step.
=> [BACKLOG-21076] Update the AvroOutput Dialog to support BigDecimal precision and scale.

legacy/src/main/java/org/pentaho/amazon/AbstractAmazonJobExecutorController.java, legacy/src/test/java/org/pentaho/amazon/AbstractAmazonJobExecutorControllerTest.java
Set Connect button and Emr settings fields disabled when Job Flow Id field is not empty.
=> [BAD-1224]-Amazon EMR Job Executor and Amazon EMR Hive Executor steps fail to run (disable Connect button when jobFlowId is set)

kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTClientBuilder.java, kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTConsumer.java, kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTProducer.java, kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTStreamSource.java, kettle-plugins/mqtt/src/main/resources/org/pentaho/di/trans/step/mqtt/messages/messages_en_US.properties, kettle-plugins/mqtt/src/test/java/org/pentaho/di/trans/step/mqtt/MQTTClientBuilderTest.java, kettle-plugins/mqtt/src/test/java/org/pentaho/di/trans/step/mqtt/MQTTConsumerTest.java, kettle-plugins/mqtt/src/test/java/org/pentaho/di/trans/step/mqtt/MQTTStreamSourceTest.java
Splitting MqttClient construction out so it can be reused by producer.
https://jira.pentaho.com/browse/BACKLOG-21243
=> [BACKLOG-21243] MQTT Consumer - Implement Secure Protocol Support

kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTClientBuilder.java, kettle-plugins/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTConsumerDialog.java
1) Moving security tab to before batch,
2) debug logging of connection options.
3) Dialog height set to match ux
4) SSL table shows 4 rows
5) SSL table now greys out when disabled.
6) Attached "Use secure protocol" to the checkbox for even spacing
across platforms (formerly bunched up on Windows)
https://jira.pentaho.com/browse/BACKLOG-21243
=> [BACKLOG-21243] MQTT Consumer - SSL

legacy/src/main/resources/org/pentaho/di/trans/steps/avroinput/messages/messages_en_US.properties
Changing the name from "Old Avro Input" to "Avro Input-Legacy"
@mbatchelor
=> [PDI-17035] AVRO input step from 7.1 not compatible with 8.0

kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/orc/input/OrcInputMetaBase.java, kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/orc/input/OrcInput.java, kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/orc/input/OrcInputDialog.java
@rmansoor The build is currently broken due to a change to BaseFileInputMeta.java made by another team. It just so happens that some of the work I did for BACKLOG-22076 makes the problem go away. There is an accompanying pull request to pentaho-ee that also needs to be processed.
=> BACKLOG-22076 Orc Input Metadata Injection does not work.

kettle-plugins/formats-meta/src/main/java/org/pentaho/big/data/kettle/plugins/formats/parquet/output/ParquetOutputMetaBase.java, kettle-plugins/formats-meta/src/test/java/org/pentaho/big/data/kettle/plugins/formats/parquet/output/ParquetOutputMetaBaseTest.java
- fixed: change compare from equals to equalsIgnoreCase and use "None" as default value
=> [BAD-1423]-Parquet Output step: NPE appears if a user use in "Compression" dropdown values with different letter case or another value

kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInputDialog.java, kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaProducerOutputDialog.java, kettle-plugins/kafka/src/main/resources/org/pentaho/big/data/kettle/plugins/kafka/messages/messages_en_US.properties
[BACKLOG-22133] Remove options table label from kafka consumer and producer options tabs
=> [BACKLOG-22133] Remove options table label from kafka consumer and producer options tabs

legacy/src/main/resources/org/pentaho/amazon/emr/ui/AmazonElasticMapReduceJobExecutorDialog.xul, legacy/src/main/resources/org/pentaho/amazon/hive/ui/AmazonHiveJobExecutorDialog.xul
Reset the size to default values (Linux) for the following fields:
- Step name;
- Access key;
- Secret key.
=> [BACKLOG-22761]-Amazon Hive Job Executor and Amazon EMR Job Executor: Linux: Size of the steps' window doesn't fit all fields in it

kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileOutputMeta.java, kettle-plugins/hdfs/src/test/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileOutputMetaTest.java, legacy/src/main/java/org/pentaho/amazon/s3/S3FileOutputDialog.java, legacy/src/main/java/org/pentaho/amazon/s3/S3FileOutputMeta.java
[PDI-16893] TextFileOutput has a dangerous "feature" allowing data to be piped to OS commands.
removed capability run as command from TextFileOutput
=> [PDI-16893] TextFileOutput has a dangerous "feature" allowing data to be piped to OS commands.

kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/input/AvroInput.java, kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/orc/input/OrcInput.java, kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/input/ParquetInput.java, kettle-plugins/formats/src/test/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/input/AvroInputTest.java
https://github.com/pentaho/pentaho-hadoop-shims/pull/808
=> [BACKLOG-24118] - Parquet Input fails on Secured shims moved to OSGI (EE specific)

assemblies/features/src/main/resources/features.xml
- Created a feature for pentaho-big-data-kettle-plugins-formats
- Added Avro dependencies to the pentaho-big-data-kettle-plugins-formats 
feature
=> [BACKLOG-25185] Avro Input Step - Backport Get Fields Functionality from the 7.1 Avro Input Step (NON-AEL)

assemblies/pmr-libraries/pom.xml, assemblies/pmr-libraries/src/main/descriptors/assembly.xml, kettle-plugins/mapreduce/pom.xml
This is one of a series of PRs. See pentaho/maven-parent-poms#70 for the complete list and more details. **Do not merge until further notice!**
@graimundo
=> [PPP-4182] Use of vulnerable component dom4j-1.6.1.jar  CVE-2018-1000632

assemblies/pmr-libraries/pom.xml, assemblies/pmr-libraries/src/main/descriptors/assembly.xml
@pedrofvteixeira please review.
Merge with: https://github.com/pentaho/pentaho-platform/pull/4305
=> [BISERVER-14068] Remove Apache Axis axis-1.4.jar and axis-saaj-1.4.jar

assemblies/pmr-libraries/pom.xml
This is a series of PRs, please see https://github.com/pentaho/maven-parent-poms/pull/82 for full list.
@ssamora
=> [PPP-4226] Use of vulnerable component commons-compress  CVE-2018-11771

assemblies/pmr-libraries/pom.xml
* [PPP-4266] Removing the version reference in the pmr libraries, it will rely on the version written in the maven-parent-poms project instead.
This is a series of PRs, please see pentaho/maven-parent-poms#83
=> [PPP-4266] Use of Vulnerable Component commons-fileupload CVE-2016-1000031

assemblies/pmr-libraries/pom.xml
This is a series of PRs, please see: https://github.com/pentaho/maven-parent-poms/pull/85
=> [SP-4828] - Backport of PPP-4266 - Use of Vulnerable Component: commons-fileupload-1.3.2.jar (CVE-2016-1000031 | sonatype-2014-01730) (7.1 Suite)

assemblies/pmr-libraries/pom.xml
This is a series of PRs, please see: https://github.com/pentaho/maven-parent-poms/pull/86
=> [SP-4827] - Backport of PPP-4266 - Use of Vulnerable Component: commons-fileupload-1.3.2.jar (CVE-2016-1000031 | sonatype-2014-01730) (7.1 Suite)

assemblies/pmr-libraries/pom.xml, osgi-jaas/pom.xml, pom.xml
@graimundo and @Pancho7 please review.
We are effectively upgrading org.apache.karaf.jaas from 2.4.2 to 3.0.3. Not sure why we had that old version and if it will have any impact...
Note that this targets pentaho:karaf_update, so wingman will not run. Our build pipeline will, when all related PRs are merged.
Needs [pentaho/maven-parent-poms#107](https://github.com/pentaho/maven-parent-poms/pull/107).
=> [BACKLOG-27577] Centralize karaf dependencies management

assemblies/pmr-libraries/pom.xml
Makes commons-dbcp a transitive dependency of kettle core.
=> [BAD-1524]

kettle-plugins/sqoop/src/main/java/org/pentaho/big/data/kettle/plugins/sqoop/AbstractSqoopJobEntry.java
Rebuilt after change and successfully tested on CDH61Sec cluster
=> Fix for misleading errors in sqoop jobs

kettle-plugins/hadoop-cluster/ui/src/main/javascript/app/components/hadoopcluster/hadoopcluster.component.js
Apparently javascript lambdas don't work with the SWT browser
on Windows and Ubuntu, but do on Mac.
Removing lambdas.
https://jira.pentaho.com/browse/BACKLOG-30592
=> [BACKLOG-30592] Add Shim/driver to Cluster Configuration

impl/shim/pig/src/main/java/org/pentaho/big/data/impl/shim/pig/WriterAppenderManager.java
Remove wrong comment with reference to kettle5-log4j-plugin.
Where was kettle5-log4j-plugin should be kettle5-log4j-core
=> [BACKLOG-30801] - Remove wrong comment reference

assemblies/legacy-plugin/src/main/assembly/resources/plugin.properties, impl/cluster/src/main/java/org/pentaho/big/data/impl/cluster/NamedClusterManager.java, impl/cluster/src/test/java/org/pentaho/big/data/impl/cluster/NamedClusterManagerTest.java, impl/cluster/src/test/resources/plugin.properties
location in the big-data-plugin plugin.properties file when running on a
pentaho slave server.
=> [BACKLOG-31075] Add the ability for a user to specify a metastore

assemblies/features/src/main/feature/feature.xml, assemblies/legacy-plugin/pom.xml, assemblies/pmr-libraries/pom.xml, legacy/pom.xml, pom.xml
This is part of a series of PRs. See https://github.com/pentaho/maven-parent-poms/pull/170 for details.
**Don't merge before the PR above.**
Removing unnecessary dependencies from `legacy` module. Changes to `feature.xml` don't cause any differences in the final assembly.
=> [PPP-4448] Use of Vulnerable Component - XStream 1.4.10

legacy/src/main/java/org/pentaho/amazon/s3/S3Details.java, legacy/src/test/java/org/pentaho/amazon/s3/S3DetailsTest.java
Used to get connection info w/o adding a dependency on big-data-legacy
to the shims.
https://jira.pentaho.com/browse/BACKLOG-30731
=> [BACKLOG-30731] Added S3Details.getProperties

kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileInputMeta.java, kettle-plugins/hdfs/src/main/resources/OSGI-INF/blueprint/blueprint.xml, kettle-plugins/hdfs/src/test/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileInputMetaTest.java
ktr in the repository when the ktr references a named cluster that does
not exist.
=> [BACKLOG-32178] Correct error when trying to import, save, and reopen a

kettle-plugins/common/ui/src/main/java/org/pentaho/big/data/plugins/common/ui/HadoopClusterDelegateImpl.java, kettle-plugins/common/ui/src/main/resources/org/pentaho/big/data/plugins/common/ui/messages/messages_en_US.properties
[BACKLOG-29907] Changing to platform independent method to backup config file
Hey @angel-ramoscardona, @jgminder, @peterrinehart: Could you please take a look at this pull request? Thanks!
=> Multishim: Changing the vendor shim of a fully configured cluster does not set back to default

assemblies/legacy-plugin/src/main/assembly/resources/plugin.properties, impl/cluster/src/main/java/org/pentaho/big/data/impl/cluster/NamedClusterManager.java
adding a new one for this release.
=> [BACKLOG-31426] Use active.hadoop.configuration variable in place of

kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/input/AvroInput.java, kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/input/AvroInputDialog.java, kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/output/AvroOutput.java, kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/avro/output/AvroOutputMeta.java, kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/orc/input/OrcInput.java, kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/orc/output/OrcOutput.java, kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/orc/output/OrcOutputMeta.java, kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/input/ParquetInput.java, kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/output/ParquetOutput.java, kettle-plugins/formats/src/main/java/org/pentaho/big/data/kettle/plugins/formats/impl/parquet/output/ParquetOutputMeta.java
Doing variable substitution prior to getting namedcluster in each
of the 6 places we retrieve the named cluster (parquet/orc/avro, in/out).
Would love to see this refactored to reduce the duplication post 9.0.
https://jira.pentaho.com/browse/BACKLOG-32824
=> [BACKLOG-32824] Avro/Parquet/Orc don't allow variables in filename

kettle-plugins/hadoop-cluster/ui/src/main/javascript/app/components/import/import.component.js, kettle-plugins/hadoop-cluster/ui/src/main/javascript/app/components/newEdit/newEdit.component.js
Last commit removed the repo message on new / import
https://jira.pentaho.com/browse/BACKLOG-32617
=> [BACKLOG-32617] repoConnection still needs to be set in init

assemblies/legacy-plugin/src/main/assembly/resources/plugin.properties
of timeouts when connecting to HDFS.
=> [BACKLOG-32812] Create a property to allow users to configure the number

impl/cluster/src/main/java/org/pentaho/big/data/impl/cluster/NamedClusterManager.java
used when running Carte jobs to avoid interfering with other processes
that might be running.
=> [BACKLOG-33079] Ensure metastore under big data plugin folder is only

impl/connections/s3/pom.xml, impl/connections/s3/src/main/resources-filtered/app/package.json, kettle-plugins/hadoop-cluster/pom.xml, kettle-plugins/hadoop-cluster/ui/pom.xml, kettle-plugins/hadoop-cluster/ui/src/main/java/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/dialog/HadoopClusterDialog.java, kettle-plugins/hadoop-cluster/ui/src/main/javascript/app/app.animation.js, kettle-plugins/hadoop-cluster/ui/src/main/javascript/app/app.module.js, kettle-plugins/hadoop-cluster/ui/src/main/resources-filtered/app/index.html, kettle-plugins/hadoop-cluster/ui/src/main/resources-filtered/app/package.json
Related PRs:
https://github.com/pentaho/pentaho-kettle/pull/7311
https://github.com/pentaho/pdi-plugins-ee/pull/169
=> [BACKLOG-33449 BACKLOG-33406] Upgrade Angular JS library from 1.5.8 version to 1.7.8 for pentaho-kettle

assemblies/pmr-libraries/pom.xml, impl/clusterTests/pom.xml, kettle-plugins/kafka/pom.xml, pom.xml
* [PPP-4496] Upgrading to version 0.10.2.2
* [PPP-4496] Removing version reference, maven-parent-pom will control version info.
This is from a series of Pull Requests:
- https://github.com/pentaho/maven-parent-poms/pull/218
- https://github.com/pentaho/big-data-plugin/pull/2032
- https://github.com/pentaho/pdi-plugins-ee/pull/168
- https://github.com/pentaho/pentaho-platform/pull/4649
- https://github.com/pentaho/pentaho-reporting/pull/1327
- https://github.com/pentaho/pentaho-reportdesigner-ee/pull/152
- https://github.com/pentaho/pentaho-metadata-editor/pull/190
- https://github.com/pentaho/pentaho-metadata-editor-ee/pull/85
- https://github.com/pentaho/pentaho-kettle/pull/7309
- https://github.com/pentaho/pentaho-big-data-ee/pull/441
=> [PPP-4496] Use of Vulnerable Component: Components/kafka

kettle-plugins/hadoop-cluster/ui/src/main/java/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/endpoints/HadoopClusterManager.java, kettle-plugins/hadoop-cluster/ui/src/test/java/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/endpoints/HadoopClusterManagerTest.java, kettle-plugins/hadoop-cluster/ui/src/test/resources/dataproc/core-site.xml, kettle-plugins/hadoop-cluster/ui/src/test/resources/dataproc/hdfs-site.xml, kettle-plugins/hadoop-cluster/ui/src/test/resources/dataproc/hive-site.xml, kettle-plugins/hadoop-cluster/ui/src/test/resources/dataproc/mapred-site.xml, kettle-plugins/hadoop-cluster/ui/src/test/resources/dataproc/yarn-site.xml
1. Google Dataproc 1.4 site xml files have different properties in site xml files, modified xml parsing logic to include them
2. Supports HDFS, Yarn(hostname only) for default clusters, supports zookeerper also for HA clusters
3. Oozie address is not supported as the property is not available in oozie-site.xml
=> [BACKLOG-34078] - Site XML parsing logic for Google Dataproc files

kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaStreamSource.java
This commit is a cherry-pick from master e64c6e7f9.
=> [SP-5876] Log kafka consumer exceptions that stop row processing.

kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaStreamSource.java
This commit is a cherry-pick from master e64c6e7f9.
=> [SP-5875] Log kafka consumer exceptions that stop row processing.

impl/vfs/hdfs/src/main/java/org/pentaho/big/data/impl/vfs/hdfs/AzureHdInsightsFileNameParser.java, impl/vfs/hdfs/src/main/resources/OSGI-INF/blueprint/blueprint.xml, impl/vfs/hdfs/src/test/java/org/pentaho/big/data/impl/vfs/hdfs/AzureFileNameParserTest.java
Updated to enable file system parser to list and select files on Azure HDInsights shim jobs
=> [BACKLOG-35131] Add Azure parser for AzureHDInsights specific scheme's

kettle-plugins/hadoop-cluster/ui/src/main/java/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/endpoints/HadoopClusterManager.java, kettle-plugins/hadoop-cluster/ui/src/test/java/org/pentaho/big/data/kettle/plugins/hadoopcluster/ui/endpoints/HadoopClusterManagerTest.java
Alternate PR to master instead of https://github.com/pentaho/big-data-plugin/pull/2153
Setting storageScheme as maprfs for NamedClusters based on the Shim Vendor.
This change sets the storage scheme to maprfs in the NamedCluster.
This change resonates across successful execution of Hadoop copy files directory structure and also with HBase jobs.
=> [BACKLOG-34864] - Determining Storage Scheme for Mapr Clusters using Shim Vendor attribute

kettle-plugins/sqoop/src/main/java/org/pentaho/big/data/kettle/plugins/sqoop/AbstractSqoopJobEntry.java
bridging them to the kettle log system to avoid mixing log messages from
separate processes together.
=> [BACKLOG-35556] Ensure logs from sqoop jobs get their own appenders

assemblies/pmr-libraries/pom.xml, impl/vfs/hdfs/pom.xml, kettle-plugins/common/job/pom.xml, kettle-plugins/common/ui/pom.xml, kettle-plugins/hadoop-cluster/pom.xml, kettle-plugins/hadoop-cluster/ui/pom.xml, kettle-plugins/hbase-meta/pom.xml, kettle-plugins/hbase/pom.xml, kettle-plugins/hdfs/pom.xml, kettle-plugins/hive/pom.xml, kettle-plugins/kafka/pom.xml, kettle-plugins/mapreduce/pom.xml, kettle-plugins/oozie/pom.xml, kettle-plugins/spark/pom.xml, kettle-plugins/sqoop/pom.xml, legacy-amazon/pom.xml, legacy/pom.xml, s3-vfs/pom.xml
more than just kettle version params actually;   this allows us to use version merger for partial builds like CUSTs and shims
=> [DEVO-4654] fix kettle version params

kettle-plugins/common/ui/src/main/resources/apachesampleconfig.properties, kettle-plugins/common/ui/src/main/resources/cdh514sampleconfig.properties, kettle-plugins/common/ui/src/main/resources/cdh61sampleconfig.properties, kettle-plugins/common/ui/src/main/resources/dataproc1421sampleconfig.properties, kettle-plugins/common/ui/src/main/resources/emr521sampleconfig.properties, kettle-plugins/common/ui/src/main/resources/hdi40sampleconfig.properties, kettle-plugins/common/ui/src/main/resources/hdp26sampleconfig.properties, kettle-plugins/common/ui/src/main/resources/hdp30sampleconfig.properties, kettle-plugins/common/ui/src/main/resources/mapr60sampleconfig.properties, kettle-plugins/common/ui/src/main/resources/mapr61sampleconfig.properties
[All Shims] Discrepancies in Copyright Years detail in config.properties file with all different Shims. (#2289)
(cherry picked from commit 2b5963b652916d153afac5846d814f1ac550fd14)
=> [Backlog-35741] Discrepencies in Copyright Years in shims are updated

kettle-plugins/common/ui/src/main/resources/cdpdc71sampleconfig.properties
Incorrect config.properties file is getting created for Hadoop Cluster connection with CDP71 shim. (#2288)
(cherry picked from commit 6ff00aeacaaf12b1257c2d500e5caa0a9bbf98de)
=> [Backlog-35705][Bigdata|CDP71] - Incorrect config.properties file is resolved

assemblies/features/src/main/feature/feature.xml, kettle-plugins/hadoop-cluster/pom.xml, pom.xml
dependencies for hadoop cluster UI.  Some dependencies necessary for the hadoop cluster UI were previously being loaded by other plugins which are no longer present.
=> [BACKLOG-36466] Ensure all js dependencies are declared as bundle

assemblies/pmr-libraries/pom.xml, assemblies/pmr-libraries/src/main/descriptors/assembly.xml
and match latest used by license manager.
=> [BACKLOG-37368] Update bouncycastle dependencies to remove old version

assemblies/pmr-libraries/pom.xml, assemblies/pmr-libraries/src/main/descriptors/assembly.xml
@andreramos89 
@smmribeiro 
Original PR: https://github.com/pentaho/big-data-plugin/pull/2402
=> [SP-6319] - Backport of PPP-3713 - Beanshell version we're using is vulnerable to serialization exploit - CVE-2016-2510 (9.3 Suite)

assemblies/pmr-libraries/pom.xml, assemblies/pmr-libraries/src/main/descriptors/assembly.xml
for karaf ssh service (and presumably anything else in karaf reliant on them).  Standardizing on the jdk15to18 packages since these still work on JDK1.8 (they are not multiversion jars).
=> [BACKLOG-37531] Bouncycastle release/version mismatch causing problems

s3-vfs/src/main/java/org/pentaho/amazon/s3/provider/S3Provider.java
Prevents KettleVFS from loading other connections, causing infinite recursion.
=> [BACKLOG-38056] use an empty Variable space

legacy-amazon/pom.xml
Adding back the removed dependency with scope tests to fix failing unit test (AbstractAmazonJobExecutorTest.testGetS3FileObjectPath_validPath()).
=> [BACKLOG-36262] - Localization missing for DetectLastRow step and other in PDI

assemblies/kafka-plugin/pom.xml, assemblies/kafka-plugin/src/assembly/assembly.xml
pentaho-streaming-kafka-plugin-zip to
pentaho-streaming-kafka-plugin and
fixed the id in the following path assemblies/kafka-plugin/src/assembly/assembly.xml from pentaho-streaming-kafka-plugin-zip to pentaho-streaming-kafka-plugin
=> renaming the artifact id from

impl/vfs/hdfs/src/main/java/org/pentaho/big/data/impl/vfs/hdfs/HDFSFileObject.java, kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileInputMeta.java, kettle-plugins/hdfs/src/main/resources/OSGI-INF/blueprint/blueprint.xml, kettle-plugins/hdfs/src/test/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileInputMetaTest.java
Input/Output steps to fail if the necessary HDFS file system is not accessible.  This property will effectively override the value of the Required column for any HDFS files in the Hadoop File Input step.
=> [PDI-20140] Add a kettle property and logic to force Hadoop File

assemblies/pmr-libraries/pom.xml, assemblies/pmr-libraries/src/main/descriptors/assembly.xml
connection pool for hibernate, and tomcat handles that.
=> [PPP-4391] Remove c3p0 dependency; was never really used except as a

assemblies/pmr-libraries/pom.xml
- Update groovy minor version to 2.4.21 to address CVE-2020-17521
- exclude transitive dependencies and their vulnerabilities
JIRA: https://hv-eng.atlassian.net/browse/PPP-4784
PR Set:
- https://github.com/pentaho/pentaho-platform/pull/5680
- https://github.com/pentaho/pentaho-reporting/pull/1676
- https://github.com/pentaho/big-data-plugin/pull/2584
- https://github.com/pentaho/pentaho-big-data-ee/pull/612
- https://github.com/pentaho/mondrian/pull/1386
=> [PPP-4784] Vulnerable Component: groovy

assemblies/pmr-libraries/pom.xml
[SP-6602]-Backport of PPP-4968 - Vulnerable Component: xmlbeans 2.5.0 (10.2 Suite)
[SP-6602]: https://hv-eng.atlassian.net/browse/SP-6602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SP-6602]-Backport of PPP-4968 - Vulnerable Component: xmlbeans 2.5.0 (10.2 Suite)

assemblies/pmr-libraries/pom.xml
Covers these PRs
- https://github.com/pentaho/big-data-plugin/pull/2618
- https://github.com/pentaho/big-data-plugin/pull/2619
- https://github.com/pentaho/big-data-plugin/pull/2620
The changes in this repo were really for intermediate testing before the parent pom changes were in. With the parent pom changes (which are already merged for this branch) this PR doesn't really change anything function, but I prefer having explicit versions in the poms, even if it's really only to make it easy to see what version it actually uses from an IDE.
=> [SP-6606] Backport Jetty upgrades

impl/cluster/src/test/java/org/pentaho/big/data/impl/cluster/NamedClusterImplTest.java
VFS2 2.10.0 is not producing URIs as 2.8.0 did in respect of the userinfo component.
From the testing done so far, this does not seem to have impact on the solution.
However, for now, I'm @Ignoring the tests referring this functionality, in case we need to reinstate it later.
@pentaho/tatooine_dev
=> fix[PPP-5649]: remove references to deprecated use of userinfo in URIs

assemblies/pmr-libraries/pom.xml
=> chore[PPP-5719]: move saxon version to pentaho parent pom

kettle-plugins/kafka/src/main/java/org/pentaho/big/data/kettle/plugins/kafka/KafkaConsumerInputMeta.java
Related PR
https://github.com/pentaho/spark-execution/pull/35
https://github.com/pentaho/pentaho-kettle/pull/10058
https://github.com/pentaho/pdi-plugins-ee/pull/2098
=> [BACKLOG-44786] - Update native spark steps (amqp, mqtt. meta inject,kafka) to reference libraries from the pdi plugin

assemblies/legacy-plugin/pom.xml, pom.xml
Issue has been resolved by Devops without these changes and build got successful.
=> Revert "[BACKLOG-44864] Fix build failure caused due to versioning of pmr-libs"
